export type BuiltinPromptCollection = {
  name: string;
  description: string;
  promptText: string;
  sourceRef: string;
};

function collection(name: string, sourceRef: string, focus: string, layout: string, checks: string): BuiltinPromptCollection {
  return {
    name: `Seedream 5 · ${name}`,
    description: `Production-oriented Seedream 5.0 Pro prompt collection for ${focus}. Adapted into PalladiumAI's existing versioned Prompt Workspace from the MIT-licensed Flaq AI prompt library.`,
    sourceRef,
    promptText: `Create a production-ready visual for the user's brief.\n\nFocus: ${focus}.\n\nPrompt structure:\n- Task and audience: state the exact asset, channel, audience and communication goal.\n- Subject: describe people, product, place, information or interface precisely.\n- Scene and composition: ${layout}.\n- Visual language: specify medium, lens/viewpoint where relevant, materials, lighting, palette and texture.\n- Exact text: quote only copy supplied by the user; do not invent brands, URLs, prices, certifications or metrics.\n- Invariants: list identity, geometry, data, writing direction, product details or layout elements that must remain unchanged.\n- Avoid: watermarks, unrelated logos, duplicated subjects, broken anatomy, garbled text, impossible reflections, unsupported claims and fabricated facts.\n- Acceptance checks: ${checks}.\n\nWhen editing an existing image, preserve every invariant not explicitly requested to change. For multi-image work, define the role of each input and maintain identity, material and lighting continuity. For multilingual output, use the user's exact supplied copy and writing direction rather than silently translating.`,
  };
}

export const SEEDREAM_PROMPT_COLLECTIONS: BuiltinPromptCollection[] = [
  collection('Infographic & Education', 'awesome-seedream-5-prompts:prompts/01-infographic-education.md', 'infographics, educational visuals, diagrams, technical cutaways and data-led explainers', 'use explicit hierarchy, numbered flows, legends and clear information zones; map every chart or label to supplied data', 'all steps and labels are present, values match the input, arrows and diagrams are logically consistent, and the result stays legible at the intended size'),
  collection('Advertising & Social', 'awesome-seedream-5-prompts:prompts/02-advertising-social.md', 'campaign visuals, social assets, thumbnails, posters, launches and conversion-oriented creative', 'reserve intentional copy space, keep one dominant visual idea and respect channel crop/safe areas', 'the product or message is unmistakable, exact copy appears once, the thumbnail remains readable, and no platform or brand facts were invented'),
  collection('Product & E-commerce', 'awesome-seedream-5-prompts:prompts/03-product-ecommerce.md', 'product photography, e-commerce galleries, packaging, material studies and merchandising', 'keep product geometry stable across views, use credible contact shadows and controlled studio or environmental lighting', 'shape, colour, labels and materials remain consistent; reflections and shadows are physical; no fake specifications or certifications appear'),
  collection('Portrait Photography', 'awesome-seedream-5-prompts:prompts/04-portrait-photography.md', 'portraits, editorial people photography, character continuity and expressive photography', 'define framing, lens feel, pose, gaze, wardrobe, background depth and key/fill/rim lighting deliberately', 'identity is continuous, skin and anatomy remain natural, styling matches the brief, and no demographic or biographical details are invented'),
  collection('Storyboard & Comics', 'awesome-seedream-5-prompts:prompts/05-storyboard-comics.md', 'storyboards, comics, sequential panels and scene continuity', 'number panels, define shot size and camera direction, track characters/props and preserve screen direction between shots', 'characters, wardrobe, props and locations stay continuous; panel order is clear; dialogue/captions exactly match supplied text'),
  collection('UI, Web & Game', 'awesome-seedream-5-prompts:prompts/06-ui-web-game.md', 'website comps, UI concepts, game assets and implementation-friendly digital product visuals', 'use realistic grids, spacing, component states, readable UI copy and device/platform constraints rather than decorative pseudo-interfaces', 'the hierarchy is implementable, controls are plausible, text is readable, responsive intent is clear and no fake platform data is presented as real'),
  collection('Brand & Typography', 'awesome-seedream-5-prompts:prompts/07-brand-typography.md', 'brand systems, typography-led layouts, identity applications and visual-world exploration', 'build a coherent system across mark, type, palette, imagery and applications; use sparse intentional typography', 'all marks are original, typography is legible, applications share one identity system and no third-party logo or trademark is imitated'),
  collection('Architecture, Food & Travel', 'awesome-seedream-5-prompts:prompts/08-architecture-food-travel.md', 'architecture, interiors, food photography, hospitality and travel imagery', 'define viewpoint, time, weather/light, material response, spatial scale and human activity where relevant', 'perspective and materials are coherent, food looks edible, spaces are structurally plausible and no venue/location facts are invented'),
  collection('Editing & Compositing', 'awesome-seedream-5-prompts:prompts/09-editing-compositing.md', 'precision image edits, object replacement, cleanup, relighting and multi-image compositing', 'state exactly what changes and explicitly list everything that must remain fixed; match perspective, lens, grain, colour and light across inserted material', 'only requested regions change, identity/geometry outside the edit is preserved and seams, shadows, reflections and occlusion are convincing'),
  collection('Multilingual Localisation', 'awesome-seedream-5-prompts:prompts/10-multilingual-localization.md', 'localised visual assets, multi-language typography and writing-direction-sensitive layouts', 'reserve text boxes by language, preserve exact copy, punctuation and writing direction, and adapt layout rather than shrinking text blindly', 'every language string is complete, directions are correct, hierarchy is equivalent across locales and no unintended translation appears'),
  collection('Illustration, Art & Materials', 'awesome-seedream-5-prompts:prompts/11-illustration-art-materials.md', 'illustration, stylised art, material exploration and tactile visual systems', 'specify medium, mark-making, surface, palette, edge quality, depth and composition without copying a living artist or protected character style', 'materials read consistently, composition serves the brief, the result is original and style language is descriptive rather than an imitation request'),
  collection('History, Classical & Culture', 'awesome-seedream-5-prompts:prompts/12-history-classical-culture.md', 'historical reconstruction, museum-style visuals, classical subjects and culturally grounded scenes', 'separate known evidence from speculative reconstruction, define period-appropriate materials and avoid inserting modern branding', 'uncertain details are not presented as fact, clothing/objects are internally period-consistent and culturally sensitive elements are handled accurately'),
  collection('Documents & Publishing', 'awesome-seedream-5-prompts:prompts/13-documents-publishing.md', 'covers, spreads, editorial pages, reports, posters and publishing systems', 'define trim/aspect, margins, baseline rhythm, image/copy hierarchy and production-safe text zones', 'copy is complete, hierarchy survives print/screen scaling, margins are usable and no fake ISBN, publisher, source or citation is invented'),
  collection('Creative Practical Workflows', 'awesome-seedream-5-prompts:prompts/14-creative-practical-workflows.md', 'repeatable creative pipelines, campaign systems, asset families and production workflows', 'define a master visual system first, then enumerate variants, crops and deliverables while keeping invariants explicit', 'the family is consistent, each deliverable is independently usable, required variants are all present and shared assets remain visually stable'),
  collection('Structured JSON Templates', 'awesome-seedream-5-prompts:prompts/15-structured-json-templates.md', 'structured agent-to-image workflows and machine-readable visual briefs', 'express goal, subject, composition, camera, lighting, palette, exact_text, invariants, avoid and acceptance_checks as explicit fields before rendering', 'the structured brief contains no credentials, every required field is bounded, exact text is preserved and acceptance checks can be evaluated objectively'),
];
