import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // The MCP endpoint files are generated by the integration and rewritten on
    // every sync, so formatting fixes there do not persist.
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "src/routes/mcp.ts",
      "src/routes/\\[.mcp\\]/**",
      "src/routes/\\[.well-known\\]/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
  {
    // Server functions, API routes and the runtime talk to Stripe and to
    // Supabase tables that are newer than the generated `Database` types, so a
    // handful of dynamic shapes are unavoidable there. Security never depends
    // on these types: every value is validated at the boundary (Zod, signature
    // verification, RLS-scoped clients) before use.
    files: [
      "src/routes/api/**/*.ts",
      "src/lib/**/*.server.ts",
      "src/lib/**/*.functions.ts",
      "src/utils/payments.functions.ts",
    ],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
);
