import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Activity,
  Banknote,
  Bot,
  Briefcase,
  CalendarClock,
  CheckCircle2,
  Gauge,
  Heart,
  Plus,
  Radar,
  Rocket,
  Sparkles,
  Target,
  Zap,
} from "lucide-react";
import { PageHeader, Panel, Meter, StatusDot } from "@/components/os/page-shell";
import { StatCard } from "@/components/os/stat-card";
import { AreaTrend, BarsChart, DonutChart } from "@/components/os/charts";
import { Button } from "@/components/ui/button";
import {
  activityFeed,
  departmentLoad,
  missions,
  notifications,
  revenueSeries,
} from "@/lib/os-data";

export const Route = createFileRoute("/app/")({
  head: () => ({
    meta: [
      { title: "Dashboard — PalladiumAI OS" },
      {
        name: "description",
        content:
          "Your AI company at a glance: revenue, live missions, active agents, department uptime and productivity.",
      },
      { property: "og:title", content: "Dashboard — PalladiumAI OS" },
      {
        property: "og:description",
        content: "Revenue, missions, agents and department health in one premium overview.",
      },
    ],
  }),
  component: Dashboard,
});

const schedule = [
  { time: "09:00", title: "AI CEO briefing", meta: "Atlas · 6 min read" },
  { time: "11:30", title: "Nordvale storefront review", meta: "Business · approval" },
  { time: "13:00", title: "Strength session — block 7", meta: "Health · Lyra" },
  { time: "15:30", title: "Enterprise demo · Halcyon Group", meta: "Sales · Rex" },
  { time: "18:00", title: "Tokyo trip logistics kickoff", meta: "Travel · Pilot-01" },
];

const quickActions = [
  { label: "Launch mission", icon: Rocket },
  { label: "Hire employee", icon: Bot },
  { label: "New business", icon: Target },
  { label: "Automate task", icon: Zap },
];

function Dashboard() {
  return (
    <>
      <PageHeader
        eyebrow="Command deck"
        title="Good afternoon, James"
        description="Your workforce completed 1,284 tasks in the last 24 hours and generated £38,410 in revenue while you were away."
        actions={
          <>
            <Button variant="outline" size="sm">
              <CalendarClock className="size-4" /> Today
            </Button>
            <Button variant="hero" size="sm">
              <Plus className="size-4" /> New mission
            </Button>
          </>
        }
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Revenue (MTD)" value="£268,410" delta="+24.8%" icon={Banknote} hint="vs last month" />
        <StatCard label="Missions running" value="12" delta="+3" icon={Radar} hint="2 need approval" />
        <StatCard label="Agents active" value="2,481" delta="+501" icon={Bot} hint="14 departments" />
        <StatCard label="Tasks completed" value="1,284" delta="+11.2%" icon={CheckCircle2} hint="last 24h" />
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Businesses" value="7" delta="+1" icon={Briefcase} hint="3 profitable" />
        <StatCard label="Departments online" value="14 / 16" trend="flat" delta="99.97%" icon={Activity} hint="uptime" />
        <StatCard label="Health score" value="86" delta="+4" icon={Heart} hint="sleep improving" />
        <StatCard label="Productivity" value="94" delta="+2.1%" icon={Gauge} hint="41h saved" />
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        <Panel
          title="Revenue & forecast"
          subtitle="Generated by autonomous business departments"
          className="xl:col-span-2"
          action={
            <span className="rounded-full border border-border px-2.5 py-1 text-[11px] text-muted-foreground">
              8 months
            </span>
          }
        >
          <AreaTrend
            data={revenueSeries}
            xKey="month"
            keys={[
              { key: "revenue", color: "var(--chart-1)" },
              { key: "forecast", color: "var(--chart-2)" },
            ]}
            height={280}
          />
        </Panel>

        <Panel title="Workforce allocation" subtitle="Agents by department load">
          <DonutChart
            height={200}
            data={[
              { name: "Development", value: 34, color: "var(--chart-1)" },
              { name: "Marketing", value: 24, color: "var(--chart-2)" },
              { name: "Business", value: 18, color: "var(--chart-3)" },
              { name: "Creative", value: 14, color: "var(--chart-4)" },
              { name: "Other", value: 10, color: "var(--chart-5)" },
            ]}
          />
          <ul className="mt-4 space-y-2 text-xs">
            {[
              ["Development", "34%", "var(--chart-1)"],
              ["Marketing", "24%", "var(--chart-2)"],
              ["Business", "18%", "var(--chart-3)"],
              ["Creative", "14%", "var(--chart-4)"],
              ["Other", "10%", "var(--chart-5)"],
            ].map(([name, val, color]) => (
              <li key={name} className="flex items-center gap-2">
                <span className="size-2 rounded-full" style={{ background: color }} />
                <span className="min-w-0 flex-1 truncate text-muted-foreground">{name}</span>
                <span className="font-medium">{val}</span>
              </li>
            ))}
          </ul>
        </Panel>
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        <Panel
          title="Live missions"
          subtitle="Autonomous work in progress"
          className="xl:col-span-2"
          action={
            <Button asChild variant="ghost" size="sm">
              <Link to="/app/mission-control">Open Mission Control</Link>
            </Button>
          }
          bodyClassName="p-0"
        >
          <ul className="divide-y divide-border">
            {missions.slice(0, 5).map((m) => (
              <li
                key={m.id}
                className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 px-5 py-4 transition-colors hover:bg-secondary/40"
              >
                <div className="min-w-0">
                  <div className="flex min-w-0 items-center gap-2">
                    <span className="font-mono text-[10px] text-muted-foreground">{m.id}</span>
                    <StatusDot status={m.status} />
                  </div>
                  <p className="mt-1 truncate text-sm font-medium">{m.name}</p>
                  <div className="mt-2 flex items-center gap-3">
                    <Meter value={m.progress} className="max-w-[220px]" />
                    <span className="text-[11px] text-muted-foreground">{m.progress}%</span>
                  </div>
                </div>
                <div className="shrink-0 text-right">
                  <p className="text-xs font-medium">{m.eta}</p>
                  <p className="mt-1 text-[11px] text-muted-foreground">{m.agents} agents</p>
                </div>
              </li>
            ))}
          </ul>
        </Panel>

        <div className="space-y-4">
          <Panel title="Today's schedule" bodyClassName="p-0">
            <ul className="divide-y divide-border">
              {schedule.map((s) => (
                <li key={s.time} className="flex items-start gap-3 px-5 py-3">
                  <span className="w-11 shrink-0 font-mono text-[11px] text-primary">{s.time}</span>
                  <div className="min-w-0">
                    <p className="truncate text-sm">{s.title}</p>
                    <p className="truncate text-[11px] text-muted-foreground">{s.meta}</p>
                  </div>
                </li>
              ))}
            </ul>
          </Panel>

          <Panel title="Quick actions">
            <div className="grid grid-cols-2 gap-2">
              {quickActions.map((a) => (
                <button
                  key={a.label}
                  className="glass group flex flex-col items-start gap-3 rounded-xl p-3.5 text-left transition-all hover:-translate-y-0.5 hover:border-primary/40"
                >
                  <a.icon className="size-4 text-primary" />
                  <span className="text-xs font-medium leading-tight">{a.label}</span>
                </button>
              ))}
            </div>
          </Panel>
        </div>
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        <Panel title="Department load" subtitle="Compute utilisation by department" className="xl:col-span-2">
          <BarsChart data={departmentLoad} xKey="name" dataKey="load" height={230} />
        </Panel>

        <Panel title="Notifications" bodyClassName="p-0">
          <ul className="divide-y divide-border">
            {notifications.map((n) => (
              <li key={n.title} className="px-5 py-3">
                <div className="flex items-center justify-between gap-2">
                  <p className="truncate text-sm font-medium">{n.title}</p>
                  <span className="shrink-0 text-[10px] text-muted-foreground">{n.time}</span>
                </div>
                <p className="mt-0.5 text-[11px] text-muted-foreground">{n.body}</p>
              </li>
            ))}
          </ul>
        </Panel>
      </div>

      <Panel
        title="Activity feed"
        subtitle="Everything your workforce did today"
        action={<Sparkles className="size-4 text-primary" />}
        bodyClassName="p-0"
      >
        <ul className="divide-y divide-border">
          {activityFeed.map((a) => (
            <li key={a.action} className="flex items-center gap-4 px-5 py-3.5">
              <span className="grid size-8 shrink-0 place-items-center rounded-lg border border-border bg-secondary/60 text-primary">
                <a.icon className="size-4" />
              </span>
              <p className="min-w-0 flex-1 truncate text-sm">
                <span className="font-medium">{a.agent}</span>{" "}
                <span className="text-muted-foreground">{a.action}</span>
              </p>
              <span className="shrink-0 text-[11px] text-muted-foreground">{a.time} ago</span>
            </li>
          ))}
        </ul>
      </Panel>
    </>
  );
}
