export type BuiltinPlaybook = {
  name: string;
  description: string;
  body: string;
  sourceRef: string;
};

function skill(name: string, description: string, sourceRef: string, guidance: string): BuiltinPlaybook {
  return {
    name,
    description,
    sourceRef,
    body: `---\nname: ${name}\ndescription: ${description}\nversion: 1.0.0\n---\n\n# ${name}\n\n${guidance.trim()}\n`,
  };
}

export const INTEGRATION_PLAYBOOKS: BuiltinPlaybook[] = [
  skill('brandkit', 'Premium brand-system direction for identity boards, logo systems, visual worlds and implementation-ready brand references.', 'taste-skill:skills/brandkit/SKILL.md', `Start from audience, positioning and brand constraints. Build a coherent logo, type, colour, imagery and application system rather than disconnected mood art. Keep typography sparse, compositions intentional, mockups credible and all generated marks original. Return implementation-ready tokens and usage rules when the task is moving from concept to product.`),
  skill('industrial-brutalist-ui', 'Raw mechanical UI direction using rigid grids, extreme type contrast and utilitarian information hierarchy.', 'taste-skill:skills/brutalist-skill/SKILL.md', `Use Swiss/editorial structure, terminal and blueprint cues, strong hierarchy and deliberate mechanical detail. Prefer functional geometry, bounded colour and dense-but-readable information. Avoid generic SaaS cards, decorative gradients and soft marketing layouts unless the brief requires them.`),
  skill('gpt-taste', 'Conversion-aware high-variance frontend composition and motion guidance.', 'taste-skill:skills/gpt-tasteskill/SKILL.md', `Audit the brief before choosing a layout. Preserve a clear conversion path while varying composition, section rhythm and visual anchors. Use motion only where it explains hierarchy or progression. Keep text readable, avoid repetitive left-copy/right-image sections, and make animation degradable for reduced-motion and small screens.`),
  skill('image-to-code', 'Audit-first workflow for turning visual references into faithful production frontend implementations.', 'taste-skill:skills/image-to-code-skill/SKILL.md', `Inspect the supplied visual reference before editing code. Identify layout, typography, colour, spacing, imagery, states and responsive behaviour. Reuse the existing framework and components, generate only missing assets, then implement the closest maintainable version without breaking existing behaviour. Verify the result at realistic desktop and mobile sizes.`),
  skill('imagegen-frontend-mobile', 'Premium mobile product art-direction for consistent multi-screen app concepts.', 'taste-skill:skills/imagegen-frontend-mobile/SKILL.md', `Treat mobile screens as one product system. Maintain type scale, navigation, component states, icon language, colour and device framing across the flow. Prioritise legibility and thumb-friendly hierarchy. Generate separate useful screens rather than one compressed concept board.`),
  skill('imagegen-frontend-web', 'Premium conversion-aware website art-direction with one clear visual composition per section.', 'taste-skill:skills/imagegen-frontend-web/SKILL.md', `Create an intentional visual concept for every requested section. Vary composition and hero scale while maintaining one palette and narrative spine. Use imagery as layout material where appropriate, preserve realistic content space, and produce references that a frontend engineer can implement without guessing.`),
  skill('minimalist-ui', 'Editorial minimal interface direction using warm monochrome surfaces, careful type and restrained accents.', 'taste-skill:skills/minimalist-skill/SKILL.md', `Use strong whitespace, typographic contrast, restrained borders and flat surfaces. Keep accent colour scarce and semantic. Prefer asymmetric but calm grids, readable line lengths and precise small UI details. Avoid heavy shadows, neon, gratuitous gradients and oversized pill containers.`),
  skill('full-output-enforcement', 'Completeness protocol for production implementation tasks.', 'taste-skill:skills/output-skill/SKILL.md', `Count the requested deliverables before implementation and finish every one. Do not replace required code with placeholders or TODOs. When a task is too large for one execution, stop only at a clean boundary and preserve an exact continuation checkpoint.`),
  skill('redesign-existing-projects', 'Audit-first redesign playbook that improves an existing product without replacing working architecture.', 'taste-skill:skills/redesign-skill/SKILL.md', `Inspect framework, styling, typography, surfaces, layout, responsive behaviour and interaction states. Identify generic or inconsistent patterns, then make targeted changes using the project's existing components and tokens. Preserve routes, data flows and accessibility while improving visual hierarchy and product coherence.`),
  skill('high-end-visual-design', 'High-end UI art direction for deliberate type, depth, motion and layout.', 'taste-skill:skills/soft-skill/SKILL.md', `Choose a visual archetype that fits the product rather than applying a fixed AI aesthetic. Use nested depth, intentional typography, asymmetric composition and controlled motion. Avoid repetitive card grids and generic gradients. Every decorative choice must support hierarchy, affordance or brand character.`),
  skill('stitch-design-taste', 'Semantic design-system guidance for agent-generated frontend specifications.', 'taste-skill:skills/stitch-skill/SKILL.md', `Express design decisions as reusable semantic tokens and component rules. Define typography, colour, spacing, radius, motion and responsive behaviour with enough precision for another agent to implement consistently. Prefer system rules over screenshot-specific hacks.`),
  skill('design-taste-frontend-v1', 'Compatibility playbook preserving the original Taste Skill design-audit behaviour.', 'taste-skill:skills/taste-skill-v1/SKILL.md', `Use the original audit-first Taste approach: identify generic frontend defaults, strengthen hierarchy and composition, then implement with the current project stack. Keep this profile for tasks that explicitly request compatibility with the older Taste workflow.`),
  skill('design-taste-frontend', 'Anti-generic frontend design and redesign playbook for production websites and apps.', 'taste-skill:skills/taste-skill/SKILL.md', `Read the brief and infer the appropriate design direction before writing UI. On redesigns, audit first and preserve working functionality. Use an intentional design system, meaningful imagery, varied composition, generous spacing and implementation clarity. Run a pre-flight check for responsiveness, accessibility, loading/empty/error states and visual repetition before declaring the work complete.`),

  skill('ornith-self-scaffold', 'Bounded self-improvement loop inspired by Ornith: scaffold, execute, verify and learn without granting new authority.', 'ornith-1:README.md', `For a difficult task, first propose the smallest task-specific scaffold: tools, sub-agent roles, checkpoints and success tests. Execute only within existing PalladiumAI grants and depth limits. Verify the result with objective checks. Promote reusable experience into a skill only through PalladiumAI's verified reflection path; never self-enable permissions or invent a successful verification.`),
  skill('raven-long-horizon-harness', 'Long-horizon agent execution using tracing, checkpoints, memory, research escalation and verified reflection.', 'raven:README.md', `Break long work into restart-safe stages. Keep durable checkpoints and concise run context, use existing memory for stable facts, and preserve traceable evidence for important decisions. Escalate broad evidence-heavy questions to the existing research capability. After a verified run, capture reusable procedure through the existing skill-reflection system rather than creating an alternate memory or harness.`),
  skill('superplane-policy-gated-delivery', 'Durable policy-gated delivery using existing PalladiumAI workflows, approvals and integrations.', 'superplane:README.md', `Model delivery as durable workflow steps: trigger, build/test evidence, policy check, approval when required, deployment action, verification and rollback path. Use existing workflow run persistence and approval_requests. Never create a second scheduler or approval table. External CI/CD and incident actions must go through connected integration capabilities.`),
  skill('superplane-progressive-delivery', 'Progressive 10/50/100 style delivery with verification and rollback checkpoints.', 'superplane:README.md', `Represent each rollout wave as an explicit workflow step with measurable success criteria. Pause between waves for health verification; require approval when policy marks the next wave risky. On failure, execute the configured rollback path and preserve the run history for audit.`),
  skill('superplane-incident-first-five', 'Incident triage playbook that gathers evidence in parallel before taking action.', 'superplane:README.md', `When an incident begins, gather recent deploys, health signals, relevant logs, ownership and runbook context through existing integrations. Summarise evidence and confidence before proposing remediation. Mutating actions remain approval/policy gated. Persist the evidence pack in the existing project/knowledge systems rather than creating a separate incident database.`),
  skill('scout-company-intelligence', 'Navigate live company context across web, integrations, CRM, Knowledge and MCP without duplicating source data.', 'scout:README.md', `Prefer navigation over bulk ingestion. Identify the authoritative source, query it through the existing PalladiumAI integration, MCP, CRM, Knowledge or web capability, then follow references until the question is supported. Keep source quirks behind bounded sub-agent/tool calls. Write learned durable facts only to the existing CRM or Knowledge systems when the task and permissions allow it; cite or preserve source references and never copy credentials into memory.`),
];
