export const FREELLMAPI_PROFILE = {
  id: "freellm",
  name: "FreeLLMAPI",
  protocol: "openai-compatible",
  palladiumProvider: "freellm",
  baseUrlEnv: "FREELLMAPI_BASE_URL",
  apiKeyEnv: "FREELLMAPI_API_KEY",
  modelEnv: "FREELLMAPI_MODEL",
  chatPath: "/chat/completions",
  deploymentPathSuffix: "/v1",
  routingOwner: "upstream",
  capabilities: [
    "independent-evaluator-lane",
    "provider-pooling",
    "rate-limit-aware-routing",
    "fallback-routing",
    "streaming",
    "tool-calls",
  ],
} as const;
