import { motion, useReducedMotion } from 'framer-motion';
import { Bot, Building2, Network, Workflow } from 'lucide-react';

export default function CompanyOperatingWorld({ departments=[], lifecycle=[], systems=[] }) {
  const reduced=useReducedMotion();
  const nodes=departments.slice(0,10);
  return <section className="relative overflow-hidden rounded-[30px] border border-cyan-300/12 bg-[#02070a]/92 shadow-[0_36px_110px_rgba(0,0,0,.42)]">
    <div aria-hidden className="absolute inset-0 bg-[radial-gradient(circle_at_50%_43%,rgba(34,211,238,.11),transparent_31%),radial-gradient(circle_at_20%_72%,rgba(139,92,246,.11),transparent_25%)]"/>
    <div className="relative flex flex-wrap items-center gap-3 border-b border-white/7 px-5 py-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.24em] text-cyan-300/70">Corporate operating system</p><h2 className="mt-1 text-lg font-semibold text-white">Company intelligence network</h2></div><div className="ml-auto flex gap-2 font-mono text-[9px] text-zinc-400"><span>{departments.length} departments</span><span>·</span><span>{systems.length} connected systems</span><span>·</span><span>{lifecycle.length} lifecycle stages</span></div></div>
    <div className="relative min-h-[330px] p-5">
      <motion.div aria-hidden className="absolute left-1/2 top-1/2 hidden h-44 w-44 -translate-x-1/2 -translate-y-1/2 rounded-full border border-cyan-300/15 md:block" animate={reduced?undefined:{rotate:[0,360]}} transition={reduced?undefined:{duration:46,repeat:Infinity,ease:'linear'}}/>
      <div className="relative hidden min-h-[290px] md:block"><div className="absolute left-1/2 top-1/2 z-10 w-44 -translate-x-1/2 -translate-y-1/2 text-center"><Building2 className="mx-auto h-8 w-8 text-cyan-200"/><p className="mt-2 text-[9px] uppercase tracking-[.18em] text-zinc-500">Company core</p><p className="mt-1 font-mono text-xl text-white">{systems.length}</p><p className="text-[9px] text-zinc-600">system routes</p></div>{nodes.map(([name,Icon],index)=>{const angle=(index/Math.max(nodes.length,1))*Math.PI*2;const left=50+Math.cos(angle)*39;const top=50+Math.sin(angle)*39;return <motion.div key={name} className="absolute w-[165px] -translate-x-1/2 -translate-y-1/2 rounded-xl border border-white/10 bg-black/72 p-3 backdrop-blur-xl" style={{left:left+'%',top:top+'%'}} animate={reduced?undefined:{y:[0,-4,0]}} transition={reduced?undefined:{duration:4+(index%3),repeat:Infinity,delay:index*.09}}><div className="flex items-center gap-2"><Icon className="h-3.5 w-3.5 text-cyan-200"/><span className="min-w-0 flex-1 truncate text-[9px] text-white">{name}</span></div></motion.div>})}</div>
      <div className="grid gap-2 md:hidden">{nodes.map(([name,Icon])=><div key={name} className="rounded-xl border border-white/10 bg-black/45 p-3"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-cyan-200"/><span className="min-w-0 flex-1 truncate text-xs text-white">{name}</span></div></div>)}</div>
    </div>
    <div className="relative grid gap-2 border-t border-white/7 bg-black/20 px-5 py-3 text-[9px] uppercase tracking-[.12em] text-zinc-500 sm:grid-cols-2"><span className="flex items-center gap-1.5"><Bot className="h-3 w-3"/>existing AI workforce remains authoritative</span><span className="flex items-center gap-1.5"><Workflow className="h-3 w-3"/>company layer coordinates rather than duplicates</span></div>
  </section>;
}
