import { Radar, Waves, Cpu, Scale, Users, Leaf, ShieldAlert, CircleDollarSign } from 'lucide-react';
const lenses=[
 ['Technology & AI',Cpu,'Automation, AI capability, platforms, cyber, new production methods and technical substitution.'],
 ['Regulation & policy',Scale,'New rules, enforcement, standards, trade policy, permits and sector-specific obligations.'],
 ['Customer & demand',Users,'Preference shifts, demographics, channel changes, service expectations and willingness to pay.'],
 ['Economics & capital',CircleDollarSign,'Rates, inflation, input costs, funding, margins, capacity investment and consolidation.'],
 ['Supply & geopolitics',ShieldAlert,'Trade friction, sanctions, chokepoints, supplier concentration, conflict and strategic materials.'],
 ['Climate & resources',Leaf,'Energy, water, emissions, physical climate exposure, adaptation and circularity pressures.'],
];
export default function IndustryDisruptionRadar(){return <section className="rounded-[26px] border border-white/[.08] bg-black/25 p-5 lg:p-6"><div className="flex items-center gap-2 text-red-300"><Radar className="h-4 w-4"/><span className="text-xs font-semibold uppercase tracking-[.16em]">Trend & disruption radar</span></div><h2 className="mt-2 text-xl font-semibold text-white">Monitor the forces capable of changing an industry's economics</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-zinc-500">Blackstar uses these lenses to structure monitoring and research. A lens is not a claim that a disruption is occurring now; current signals require dated, attributable evidence.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{lenses.map(([name,Icon,text])=><article key={name} className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><Icon className="h-5 w-5 text-red-300"/><h3 className="mt-3 text-sm font-medium text-white">{name}</h3><p className="mt-2 text-xs leading-5 text-zinc-500">{text}</p><div className="mt-3 flex gap-2"><span className="rounded-full border border-white/[.06] px-2 py-1 text-[9px] text-zinc-700">Signal</span><span className="rounded-full border border-white/[.06] px-2 py-1 text-[9px] text-zinc-700">Impact</span><span className="rounded-full border border-white/[.06] px-2 py-1 text-[9px] text-zinc-700">Horizon</span></div></article>)}</div></section>}
