import { Radar, TrendingUp, Bot, ShieldCheck, SearchCheck, Workflow } from 'lucide-react';
const workflows=[
 ['Market landscape brief',Radar,'Map market structure, segments, value pools, competitors, substitutes and uncertainty; source current claims through Research/Web Intelligence.'],
 ['Growth opportunity scan',TrendingUp,'Generate and rank product, customer, channel, geography and partnership hypotheses, then validate assumptions before investment.'],
 ['Competitive intelligence',SearchCheck,'Compare public positioning, capabilities, business models and evidence without inventing private competitor information.'],
 ['Operational improvement',Workflow,'Turn a process or KPI problem into root-cause hypotheses, measurement plans, SOP improvements and automation candidates.'],
 ['Industry AI adoption',Bot,'Identify high-value AI use cases by workflow, data readiness, risk, human oversight and measurable outcome rather than deploying AI everywhere.'],
 ['Risk & resilience review',ShieldCheck,'Build an industry-aware risk register covering operations, suppliers, workforce, cyber, market, financial and regulatory dependencies.'],
];
export default function IndustryWorkflows(){return <section className="rounded-[26px] border border-white/[.08] bg-black/25 p-5 lg:p-6"><div className="flex items-center gap-2 text-violet-300"><Bot className="h-4 w-4"/><span className="text-xs font-semibold uppercase tracking-[.16em]">Industry AI workflows</span></div><h2 className="mt-2 text-xl font-semibold text-white">Reusable missions for Blackstar agents and research systems</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">These workflows define what Blackstar should orchestrate using existing agents, Research, Web Intelligence, Finance, Legal, Knowledge and approvals. They do not create a duplicate agent runtime.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{workflows.map(([name,Icon,text])=><article key={name} className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><Icon className="h-5 w-5 text-violet-300"/><h3 className="mt-3 text-sm font-medium text-white">{name}</h3><p className="mt-2 text-xs leading-5 text-zinc-500">{text}</p></article>)}</div></section>}
