import { useEffect, useState } from 'react';
import { Building2, Plus, Trash2, Save } from 'lucide-react';
import { deleteIndustryWorkspace, listIndustryWorkspaces, saveIndustryWorkspace } from '@/lib/industry/industry-workspaces.functions';

const blank={name:'',industry:'Manufacturing & Industry',geography:'',organisation_context:'',objectives:'',notes:''};
export default function IndustryWorkspace(){
 const [items,setItems]=useState([]),[form,setForm]=useState(blank),[error,setError]=useState('');
 const load=()=>listIndustryWorkspaces({data:{}}).then(setItems).catch(e=>setError(e instanceof Error?e.message:'Could not load industry workspaces.'));
 useEffect(()=>{load()},[]);
 const save=async()=>{setError('');try{await saveIndustryWorkspace({data:form});setForm(blank);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save workspace.')}};
 const remove=async(id)=>{try{await deleteIndustryWorkspace({data:{id}});await load()}catch(e){setError(e instanceof Error?e.message:'Could not delete workspace.')}};
 return <section className="rounded-[26px] border border-white/[.08] bg-black/25 p-5 lg:p-6"><div className="flex items-center gap-2 text-emerald-300"><Building2 className="h-4 w-4"/><span className="text-xs font-semibold uppercase tracking-[.16em]">Private industry workspaces</span></div><h2 className="mt-2 text-xl font-semibold text-white">Keep organisation-specific industry context persistent</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Owner-scoped workspaces store your organisation context and objectives so sector work does not have to restart from generic assumptions.</p>
 {error&&<p className="mt-3 rounded-xl border border-rose-300/15 bg-rose-300/[.04] p-3 text-xs text-rose-200">{error}</p>}
 <div className="mt-5 grid gap-3 lg:grid-cols-2"><div className="space-y-3 rounded-2xl border border-white/[.07] p-4"><Field label="Workspace name" value={form.name} set={v=>setForm({...form,name:v})}/><Field label="Industry" value={form.industry} set={v=>setForm({...form,industry:v})}/><Field label="Geography / market" value={form.geography} set={v=>setForm({...form,geography:v})}/><Area label="Organisation context" value={form.organisation_context} set={v=>setForm({...form,organisation_context:v})}/><Area label="Objectives" value={form.objectives} set={v=>setForm({...form,objectives:v})}/><button disabled={!form.name.trim()||!form.industry.trim()} onClick={save} className="flex items-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/[.06] px-4 py-2 text-xs text-emerald-100 disabled:opacity-40"><Save className="h-3.5 w-3.5"/>Save workspace</button></div>
 <div className="space-y-2">{items.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-xs text-zinc-600">No saved industry workspaces yet.</div>:items.map(x=><article key={x.id} className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex justify-between gap-3"><div><h3 className="text-sm font-medium text-white">{x.name}</h3><p className="mt-1 text-xs text-violet-300">{x.industry}{x.geography?' · '+x.geography:''}</p></div><button aria-label="Delete workspace" onClick={()=>remove(x.id)} className="text-zinc-700 hover:text-rose-300"><Trash2 className="h-4 w-4"/></button></div>{x.objectives&&<p className="mt-3 line-clamp-3 text-xs leading-5 text-zinc-500">{x.objectives}</p>}</article>)}</div></div></section>
}
function Field({label,value,set}){return <label className="block"><span className="text-[10px] uppercase tracking-[.1em] text-zinc-600">{label}</span><input value={value} onChange={e=>set(e.target.value)} className="mt-1.5 w-full rounded-xl border border-white/[.07] bg-black/30 px-3 py-2 text-sm text-white outline-none"/></label>}
function Area({label,value,set}){return <label className="block"><span className="text-[10px] uppercase tracking-[.1em] text-zinc-600">{label}</span><textarea value={value} onChange={e=>set(e.target.value)} rows={3} className="mt-1.5 w-full resize-none rounded-xl border border-white/[.07] bg-black/30 px-3 py-2 text-sm text-white outline-none"/></label>}
