import { useMemo, useState } from 'react';
import { Search, Activity, Gauge, Network, ShieldCheck, Lightbulb, Target, Factory } from 'lucide-react';

const playbooks = [
  { sector:'Manufacturing & Industry', valueChain:'Inputs → production → quality → warehousing → distribution → service', kpis:['OEE','Yield','Scrap rate','Cycle time','OTIF','Downtime'], priorities:['Lean flow','Predictive maintenance','Quality systems','Automation','Supplier resilience'], risks:['Single-source suppliers','Unplanned downtime','Energy volatility','Quality escapes'] },
  { sector:'Technology & AI', valueChain:'Research → product → engineering → platform → go-to-market → support', kpis:['ARR/MRR','Gross margin','Retention','Deployment frequency','Availability','CAC payback'], priorities:['Product velocity','AI adoption','Security','Platform reliability','Developer productivity'], risks:['Cyber incidents','Vendor concentration','Technical debt','Regulatory change'] },
  { sector:'Healthcare & Life Sciences', valueChain:'Research → validation → regulatory → delivery → monitoring → outcomes', kpis:['Quality events','Cycle time','Capacity','Service level','Outcome measures','Compliance actions'], priorities:['Quality','Patient/service safety','Evidence','Workflow efficiency','Data governance'], risks:['Safety events','Compliance gaps','Supply shortages','Data/privacy incidents'] },
  { sector:'Energy & Utilities', valueChain:'Generation/source → network → balancing → distribution → customer → asset renewal', kpis:['Availability','Capacity factor','Losses','SAIDI/SAIFI','Unit cost','Emissions intensity'], priorities:['Reliability','Grid flexibility','Asset health','Efficiency','Transition planning'], risks:['Asset failure','Commodity exposure','Weather disruption','Network constraints'] },
  { sector:'Retail & Commerce', valueChain:'Source → buy → merchandise → inventory → channel → fulfilment → loyalty', kpis:['Gross margin','Sell-through','Inventory turns','Conversion','AOV','Return rate'], priorities:['Merchandising','Inventory productivity','Omnichannel','Retention','Pricing'], risks:['Demand error','Stockouts','Margin compression','Supplier failure'] },
  { sector:'Transport & Logistics', valueChain:'Plan → procure capacity → collect → move → hub/warehouse → deliver → recover', kpis:['OTIF','Cost per shipment','Utilisation','Dwell time','Damage rate','Empty miles'], priorities:['Network design','Fleet utilisation','Warehouse flow','Visibility','Resilience'], risks:['Capacity shocks','Fuel costs','Port disruption','Route concentration'] },
  { sector:'Construction & Real Estate', valueChain:'Originate → design → procure → build → commission → operate → renew', kpis:['Schedule variance','Cost variance','Rework','Safety rate','Occupancy','Asset yield'], priorities:['Project controls','Procurement','BIM/data','Safety','Lifecycle cost'], risks:['Cost escalation','Programme delay','Contract risk','Material shortages'] },
  { sector:'Agriculture & Food', valueChain:'Inputs → grow/source → process → assure → distribute → retail/foodservice', kpis:['Yield','Waste','Throughput','Forecast accuracy','Traceability','Service level'], priorities:['Yield','Food safety','Traceability','Waste reduction','Supply resilience'], risks:['Weather','Disease','Input inflation','Cold-chain failure'] },
  { sector:'Financial Services', valueChain:'Acquire → onboard → assess → transact/serve → monitor → retain', kpis:['Cost-to-income','Loss rate','NIM/margin','Retention','STP rate','Complaint rate'], priorities:['Controls','Digital service','Fraud prevention','Automation','Customer value'], risks:['Credit/liquidity','Fraud','Cyber','Conduct/compliance'] },
  { sector:'Professional Services', valueChain:'Market → qualify → scope → staff → deliver → assure → expand', kpis:['Utilisation','Realisation','Margin','Backlog','Win rate','Client retention'], priorities:['Knowledge leverage','Delivery quality','Pricing','Talent','Automation'], risks:['Key-person dependency','Scope creep','Pipeline volatility','Quality failures'] },
];

export default function IndustryOperatingSystem() {
  const [query,setQuery]=useState('');
  const [selected,setSelected]=useState(playbooks[0].sector);
  const visible=useMemo(()=>playbooks.filter(p=>p.sector.toLowerCase().includes(query.toLowerCase())),[query]);
  const active=playbooks.find(p=>p.sector===selected) ?? visible[0] ?? playbooks[0];

  return <section className="rounded-[26px] border border-white/[.08] bg-black/30 p-5 lg:p-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2 text-cyan-300"><Factory className="h-4 w-4"/><span className="text-xs font-semibold uppercase tracking-[.16em]">Industry operating system</span></div><h2 className="mt-2 text-2xl font-semibold text-white">Sector playbooks, KPIs, value chains and transformation priorities</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Use these as operating frameworks, then send current facts, regulations, financial analysis and execution work to Blackstar's connected specialist systems.</p></div><label className="flex min-w-[260px] items-center gap-2 rounded-xl border border-white/[.08] bg-black/30 px-3"><Search className="h-4 w-4 text-zinc-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find an industry…" className="w-full bg-transparent py-2.5 text-sm text-white outline-none placeholder:text-zinc-700"/></label></div>
    <div className="mt-5 flex flex-wrap gap-2">{visible.map(p=><button key={p.sector} onClick={()=>setSelected(p.sector)} className={`rounded-full border px-3 py-1.5 text-xs transition ${active.sector===p.sector?'border-violet-300/25 bg-violet-400/10 text-violet-100':'border-white/[.07] text-zinc-500 hover:text-white'}`}>{p.sector}</button>)}</div>
    <div className="mt-5 grid gap-3 xl:grid-cols-2">
      <Card icon={Network} title="Value chain"><p>{active.valueChain}</p></Card>
      <Card icon={Gauge} title="Core KPI library"><div className="flex flex-wrap gap-2">{active.kpis.map(x=><Tag key={x}>{x}</Tag>)}</div></Card>
      <Card icon={Lightbulb} title="Transformation priorities"><div className="flex flex-wrap gap-2">{active.priorities.map(x=><Tag key={x}>{x}</Tag>)}</div></Card>
      <Card icon={ShieldCheck} title="Common risk lenses"><div className="flex flex-wrap gap-2">{active.risks.map(x=><Tag key={x}>{x}</Tag>)}</div></Card>
    </div>
    <div className="mt-4 grid gap-3 md:grid-cols-3"><Action icon={Activity} title="Assess maturity" text="Benchmark process, data, automation, governance and capability maturity."/><Action icon={Target} title="Find opportunities" text="Turn value-chain friction into growth, efficiency, resilience and innovation opportunities."/><Action icon={Network} title="Build transformation map" text="Sequence people, process, technology, data, controls and measurable outcomes."/></div>
  </section>;
}
function Card({icon:Icon,title,children}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-zinc-500"><Icon className="h-4 w-4 text-violet-300"/>{title}</div><div className="mt-3 text-sm leading-6 text-zinc-300">{children}</div></div>}
function Tag({children}){return <span className="rounded-lg border border-white/[.07] bg-black/25 px-2.5 py-1 text-xs text-zinc-400">{children}</span>}
function Action({icon:Icon,title,text}){return <div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[.025] p-4"><Icon className="h-4 w-4 text-cyan-300"/><h3 className="mt-2 text-sm font-medium text-white">{title}</h3><p className="mt-1 text-xs leading-5 text-zinc-500">{text}</p></div>}
