import { Route, Flag, Database, Users, Cpu, ShieldCheck } from 'lucide-react';
const phases=[
 ['Discover','0–30 days','Baseline KPIs, customer/market evidence, process map, risks and constraints.'],
 ['Design','30–60 days','Target operating model, prioritised use cases, business cases, controls and owners.'],
 ['Pilot','60–120 days','Run bounded pilots with acceptance criteria, human oversight and measurable outcomes.'],
 ['Scale','3–9 months','Standardise successful changes, integrate systems, train teams and expand adoption.'],
 ['Optimise','Ongoing','Track benefits, risk, quality and customer outcomes; retire weak initiatives and compound winners.'],
];
export default function TransformationRoadmap(){return <section className="rounded-[26px] border border-white/[.08] bg-black/25 p-5 lg:p-6"><div className="flex items-center gap-2 text-blue-300"><Route className="h-4 w-4"/><span className="text-xs font-semibold uppercase tracking-[.16em]">Transformation roadmap</span></div><h2 className="mt-2 text-xl font-semibold text-white">Turn industry intelligence into sequenced execution</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">A reusable transformation structure that Blackstar can adapt to the organisation, sector, risk profile and evidence available.</p><div className="mt-5 grid gap-3 xl:grid-cols-5">{phases.map(([name,time,text],i)=><article key={name} className="rounded-2xl border border-white/[.07] p-4"><span className="text-[10px] text-blue-300">{time}</span><h3 className="mt-2 text-sm font-medium text-white">{i+1}. {name}</h3><p className="mt-2 text-xs leading-5 text-zinc-600">{text}</p></article>)}</div><div className="mt-4 flex flex-wrap gap-2">{[['Data',Database],['People',Users],['Technology',Cpu],['Controls',ShieldCheck],['Outcomes',Flag]].map(([x,I])=><span key={x} className="flex items-center gap-1.5 rounded-full border border-white/[.07] px-3 py-1.5 text-xs text-zinc-500"><I className="h-3.5 w-3.5"/>{x}</span>)}</div></section>}
