import {useEffect,useMemo,useState} from 'react';
import {Database,Loader2,Plus,Save,Trash2} from 'lucide-react';
import {deleteWebsiteStudioCollectionItem,listWebsiteStudioCollectionItems,saveWebsiteStudioCollectionItem} from '@/lib/website-studio/website-cms.functions';

export default function WebsiteCmsManager({project}){
 const collections=Array.isArray(project.app_config?.collections)?project.app_config.collections:[];
 const [key,setKey]=useState(collections[0]?.name||'');
 const [rows,setRows]=useState([]);
 const [draft,setDraft]=useState({slug:'',title:'',data:'{}',status:'draft'});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const normalizedKey=useMemo(()=>key.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),[key]);
 const refresh=async()=>{if(!project.id||!normalizedKey)return setRows([]);try{setRows(await listWebsiteStudioCollectionItems({data:{projectId:project.id,collectionKey:normalizedKey}}));setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load collection.')}};
 useEffect(()=>{void refresh()},[project.id,normalizedKey]);
 const save=async()=>{if(!project.id||!normalizedKey)return;setBusy(true);try{const data=JSON.parse(draft.data||'{}');await saveWebsiteStudioCollectionItem({data:{projectId:project.id,collectionKey:normalizedKey,slug:draft.slug,title:draft.title,data,status:draft.status}});setDraft({slug:'',title:'',data:'{}',status:'draft'});await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save item.')}finally{setBusy(false)}};
 const remove=async(id)=>{setBusy(true);try{await deleteWebsiteStudioCollectionItem({data:{id}});await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not delete item.')}finally{setBusy(false)}};
 return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2 text-indigo-300"><Database className="h-4 w-4"/><span className="text-[10px] font-semibold uppercase tracking-[.16em]">CMS collections</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">Create and manage structured content for this Website Studio project. Collection data is owner-scoped and private until a publishing/runtime adapter deliberately exposes published content.</p>
 <div className="mt-4 flex flex-wrap gap-2">{collections.map(c=><button key={c.name} onClick={()=>setKey(c.name)} className={(key===c.name?'border-indigo-300/25 text-indigo-200':'border-white/10 text-zinc-500')+' rounded-lg border px-2.5 py-1.5 text-xs'}>{c.name}</button>)}<button onClick={()=>{const name=window.prompt('Collection name');if(name)setKey(name)}} className="rounded-lg border border-white/10 px-2.5 py-1.5 text-xs text-zinc-500"><Plus className="inline h-3 w-3"/> Collection</button></div>
 {error&&<p className="mt-3 rounded-lg border border-rose-300/15 p-2 text-xs text-rose-200">{error}</p>}
 {key&&<div className="mt-4 grid gap-3 lg:grid-cols-[320px_1fr]"><div className="space-y-2 rounded-xl border border-white/[.07] bg-black/20 p-3"><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Title" className="w-full rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-xs text-white"/><input value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})} placeholder="slug" className="w-full rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-xs text-white"/><textarea value={draft.data} onChange={e=>setDraft({...draft,data:e.target.value})} rows={8} className="w-full rounded-lg border border-white/10 bg-black/30 p-2 font-mono text-[10px] text-zinc-300"/><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})} className="w-full rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-xs text-white"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><button disabled={busy||!draft.slug} onClick={save} className="flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-xs text-white disabled:opacity-40">{busy?<Loader2 className="h-3 w-3 animate-spin"/>:<Save className="h-3 w-3"/>}Save item</button></div><div className="space-y-2">{rows.length===0?<p className="rounded-xl border border-dashed border-white/10 p-5 text-center text-xs text-zinc-600">No items in {key}.</p>:rows.map(row=><article key={row.id} className="rounded-xl border border-white/[.07] bg-black/20 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-medium text-white">{row.title||row.slug}</p><p className="mt-1 text-[10px] text-zinc-600">{row.slug} · {row.status}</p></div><button onClick={()=>remove(row.id)} className="text-zinc-700 hover:text-rose-300"><Trash2 className="h-3.5 w-3.5"/></button></div><pre className="mt-2 overflow-auto whitespace-pre-wrap text-[10px] text-zinc-500">{JSON.stringify(row.data,null,2)}</pre></article>)}</div></div>}</section>
}
