export type OutcomePackTier = 'acquisition' | 'premium'

export type OutcomePack = {
  id: string
  name: string
  tagline: string
  description: string
  tier: OutcomePackTier
  category: string
  launchRoute: string
  requestTemplate: string
  requiredTools: string[]
  involvesMoney: boolean
  value: string
}

const pack = (value: OutcomePack) => value

export const OUTCOME_PACKS: OutcomePack[] = [
  pack({ id:'website-launch-sprint', name:'Website Launch Sprint', tagline:'Turn an idea into a launch plan.', description:'Create a governed website launch mission covering positioning, structure, copy, build, QA and release.', tier:'acquisition', category:'website', launchRoute:'/website-studio', requestTemplate:'Plan and execute a website launch sprint for my goal. Start by clarifying the audience and offer, then produce the site structure, copy/build tasks, QA checklist and deployment handoff. Do not publish or spend money without approval.', requiredTools:['web','files'], involvesMoney:false, value:'A practical path from idea to launched site.' }),
  pack({ id:'business-health-scan', name:'Business Health Scan', tagline:'Find the biggest operational opportunities.', description:'Review company context, risks, bottlenecks and near-term growth opportunities.', tier:'acquisition', category:'business', launchRoute:'/business-intelligence', requestTemplate:'Run a business health scan using the company context I provide or have connected. Identify operational bottlenecks, revenue opportunities, risks, missing information and the five highest-value next actions. Separate evidence from assumptions.', requiredTools:['web'], involvesMoney:false, value:'A prioritised operating brief.' }),
  pack({ id:'competitor-radar', name:'Competitor Radar', tagline:'Understand the market before acting.', description:'Research competitors, positioning, pricing signals and product differences with sourced evidence.', tier:'acquisition', category:'research', launchRoute:'/web-intelligence', requestTemplate:'Build a competitor radar for my market. Identify relevant competitors, positioning, public pricing, product strengths, gaps and recent signals. Cite sources and distinguish facts from inference.', requiredTools:['web'], involvesMoney:false, value:'Current competitive intelligence.' }),
  pack({ id:'job-application-copilot', name:'Job Application Copilot', tagline:'Prepare a stronger application.', description:'Turn a role brief and user-provided experience into an application plan, CV improvements and interview preparation.', tier:'acquisition', category:'career', launchRoute:'/documents', requestTemplate:'Help me prepare for a job application using only the experience and documents I provide. Produce role-fit gaps, CV improvement tasks, application talking points and an interview preparation checklist. Never invent credentials or experience.', requiredTools:['files','web'], involvesMoney:false, value:'A truthful application workflow.' }),
  pack({ id:'product-launch-kit', name:'Product Launch Kit', tagline:'Coordinate a product launch.', description:'Build launch positioning, asset, channel and measurement tasks around a product.', tier:'acquisition', category:'marketing', launchRoute:'/marketing', requestTemplate:'Create a product launch mission for my product. Produce positioning, audience, launch milestones, content/assets required, channel plan, measurement plan and approval checkpoints. Do not publish or buy ads without approval.', requiredTools:['web'], involvesMoney:false, value:'A launch system instead of a loose checklist.' }),
  pack({ id:'social-content-week', name:'Social Content Week', tagline:'Plan seven days of useful content.', description:'Research themes and create a bounded seven-day social publishing plan.', tier:'acquisition', category:'social', launchRoute:'/social-operations', requestTemplate:'Plan seven days of social content for my objective and audience. Research relevant current themes where useful, then create a channel-aware calendar, asset list, hooks and review checkpoints. Do not publish without approval.', requiredTools:['web'], involvesMoney:false, value:'One week of structured content operations.' }),
  pack({ id:'research-brief', name:'Research Brief', tagline:'Turn a question into sourced intelligence.', description:'Create a research mission with source quality, uncertainties and an executive summary.', tier:'acquisition', category:'research', launchRoute:'/research', requestTemplate:'Research my question deeply. Use current reputable sources where needed, separate verified facts from analysis, show material uncertainty and produce an executive brief plus recommended follow-up questions.', requiredTools:['web'], involvesMoney:false, value:'Decision-ready research with provenance.' }),
  pack({ id:'compliance-navigator', name:'Compliance Navigator', tagline:'Find the rules that may matter.', description:'Build a jurisdiction-aware compliance research checklist without presenting it as legal advice.', tier:'acquisition', category:'compliance', launchRoute:'/compliance-sentinel', requestTemplate:'Create a compliance research checklist for my described activity and jurisdictions. Identify potentially relevant rules, regulators, official sources, evidence to retain and questions for qualified counsel. Do not present this as legal advice.', requiredTools:['web'], involvesMoney:false, value:'A safer route into compliance research.' }),
  pack({ id:'finance-snapshot', name:'Finance Snapshot', tagline:'Organise the numbers that matter.', description:'Create a finance review from user-provided or connected business data.', tier:'acquisition', category:'finance', launchRoute:'/finance', requestTemplate:'Prepare a financial snapshot from the data I provide or have connected. Summarise cashflow, revenue/cost trends, anomalies, upcoming obligations and missing data. Do not move money or make transactions.', requiredTools:['files'], involvesMoney:false, value:'A concise financial operating picture.' }),
  pack({ id:'meeting-to-actions', name:'Meeting → Actions', tagline:'Turn notes into accountable work.', description:'Transform meeting notes into decisions, owners, deadlines and Mission Control tasks.', tier:'acquisition', category:'productivity', launchRoute:'/tasks', requestTemplate:'Turn my meeting notes into a structured action register: decisions, unresolved questions, tasks, suggested owners, dependencies and due-date recommendations. Flag anything ambiguous instead of guessing.', requiredTools:['files'], involvesMoney:false, value:'Less work lost after meetings.' }),
  pack({ id:'store-listing-booster', name:'Store Listing Booster', tagline:'Improve a product listing.', description:'Research and improve product copy, SEO and merchandising without inventing claims.', tier:'acquisition', category:'commerce', launchRoute:'/commerce-studio', requestTemplate:'Review and improve my product listing. Use only verified product facts, identify weak positioning/SEO, propose title/description/bullets/image requirements and a test plan. Never invent product claims.', requiredTools:['web'], involvesMoney:false, value:'Higher-quality commerce content.' }),
  pack({ id:'customer-reply-desk', name:'Customer Reply Desk', tagline:'Triage customer conversations.', description:'Create response drafts and escalation rules from provided customer messages.', tier:'acquisition', category:'support', launchRoute:'/support', requestTemplate:'Triage the customer messages I provide. Categorise urgency and intent, draft appropriate replies, identify cases needing human escalation and list any facts that must be checked before sending. Do not send messages automatically.', requiredTools:[], involvesMoney:false, value:'Faster, safer customer response.' }),
  pack({ id:'seo-quick-wins', name:'SEO Quick Wins', tagline:'Find practical search improvements.', description:'Audit supplied pages and prioritise evidence-based SEO improvements.', tier:'acquisition', category:'seo', launchRoute:'/seo-studio', requestTemplate:'Audit the pages or site I provide for practical SEO improvements. Prioritise technical, content and internal-linking opportunities by impact and effort, and separate observed evidence from assumptions.', requiredTools:['web'], involvesMoney:false, value:'A prioritised SEO improvement list.' }),
  pack({ id:'data-cleanup', name:'Data Cleanup', tagline:'Turn messy data into a usable plan.', description:'Inspect files/tables, surface quality problems and define a safe cleanup workflow.', tier:'acquisition', category:'data', launchRoute:'/smart-tables', requestTemplate:'Review the dataset or table I provide. Identify duplicates, missing values, inconsistent formats, suspicious outliers and schema issues, then produce a reversible cleanup plan before making destructive changes.', requiredTools:['files'], involvesMoney:false, value:'Cleaner data with fewer accidental edits.' }),
  pack({ id:'travel-planner', name:'Travel Planner', tagline:'Build a sourced trip plan.', description:'Research transport, stay and itinerary options while keeping purchases approval-gated.', tier:'acquisition', category:'travel', launchRoute:'/mission-control', requestTemplate:'Plan my trip using current information. Compare transport, accommodation and itinerary options against my constraints, show prices as current estimates with sources, and prepare approval-gated booking actions. Do not purchase anything without approval.', requiredTools:['web'], involvesMoney:true, value:'Travel research plus governed booking prep.' }),
  pack({ id:'home-admin-assistant', name:'Home Admin Assistant', tagline:'Organise life admin into tasks.', description:'Turn household/admin obligations into a clear prioritised task plan.', tier:'acquisition', category:'personal', launchRoute:'/tasks', requestTemplate:'Turn my household and personal admin list into a prioritised plan with deadlines, dependencies, documents needed and reminders I should consider. Do not contact organisations or make payments without approval.', requiredTools:[], involvesMoney:false, value:'A calmer personal-admin backlog.' }),
  pack({ id:'fitness-routine', name:'Fitness Routine Builder', tagline:'Create a practical training structure.', description:'Build a non-diagnostic routine from the user’s goals, equipment and preferences.', tier:'acquisition', category:'health', launchRoute:'/health-fitness', requestTemplate:'Create a practical fitness routine from my goals, schedule, experience and available equipment. Keep it general wellness guidance, identify where professional medical advice may be appropriate, and include progression and recovery considerations.', requiredTools:[], involvesMoney:false, value:'A structured wellness routine.' }),
  pack({ id:'learning-plan', name:'Learning Plan', tagline:'Turn a skill goal into a curriculum.', description:'Create milestones, practice tasks and review checkpoints for a learning goal.', tier:'acquisition', category:'learning', launchRoute:'/knowledge', requestTemplate:'Build a learning plan for the skill I want to develop. Break it into milestones, practice tasks, resources to evaluate, review checkpoints and a realistic sequence. Adapt the plan to the time I say I have available.', requiredTools:['web'], involvesMoney:false, value:'A usable self-directed curriculum.' }),
  pack({ id:'creator-content-pack', name:'Creator Content Pack', tagline:'Shape one idea into multiple assets.', description:'Turn a creator brief into a channel-aware content production plan.', tier:'acquisition', category:'creator', launchRoute:'/creator-hub', requestTemplate:'Turn my creator brief into a multi-format content pack plan: long-form concept, short-form cuts, thumbnail/image needs, hooks, titles and production sequence. Preserve originality and do not imitate living creators.', requiredTools:['web'], involvesMoney:false, value:'One idea expanded into a production system.' }),
  pack({ id:'app-idea-validator', name:'App Idea Validator', tagline:'Pressure-test a software idea.', description:'Research users, alternatives, risks and an MVP experiment before building.', tier:'acquisition', category:'development', launchRoute:'/developer-workspace', requestTemplate:'Validate my app idea before implementation. Research alternatives and target users, identify assumptions and technical/commercial risks, then propose the smallest useful MVP and validation experiments. Cite current market evidence where relevant.', requiredTools:['web'], involvesMoney:false, value:'A sharper build/no-build decision.' }),

  pack({ id:'autonomous-business-operator', name:'Autonomous Business Operator', tagline:'Coordinate recurring business operations.', description:'Create a governed operating mission spanning agents, workflows, approvals and Always-On Intelligence.', tier:'premium', category:'business', launchRoute:'/autonomous-os', requestTemplate:'Design a governed recurring operating system for my business objective using existing Blackstar agents, workflows, approvals and Always-On Intelligence. Define stop conditions, budgets, review cadence and human approvals before external or financial actions.', requiredTools:['web'], involvesMoney:false, value:'An always-on operating loop with controls.' }),
  pack({ id:'executive-command-brief', name:'Executive Daily Command Brief', tagline:'One daily picture of what needs attention.', description:'Aggregate work, risks, approvals, metrics and decisions into an executive operating brief.', tier:'premium', category:'executive', launchRoute:'/mission-control', requestTemplate:'Create an executive command brief from my permitted Blackstar workspace context: work in progress, blockers, approvals, material changes, important metrics, risks and top decisions. Prioritise only what needs attention.', requiredTools:[], involvesMoney:false, value:'A daily control-plane view.' }),
  pack({ id:'always-on-competitor-watch', name:'Always-On Competitor Watch', tagline:'Continuously watch meaningful market changes.', description:'Configure a bounded recurring competitive-intelligence watch with evidence and alert thresholds.', tier:'premium', category:'research', launchRoute:'/autonomous-os', requestTemplate:'Design an always-on competitor watch for the competitors and signals I specify. Define sources, meaningful-change thresholds, evidence requirements, alert cadence, budget limits and stop conditions. Do not notify on noise.', requiredTools:['web'], involvesMoney:false, value:'Continuous competitive awareness without constant manual checking.' }),
  pack({ id:'revenue-operations-team', name:'Revenue Operations Agent Team', tagline:'Coordinate pipeline research and follow-up.', description:'Design a multi-agent revenue workflow around CRM, research, approvals and outreach drafts.', tier:'premium', category:'sales', launchRoute:'/workforce', requestTemplate:'Design a governed revenue-operations agent team using my CRM and company context: account research, pipeline hygiene, follow-up drafting, risk flags and manager review. Do not send outreach or change commercial terms without approval.', requiredTools:['web'], involvesMoney:false, value:'A coordinated revenue operations workforce.' }),
  pack({ id:'multi-channel-marketing-factory', name:'Multi-Channel Marketing Factory', tagline:'Run campaigns as a repeatable pipeline.', description:'Coordinate research, assets, approvals, scheduling and measurement across channels.', tier:'premium', category:'marketing', launchRoute:'/marketing', requestTemplate:'Build a multi-channel campaign production pipeline for my objective. Define research, creative production, channel adaptations, approval gates, scheduling, measurement and iteration. Do not publish or buy media without approval.', requiredTools:['web'], involvesMoney:false, value:'Repeatable governed campaign production.' }),
  pack({ id:'commerce-operations-command', name:'Commerce Operations Command', tagline:'Coordinate catalogue, customers and store operations.', description:'Create an operations mission across commerce, CRM, support and connected store systems.', tier:'premium', category:'commerce', launchRoute:'/commerce-studio', requestTemplate:'Create a commerce operations command mission across catalogue quality, customer issues, stock/price signals, merchandising and connected store workflows. Require approval for price changes, refunds, purchases or other financial actions.', requiredTools:['web'], involvesMoney:true, value:'Unified commerce operations with financial controls.' }),
  pack({ id:'cashflow-watch', name:'Finance & Cashflow Watch', tagline:'Watch financial signals without moving money.', description:'Set a recurring analysis process for cashflow, anomalies and upcoming obligations.', tier:'premium', category:'finance', launchRoute:'/finance', requestTemplate:'Design a recurring finance and cashflow watch using my permitted data. Track material changes, anomalies, upcoming obligations and scenario risks. Never transfer funds, trade or make financial commitments.', requiredTools:['files'], involvesMoney:false, value:'Continuous financial awareness without autonomous money movement.' }),
  pack({ id:'trading-research-room', name:'Global Trading Research Room', tagline:'Coordinate market research and risk planning.', description:'Build a research-only market intelligence workflow with watchlists, scenarios and journaling.', tier:'premium', category:'trading', launchRoute:'/trading-hub', requestTemplate:'Create a market research room for the assets/themes I specify. Track real market data where available, catalysts, scenarios, portfolio context and risk notes. This is research/planning only—do not execute trades or imply guaranteed returns.', requiredTools:['web'], involvesMoney:false, value:'Structured market intelligence with explicit execution boundaries.' }),
  pack({ id:'compliance-sentinel-watch', name:'Compliance Sentinel Watch', tagline:'Monitor regulatory change that may matter.', description:'Configure a bounded watch of official regulatory sources and impact questions.', tier:'premium', category:'compliance', launchRoute:'/compliance-sentinel', requestTemplate:'Design a regulatory-change watch for my jurisdictions and activities using authoritative sources. Define what changes are material, what evidence to retain, impact questions and when qualified legal/compliance review is required.', requiredTools:['web'], involvesMoney:false, value:'Ongoing compliance awareness with source discipline.' }),
  pack({ id:'contract-intelligence-desk', name:'Contract Intelligence Desk', tagline:'Organise contract review and obligations.', description:'Extract obligations, dates, risks and questions from user-provided agreements without replacing counsel.', tier:'premium', category:'legal', launchRoute:'/legal-hub', requestTemplate:'Create a contract intelligence desk for the agreements I provide. Extract parties, obligations, dates, renewal/termination mechanics, unusual clauses, operational actions and questions for qualified counsel. Do not provide legal conclusions beyond the documents.', requiredTools:['files'], involvesMoney:false, value:'Operational contract awareness.' }),
  pack({ id:'support-operations-workforce', name:'Support Operations Workforce', tagline:'Coordinate triage, knowledge and escalation.', description:'Design a governed support workforce with quality and escalation controls.', tier:'premium', category:'support', launchRoute:'/workforce', requestTemplate:'Design a customer-support agent workforce using my approved knowledge and channels. Define triage, draft responses, escalation triggers, quality review, SLA monitoring and prohibited autonomous actions.', requiredTools:[], involvesMoney:false, value:'Scalable support with human escalation.' }),
  pack({ id:'recruitment-pipeline-operator', name:'Recruitment Pipeline Operator', tagline:'Coordinate hiring work without opaque scoring.', description:'Organise sourcing, scheduling and candidate operations while preserving human decisions.', tier:'premium', category:'recruiting', launchRoute:'/workforce', requestTemplate:'Design a recruitment operations workflow for my roles: job requirements, sourcing research, scheduling, candidate communications drafts and interview logistics. Keep hiring decisions with humans and do not infer protected traits.', requiredTools:['web'], involvesMoney:false, value:'Faster hiring operations without automated employment decisions.' }),
  pack({ id:'project-recovery-mission', name:'Project Recovery Mission', tagline:'Recover a slipping project.', description:'Diagnose blockers, dependencies, ownership gaps and a credible recovery sequence.', tier:'premium', category:'projects', launchRoute:'/projects', requestTemplate:'Run a project recovery mission using the project information I provide. Identify blockers, critical path, dependency/ownership gaps, scope risks and a staged recovery plan with checkpoints and escalation criteria.', requiredTools:['files'], involvesMoney:false, value:'A structured route out of project drift.' }),
  pack({ id:'website-growth-operator', name:'Website Growth Operator', tagline:'Continuously improve a live site.', description:'Coordinate SEO, conversion, content and technical improvement cycles.', tier:'premium', category:'website', launchRoute:'/website-studio', requestTemplate:'Design an ongoing website growth workflow: technical health, SEO, conversion friction, content opportunities, experiment backlog, measurement and safe release checkpoints. Do not publish changes without approval.', requiredTools:['web'], involvesMoney:false, value:'A repeatable website improvement engine.' }),
  pack({ id:'content-studio-pipeline', name:'Content Studio Pipeline', tagline:'Move ideas through a full production line.', description:'Coordinate research, scripts, assets, voice, review and publishing handoff.', tier:'premium', category:'creator', launchRoute:'/media-studio', requestTemplate:'Design a content studio pipeline for my brand: research, ideation, scripting, image/video/voice assets, review, repurposing, metadata and publishing handoff. Use approval gates before anything is published.', requiredTools:['web'], involvesMoney:false, value:'A governed creator production line.' }),
  pack({ id:'cinema-production-pipeline', name:'Cinema Production Pipeline', tagline:'Coordinate a long-form AI film project.', description:'Use Cinema planning, continuity, shots, workers and mastering as one governed production mission.', tier:'premium', category:'cinema', launchRoute:'/cinema-studio', requestTemplate:'Create a Cinema production mission from my film brief. Coordinate development, continuity bible, scene/shot compilation, keyframes, motion segments, audio and mastering evidence. Never claim a render exists until a real worker returns output.', requiredTools:[], involvesMoney:false, value:'A long-form production workflow with evidence.' }),
  pack({ id:'game-production-pack', name:'Game Foundry Production Pack', tagline:'Coordinate a game from brief to engine handoff.', description:'Use design, generated assets, game-ready processing and engine packaging in one mission.', tier:'premium', category:'gaming', launchRoute:'/game-foundry', requestTemplate:'Create a Game Foundry production mission from my brief. Coordinate game design, required assets, 3D generation/processing, source/project generation, validation and engine handoff. Do not claim engine integration or playable output without real evidence.', requiredTools:[], involvesMoney:false, value:'A traceable game-production pipeline.' }),
  pack({ id:'3d-asset-production-pack', name:'3D Asset Production Pack', tagline:'Move reference art into game-ready assets.', description:'Coordinate 3D generation, processing, validation and export targets.', tier:'premium', category:'3d', launchRoute:'/three-d-studio', requestTemplate:'Create a 3D asset production mission for my references and target engine. Coordinate generation, topology/UV/material requirements, LOD/collision, validation and export. Fail closed for rigging/animation if no specialist worker is configured.', requiredTools:[], involvesMoney:false, value:'A production-oriented 3D pipeline.' }),
  pack({ id:'developer-release-train', name:'Developer Release Train', tagline:'Coordinate build, test and deployment.', description:'Create a governed software delivery workflow around source control and verification.', tier:'premium', category:'development', launchRoute:'/developer-workspace', requestTemplate:'Create a governed release train for my software project using connected source control and deployment systems. Define implementation tasks, tests, security checks, review gates, deployment verification and rollback evidence. Do not merge or deploy without the configured approval policy.', requiredTools:[], involvesMoney:false, value:'Repeatable software delivery with verification.' }),
  pack({ id:'enterprise-ai-governance', name:'Enterprise AI Governance Pack', tagline:'Control models, agents, tools and evidence.', description:'Build an organisation-wide governance operating model using Blackstar’s existing controls.', tier:'premium', category:'enterprise', launchRoute:'/organisation', requestTemplate:'Design an enterprise AI governance operating model using Blackstar’s existing model routing, agent permissions, approvals, MCP, audit, memory privacy, budget controls and acceptance evidence. Identify gaps without inventing compliance certification.', requiredTools:[], involvesMoney:false, value:'A practical governed-AI operating model.' }),
]

export const ACQUISITION_OUTCOME_PACKS = OUTCOME_PACKS.filter((item) => item.tier === 'acquisition')
export const PREMIUM_OUTCOME_PACKS = OUTCOME_PACKS.filter((item) => item.tier === 'premium')

export function getOutcomePack(id: string) {
  return OUTCOME_PACKS.find((item) => item.id === id) ?? null
}
