// Mock data for the PalladiumAI Admin User Management — illustrative, backend-ready.

export const PLANS = ['Free', 'Pro', 'Team', 'Enterprise'];
export const STATUSES = ['active', 'suspended', 'invited'];
export const ORGS = ['Palladium Studio', 'Acme Corp', 'Globex', 'Initech', 'Umbrella', 'Soylent', 'Hooli'];

export const USERS = [
  { id:'u1', name:'Sarah Chen', email:'sarah@palladium.ai', plan:'Enterprise', status:'active', org:'Palladium Studio', created:'2024-09-12', lastActive:'2m ago', usage: { requests: 18420, agents: 12, projects: 8, storage: 42 }, projects:['Atlas Analytics','Nova Support','Orbit Commerce'], agents:['Atlas Research','Insight Agent'], billing:{ plan:'Enterprise', mrr:'$1,290', method:'Invoice', since:'Sep 2024' }, security:{ mfa:true, sessions:3, lastLogin:'2m ago', risk:'low' }, activity:[{a:'Created agent "Atlas Research"', t:'12m ago'},{a:'Upgraded to Enterprise', t:'3d ago'},{a:'Invited user', t:'1w ago'}] },
  { id:'u2', name:'Maya Patel', email:'maya@acme.com', plan:'Team', status:'active', org:'Acme Corp', created:'2024-11-04', lastActive:'18m ago', usage: { requests: 9210, agents: 6, projects: 5, storage: 18 }, projects:['Acme Dashboard','Acme CRM'], agents:['Support Agent','CodePilot'], billing:{ plan:'Team', mrr:'$99', method:'Visa •••• 4242', since:'Nov 2024' }, security:{ mfa:true, sessions:2, lastLogin:'18m ago', risk:'low' }, activity:[{a:'Connected Gemini 2.5 Pro', t:'1h ago'},{a:'Created project', t:'2d ago'}] },
  { id:'u3', name:'James Lee', email:'james@globex.io', plan:'Pro', status:'suspended', org:'Globex', created:'2025-01-22', lastActive:'3d ago', usage: { requests: 3120, agents: 2, projects: 3, storage: 8 }, projects:['Globex Web'], agents:['Knowledge Agent'], billing:{ plan:'Pro', mrr:'$29', method:'Mastercard •••• 8800', since:'Jan 2025' }, security:{ mfa:false, sessions:0, lastLogin:'3d ago', risk:'medium' }, activity:[{a:'Account suspended', t:'3d ago'},{a:'Failed login attempts x5', t:'3d ago'}] },
  { id:'u4', name:'Lina Garcia', email:'lina@initech.com', plan:'Enterprise', status:'active', org:'Initech', created:'2024-07-18', lastActive:'1h ago', usage: { requests: 24010, agents: 14, projects: 11, storage: 64 }, projects:['Initech Suite','Initech Finance'], agents:['Insight Agent','Atlas Research','Marketing Agent'], billing:{ plan:'Enterprise', mrr:'$2,490', method:'Invoice', since:'Jul 2024' }, security:{ mfa:true, sessions:4, lastLogin:'1h ago', risk:'low' }, activity:[{a:'Deployed workflow v2', t:'40m ago'},{a:'Added team member', t:'5h ago'}] },
  { id:'u5', name:'Tom Wright', email:'tom@umbrella.org', plan:'Free', status:'active', org:'Umbrella', created:'2025-04-02', lastActive:'2d ago', usage: { requests: 420, agents: 1, projects: 1, storage: 2 }, projects:['Personal Site'], agents:['CodePilot'], billing:{ plan:'Free', mrr:'$0', method:'—', since:'Apr 2025' }, security:{ mfa:false, sessions:1, lastLogin:'2d ago', risk:'low' }, activity:[{a:'Created project', t:'2d ago'}] },
  { id:'u6', name:'Aisha Khan', email:'aisha@soylent.co', plan:'Team', status:'invited', org:'Soylent', created:'2025-06-14', lastActive:'—', usage: { requests: 0, agents: 0, projects: 0, storage: 0 }, projects:[], agents:[], billing:{ plan:'Team', mrr:'$99', method:'Pending', since:'Jun 2025' }, security:{ mfa:false, sessions:0, lastLogin:'—', risk:'low' }, activity:[{a:'Invitation sent', t:'3w ago'}] },
  { id:'u7', name:'Ben Carter', email:'ben@hooli.com', plan:'Pro', status:'active', org:'Hooli', created:'2025-02-28', lastActive:'5m ago', usage: { requests: 6840, agents: 4, projects: 6, storage: 22 }, projects:['Hooli App','Hooli Marketing'], agents:['Marketing Agent','Support Agent'], billing:{ plan:'Pro', mrr:'$29', method:'Visa •••• 1190', since:'Feb 2025' }, security:{ mfa:true, sessions:2, lastLogin:'5m ago', risk:'low' }, activity:[{a:'Ran campaign report', t:'10m ago'},{a:'Updated billing', t:'1w ago'}] },
  { id:'u8', name:'Nora Fields', email:'nora@palladium.ai', plan:'Enterprise', status:'suspended', org:'Palladium Studio', created:'2024-05-30', lastActive:'2w ago', usage: { requests: 31200, agents: 18, projects: 14, storage: 88 }, projects:['Palladium Admin','Palladium API'], agents:['Atlas Research','Insight Agent','CodePilot'], billing:{ plan:'Enterprise', mrr:'$1,290', method:'Invoice', since:'May 2024' }, security:{ mfa:true, sessions:0, lastLogin:'2w ago', risk:'high' }, activity:[{a:'Account suspended (policy)', t:'2w ago'}] },
];