import { useEffect, useState } from 'react';
import { CheckCircle2, Gift, History, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react';
import { listRetailWorkspaces } from '@/lib/retail/retail-operations.functions';
import {
  getRetailExecutionState, completeRetailStocktake, issueRetailGiftCard, adjustRetailGiftCard,
} from '@/lib/retail/retail-execution.functions';

const blankIssue = { code: '', value: 0, customer_name: '', customer_email: '', expires_at: '', note: '' };
const blankAdjust = { gift_card_id: '', amount: 0, event_type: 'redeem', reference: '', note: '' };
function toIso(v) { return v ? new Date(v).toISOString() : null; }
function cash(v, c='GBP') { try { return new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(Number(v||0)); } catch { return `${c} ${Number(v||0).toFixed(2)}`; } }
function date(v) { return v ? new Date(v).toLocaleString() : '—'; }

export default function RetailExecutionControls() {
  const [workspaces,setWorkspaces]=useState([]); const [selected,setSelected]=useState(''); const [data,setData]=useState(null);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [issue,setIssue]=useState(blankIssue); const [adjust,setAdjust]=useState(blankAdjust);
  const workspace=workspaces.find((x)=>x.id===selected);
  const loadWorkspaces=async()=>{const rows=await listRetailWorkspaces({data:{}});setWorkspaces(rows);setSelected((c)=>c&&rows.some((x)=>x.id===c)?c:(rows[0]?.id||''));};
  const load=async(id=selected)=>{if(!id){setData(null);return;}setData(await getRetailExecutionState({data:{workspace_id:id}}));};
  const refresh=async()=>{setBusy(true);setError('');try{await loadWorkspaces();if(selected)await load(selected);}catch(e){setError(e instanceof Error?e.message:'Could not load execution state.');}finally{setBusy(false);}};
  useEffect(()=>{loadWorkspaces().catch((e)=>setError(e instanceof Error?e.message:'Could not load Retail workspaces.'));},[]);
  useEffect(()=>{if(selected)load(selected).catch((e)=>setError(e instanceof Error?e.message:'Could not load Retail execution state.'));},[selected]);
  if(!workspaces.length)return null;

  const finishStocktake=async(id)=>run(async()=>{await completeRetailStocktake({data:{stocktake_id:id}});await load();});
  const issueCard=async()=>run(async()=>{await issueRetailGiftCard({data:{workspace_id:selected,code:issue.code,value:Number(issue.value),currency:workspace?.currency||'GBP',customer_name:issue.customer_name,customer_email:issue.customer_email,expires_at:toIso(issue.expires_at),note:issue.note}});setIssue(blankIssue);await load();});
  const postCard=async()=>run(async()=>{await adjustRetailGiftCard({data:{gift_card_id:adjust.gift_card_id,amount:Number(adjust.amount),event_type:adjust.event_type,order_id:null,return_id:null,reference:adjust.reference,note:adjust.note}});setAdjust(blankAdjust);await load();});
  async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Retail execution failed.');}finally{setBusy(false);}}

  return <section className="rounded-[28px] border border-white/[.08] bg-black/30 p-4 lg:p-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.17em] text-emerald-300"><ShieldCheck className="h-4 w-4"/> Governed Retail execution</div><h2 className="mt-1 text-2xl font-semibold text-white">Post real operational changes through audited ledgers</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Stocktake variances are posted atomically to inventory history; gift/store-credit balances are backed by immutable issue, redemption, refund and adjustment events.</p></div><div className="flex gap-2"><select value={selected} onChange={(e)=>setSelected(e.target.value)} className="rounded-xl border border-white/[.08] bg-black/50 px-3 py-2 text-sm text-white">{workspaces.map((w)=><option key={w.id} value={w.id}>{w.business_name}</option>)}</select><button onClick={refresh} disabled={busy} className="rounded-xl border border-white/[.08] bg-white/[.035] p-2 text-zinc-300"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/></button></div></div>
    {error&&<div className="mt-4 rounded-xl border border-rose-300/15 bg-rose-300/[.045] px-4 py-3 text-xs text-rose-200">{error}</div>}
    {data&&<div className="mt-5 grid gap-4 xl:grid-cols-2">
      <div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300"/><h3 className="text-sm font-medium text-white">Complete stocktakes</h3></div><p className="mt-2 text-xs leading-5 text-zinc-500">Completion refuses uncounted lines and records every non-zero variance as an inventory adjustment tied to the stocktake ID.</p><div className="mt-4 space-y-2">{data.stocktakes.filter((x)=>!['completed','cancelled'].includes(x.status)).map((x)=>{const lines=data.stocktakeLines.filter((l)=>l.stocktake_id===x.id);const uncounted=lines.filter((l)=>l.counted_quantity==null).length;return <div key={x.id} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-white">{x.name}</p><p className="mt-1 text-[11px] text-zinc-500">{lines.length} lines · {uncounted} uncounted · {x.status}</p></div><button onClick={()=>finishStocktake(x.id)} disabled={busy||!lines.length||uncounted>0} className="rounded-lg bg-emerald-400/10 px-2.5 py-1.5 text-[11px] text-emerald-200 disabled:opacity-35">Complete & post</button></div></div>})}{!data.stocktakes.some((x)=>!['completed','cancelled'].includes(x.status))&&<p className="rounded-xl border border-dashed border-white/10 p-4 text-xs text-zinc-600">No open stocktakes.</p>}</div></div>
      <div className="space-y-4"><div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-center gap-2"><Gift className="h-4 w-4 text-violet-300"/><h3 className="text-sm font-medium text-white">Issue gift/store credit</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Code" value={issue.code} set={(v)=>setIssue({...issue,code:v})}/><Field label="Value" type="number" value={issue.value} set={(v)=>setIssue({...issue,value:v})}/><Field label="Customer" value={issue.customer_name} set={(v)=>setIssue({...issue,customer_name:v})}/><Field label="Email" value={issue.customer_email} set={(v)=>setIssue({...issue,customer_email:v})}/><Field label="Expires" type="datetime-local" value={issue.expires_at} set={(v)=>setIssue({...issue,expires_at:v})}/><Field label="Note" value={issue.note} set={(v)=>setIssue({...issue,note:v})}/></div><button onClick={issueCard} disabled={busy||!issue.code.trim()||Number(issue.value)<=0} className="mt-4 rounded-xl bg-violet-400/10 px-3 py-2 text-xs text-violet-100 disabled:opacity-35">Issue with ledger event</button></div>
      <div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-cyan-300"/><h3 className="text-sm font-medium text-white">Post gift-credit transaction</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Select label="Card" value={adjust.gift_card_id} set={(v)=>setAdjust({...adjust,gift_card_id:v})} options={data.giftCards.map((x)=>[x.id,`${x.code} · ${cash(x.balance,x.currency)}`])}/><Select label="Event" value={adjust.event_type} set={(v)=>setAdjust({...adjust,event_type:v})} options={['redeem','refund','adjust','void','expire']}/><Field label="Amount" type="number" value={adjust.amount} set={(v)=>setAdjust({...adjust,amount:v})}/><Field label="Reference" value={adjust.reference} set={(v)=>setAdjust({...adjust,reference:v})}/><Field label="Note" value={adjust.note} set={(v)=>setAdjust({...adjust,note:v})}/></div><button onClick={postCard} disabled={busy||!adjust.gift_card_id||Number(adjust.amount)===0} className="mt-4 rounded-xl bg-cyan-400/10 px-3 py-2 text-xs text-cyan-100 disabled:opacity-35">Post transaction</button></div></div>
      <div className="xl:col-span-2 rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-center gap-2"><History className="h-4 w-4 text-zinc-300"/><h3 className="text-sm font-medium text-white">Recent gift-credit ledger</h3></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{data.giftCardEvents.slice(0,30).map((e)=>{const card=data.giftCards.find((x)=>x.id===e.gift_card_id);return <div key={e.id} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><p className="text-sm text-white">{card?.code||'Gift credit'} · {e.event_type}</p><p className="mt-1 text-[11px] text-zinc-500">{cash(e.amount,card?.currency||workspace?.currency||'GBP')} · balance {cash(e.balance_after,card?.currency||workspace?.currency||'GBP')} · {date(e.occurred_at)}</p></div>})}</div></div>
    </div>}
  </section>;
}

function Field({label,value,set,type='text'}){return <label className="text-xs text-zinc-500"><span>{label}</span><input type={type} value={value??''} onChange={(e)=>set(e.target.value)} className="mt-1.5 w-full rounded-xl border border-white/[.08] bg-black/40 px-3 py-2 text-sm text-white outline-none"/></label>}
function Select({label,value,set,options}){return <label className="text-xs text-zinc-500"><span>{label}</span><select value={value??''} onChange={(e)=>set(e.target.value)} className="mt-1.5 w-full rounded-xl border border-white/[.08] bg-black/50 px-3 py-2 text-sm text-white outline-none"><option value="">Select…</option>{options.map((o)=>Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o} value={o}>{o}</option>)}</select></label>}
