import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Activity, ArrowRight, Bot, CheckCircle2, CirclePause, GitBranch, LayoutGrid, List, Loader2, Plus, RefreshCw, Search, Sparkles, Workflow } from 'lucide-react';
import PageHeader from '@/components/palladium/PageHeader';
import AgentCard from '@/components/agents/AgentCard';
import { CATEGORIES, AVATAR_COLORS } from '@/components/agents/agentsData';
import AnimatedBrain from '@/components/visual/AnimatedBrain';
import { useUpgrade } from '@/lib/upgradeContext';
import { listAgents, setAgentStatus, duplicateAgent, deleteAgent } from '@/lib/agents/agents.functions';
const STATUS_MAP={active:'Running',paused:'Paused',draft:'Idle',archived:'Stopped'};
const TOOL_NAMES={web_search:'Web Search',files:'File Analysis',email:'Email',calendar:'Calendar',terminal:'Terminal',vision:'Vision',image:'Image Generation',browser:'Browser',api:'API Calls',workflow:'Workflow Builder'};
const LIVE_STATUSES=new Set(['running','queued','waiting_for_approval','awaiting_approval']);
function hashGrad(str){const i=(str||'').split('').reduce((a,c)=>a+c.charCodeAt(0),0)%AVATAR_COLORS.length;return AVATAR_COLORS[i];}
function relTime(iso){if(!iso)return '—';const s=Math.round((Date.now()-new Date(iso).getTime())/1000);if(s<0||s<=5)return'now';if(s<60)return`${s}s ago`;const m=Math.round(s/60);if(m<60)return`${m}m ago`;const h=Math.round(m/60);if(h<24)return`${h}h ago`;return`${Math.round(h/24)}d ago`;}
function mapAgent(r){const cfg=r.preferences||{};const tools=Array.isArray(r.allowed_tools)?r.allowed_tools:[];return{id:r.id,name:r.name||'Untitled Agent',letter:(r.name||'A').trim().charAt(0).toUpperCase(),grad:cfg.grad||hashGrad(r.id||r.name||''),desc:r.description||'No description set.',status:STATUS_MAP[r.status]||'Idle',model:r.model||'gpt-5-mini',modelGrad:'from-violet-500 to-indigo-500',caps:tools.map((t)=>TOOL_NAMES[t]||t),memory:cfg.memory!==false,lastRun:relTime(r.last_run_at||r.updated_at||r.created_at),category:cfg.category||r.category||'Operations',featured:!!cfg.featured,recent:!!cfg.recent,score:typeof cfg.score==='number'?cfg.score:0,dept:r.category||'Operations',task:cfg.task||'',_raw:r};}
function statusTone(status){if(status==='running'||status==='queued')return'border-violet-300/25 bg-violet-400/[.09] text-violet-100';if(status==='waiting_for_approval'||status==='awaiting_approval')return'border-amber-400/25 bg-amber-500/10 text-amber-200';if(status==='failed')return'border-rose-400/25 bg-rose-500/10 text-rose-200';if(status==='succeeded'||status==='completed')return'border-emerald-400/25 bg-emerald-500/10 text-emerald-200';return'border-white/10 bg-white/5 text-zinc-400';}
function StatusBadge({status}){return <span className={`rounded-full border px-2 py-1 text-[10px] font-medium ${statusTone(status)}`}>{String(status||'unknown').replace(/_/g,' ')}</span>;}
export default function Agents(){
 const navigate=useNavigate();const[params,setParams]=useSearchParams();const{gate}=useUpgrade();const[agents,setAgents]=useState([]);const[tasks,setTasks]=useState([]);const[workflows,setWorkflows]=useState([]);const[workflowRuns,setWorkflowRuns]=useState([]);const[workflowStepRuns,setWorkflowStepRuns]=useState([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[view,setView]=useState('grid');const[q,setQ]=useState('');const[cat,setCat]=useState('All');const focusActive=params.get('view')==='active';
 const load=useCallback(async(quiet=false)=>{if(quiet)setRefreshing(true);else setLoading(true);try{const data=await listAgents({data:{limit:100,withTasks:true}});setAgents((data?.agents||[]).map(mapAgent));setTasks(data?.tasks||[]);setWorkflows(data?.workflows||[]);setWorkflowRuns(data?.workflowRuns||[]);setWorkflowStepRuns(data?.workflowStepRuns||[]);}catch(e){console.error('[agents] could not load live operations',e);}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{load(false);const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer);},[load]);
 const workflowById=useMemo(()=>new Map(workflows.map((w)=>[w.id,w])),[workflows]);const runById=useMemo(()=>new Map(workflowRuns.map((r)=>[r.id,r])),[workflowRuns]);
 const taskRunsByAgent=useMemo(()=>{const map=new Map();for(const task of tasks){if(!task.agent_id)continue;const rows=map.get(task.agent_id)||[];rows.push(task);map.set(task.agent_id,rows);}return map;},[tasks]);
 const workflowStepsByAgent=useMemo(()=>{const map=new Map();for(const step of workflowStepRuns){if(!step.agent_id)continue;const rows=map.get(step.agent_id)||[];rows.push(step);map.set(step.agent_id,rows);}return map;},[workflowStepRuns]);
 const actuallyRunningIds=useMemo(()=>{const ids=new Set();for(const task of tasks)if(task.agent_id&&LIVE_STATUSES.has(task.status))ids.add(task.agent_id);for(const step of workflowStepRuns)if(step.agent_id&&LIVE_STATUSES.has(step.status))ids.add(step.agent_id);return ids;},[tasks,workflowStepRuns]);
 const configuredActive=agents.filter((a)=>a.status==='Running');const executing=agents.filter((a)=>actuallyRunningIds.has(a.id));const mine=agents.filter((a)=>(cat==='All'||a.category===cat)&&a.name.toLowerCase().includes(q.toLowerCase()));const shown=focusActive?mine.filter((a)=>a.status==='Running'||actuallyRunningIds.has(a.id)):mine;const runningWorkflowRuns=workflowRuns.filter((r)=>LIVE_STATUSES.has(r.status));
 const remove=async(a)=>{try{await deleteAgent({data:{id:a.id}});}catch{}await load(true);};const run=async(a)=>{try{await setAgentStatus({data:{id:a.id,status:'active'}});}catch{}await load(true);};const duplicate=async(a)=>{try{await duplicateAgent({data:{id:a.id}});}catch{}await load(true);};
 return <><div aria-hidden className="pointer-events-none fixed inset-0 -z-10 opacity-30"><AnimatedBrain agentStates={agents.map((a)=>a.status)} /></div>
 <PageHeader eyebrow="Blackstar Agent Network" title="Agent Command" description="Deploy, observe and coordinate executable intelligence across live tasks, runtime state and workflow handoffs." action={<div className="flex items-center gap-2"><button onClick={()=>load(true)} disabled={refreshing} className="rounded-xl border border-violet-300/10 bg-violet-400/[.03] p-2 text-zinc-300 hover:bg-violet-400/[.07] disabled:opacity-50" title="Refresh live operations"><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`} /></button><button onClick={()=>{if(gate('createAgents'))navigate('/agents/new');}} className="flex items-center gap-2 rounded-xl border border-violet-200/20 bg-violet-300 px-4 py-2 text-sm font-semibold text-[#09070d] shadow-[0_0_28px_rgba(167,139,250,.12)] hover:bg-violet-200"><Plus className="h-4 w-4" />Deploy agent</button></div>} />
 <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Bot} label="Agent nodes" value={agents.length} /><Metric icon={Activity} label="Executing now" value={executing.length} live /><Metric icon={CheckCircle2} label="Enabled nodes" value={configuredActive.length} tone="green" /><Metric icon={Workflow} label="Live workflows" value={runningWorkflowRuns.length} tone="amber" /></div>
 {focusActive&&<div className="mb-5 flex items-center justify-between rounded-2xl border border-violet-300/20 bg-violet-400/[.055] px-4 py-3"><div><p className="text-xs font-semibold text-violet-100">Mission Control focus · Active agents</p><p className="mt-0.5 text-[11px] text-violet-200/60">Showing nodes that are enabled or currently carrying live execution.</p></div><button onClick={()=>{params.delete('view');setParams(params);}} className="text-xs text-violet-200 hover:text-white">Show all</button></div>}
 <section className="relative mb-8 overflow-hidden rounded-[24px] border border-violet-300/15 bg-[linear-gradient(145deg,rgba(13,10,20,.92),rgba(5,5,9,.96))] p-4 shadow-[0_22px_70px_rgba(0,0,0,.25)] backdrop-blur-xl"><div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-violet-200/25 to-transparent" /><div className="mb-4 flex flex-wrap items-center gap-3"><div><h2 className="flex items-center gap-2 text-sm font-semibold text-white"><Activity className="h-4 w-4 text-violet-300" />Live execution network</h2><p className="mt-1 text-[11px] text-zinc-500">Authoritative runtime activity from agent tasks and workflow step runs.</p></div><span className="ml-auto flex items-center gap-1.5 text-[10px] text-violet-300"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-violet-300 shadow-[0_0_12px_rgba(196,181,253,.7)]" />TELEMETRY · 15S</span></div>
 {loading?<div className="flex items-center justify-center gap-2 py-10 text-sm text-zinc-500"><Loader2 className="h-4 w-4 animate-spin" />Synchronising agent telemetry…</div>:executing.length===0&&runningWorkflowRuns.length===0?<div className="rounded-xl border border-dashed border-violet-300/10 bg-black/20 p-6 text-center"><CirclePause className="mx-auto h-6 w-6 text-zinc-600" /><p className="mt-2 text-sm font-medium text-zinc-300">Execution network idle</p><p className="mt-1 text-xs text-zinc-600">Enabled agents remain ready. The next real execution will appear automatically.</p></div>:<div className="space-y-3">{executing.map((agent)=><AgentOperation key={agent.id} agent={agent} tasks={taskRunsByAgent.get(agent.id)||[]} steps={workflowStepsByAgent.get(agent.id)||[]} workflowById={workflowById} runById={runById} />)}{runningWorkflowRuns.filter((r)=>!workflowStepRuns.some((s)=>s.run_id===r.id&&s.agent_id)).map((r)=><div key={r.id} className="rounded-xl border border-amber-400/15 bg-amber-500/[.04] p-3"><div className="flex items-center gap-2"><Workflow className="h-4 w-4 text-amber-300" /><p className="text-xs font-semibold text-white">{workflowById.get(r.workflow_id)?.name||'Workflow run'}</p><StatusBadge status={r.status} /></div><p className="mt-2 line-clamp-2 text-[11px] text-zinc-500">{r.input||'Workflow is running a built-in or unassigned step.'}</p></div>)}</div>}</section>
 <div className="mb-4 flex flex-wrap items-center gap-2"><div className="flex items-center gap-2 rounded-xl border border-violet-300/10 bg-black/30 px-3 py-2"><Search className="h-4 w-4 text-zinc-600" /><input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Search agent network" className="w-44 bg-transparent text-sm text-zinc-100 outline-none placeholder:text-zinc-600" /></div><div className="flex max-w-full gap-1 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{CATEGORIES.map((c)=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full border px-3 py-1.5 text-xs ${cat===c?'border-violet-200/20 bg-violet-300 text-[#09070d]':'border-violet-300/[.08] text-zinc-500 hover:bg-violet-400/[.04] hover:text-zinc-300'}`}>{c}</button>)}</div><div className="ml-auto flex items-center gap-1 rounded-xl border border-violet-300/10 bg-black/30 p-1"><button onClick={()=>setView('grid')} className={`rounded-lg p-1.5 ${view==='grid'?'bg-violet-400/[.09] text-violet-200':'text-zinc-600'}`}><LayoutGrid className="h-4 w-4" /></button><button onClick={()=>setView('list')} className={`rounded-lg p-1.5 ${view==='list'?'bg-violet-400/[.09] text-violet-200':'text-zinc-600'}`}><List className="h-4 w-4" /></button></div></div>
 <section className="mb-8"><div className="mb-3 flex items-center gap-2"><Sparkles className="h-4 w-4 text-violet-300" /><h2 className="text-sm font-semibold text-white">{focusActive?'Active intelligence nodes':'Agent network'}</h2><span className="rounded-full border border-violet-300/10 bg-violet-400/[.03] px-2 py-0.5 text-[10px] text-zinc-500">{shown.length}</span></div>{loading?<div className="flex items-center gap-2 rounded-2xl border border-violet-300/10 bg-black/25 p-8 text-sm text-zinc-400"><Loader2 className="h-4 w-4 animate-spin" />Loading agent network…</div>:shown.length===0?<div className="rounded-2xl border border-dashed border-violet-300/10 bg-black/20 p-10 text-center"><Bot className="mx-auto h-8 w-8 text-zinc-700" /><h3 className="mt-3 text-base font-semibold text-white">No matching agents</h3><p className="mt-1 text-sm text-zinc-500">Deploy an agent or clear the filters.</p></div>:view==='grid'?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{shown.map((a)=><div key={a.id} className="relative"><AgentCard agent={a} onEdit={()=>navigate(`/agents/${a.id}`)} onDuplicate={duplicate} onDelete={remove} onRun={run} />{actuallyRunningIds.has(a.id)&&<span className="absolute right-3 top-3 flex items-center gap-1 rounded-full border border-violet-300/25 bg-[#0b0812]/95 px-2 py-1 text-[9px] font-semibold text-violet-200"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-violet-300" />EXECUTING</span>}</div>)}</div>:<div className="overflow-x-auto rounded-2xl border border-violet-300/10 bg-black/25"><table className="w-full min-w-[780px] text-sm"><thead className="border-b border-violet-300/[.08] text-left text-xs text-zinc-500"><tr>{['Agent','Lifecycle','Runtime','Current task','Workflow','Last run',''].map((h)=><th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{shown.map((a)=>{const currentTask=(taskRunsByAgent.get(a.id)||[]).find((t)=>LIVE_STATUSES.has(t.status));const currentStep=(workflowStepsByAgent.get(a.id)||[]).find((s)=>LIVE_STATUSES.has(s.status));const wfRun=currentStep?runById.get(currentStep.run_id):null;const wf=wfRun?workflowById.get(wfRun.workflow_id):null;return <tr key={a.id} className="border-b border-violet-300/[.05] hover:bg-violet-400/[.025]"><td className="px-4 py-3 font-medium text-white">{a.name}</td><td className="px-4 py-3 text-zinc-400">{a.status}</td><td className="px-4 py-3">{actuallyRunningIds.has(a.id)?<StatusBadge status="running" />:<span className="text-zinc-600">Ready</span>}</td><td className="max-w-[240px] truncate px-4 py-3 text-zinc-400">{currentTask?.title||currentStep?.name||'—'}</td><td className="px-4 py-3 text-zinc-500">{wf?.name||'—'}</td><td className="px-4 py-3 text-zinc-500">{a.lastRun}</td><td className="px-4 py-3 text-right"><Link to={`/agents/${a.id}`} className="inline-flex text-violet-300"><ArrowRight className="h-4 w-4" /></Link></td></tr>;})}</tbody></table></div>}</section></>;
}
function Metric({icon:Icon,label,value,tone,live}){const cls=tone==='green'?'text-emerald-300':tone==='amber'?'text-amber-300':'text-violet-300';return <div className="relative overflow-hidden rounded-2xl border border-violet-300/10 bg-black/35 p-4 backdrop-blur-xl"><div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-violet-200/20 to-transparent" /><div className={`flex items-center justify-between ${cls}`}><Icon className="h-4 w-4" />{live&&<span className="flex items-center gap-1 text-[9px]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-current" />LIVE</span>}</div><p className="mt-3 text-2xl font-semibold text-white">{value}</p><p className="text-[10px] uppercase tracking-[.14em] text-zinc-500">{label}</p></div>;}
function AgentOperation({agent,tasks,steps,workflowById,runById}){const activeTasks=tasks.filter((t)=>LIVE_STATUSES.has(t.status));const activeSteps=steps.filter((s)=>LIVE_STATUSES.has(s.status));const recentTask=activeTasks[0]||tasks[0];const recentStep=activeSteps[0]||steps[0];const run=recentStep?runById.get(recentStep.run_id):null;const workflow=run?workflowById.get(run.workflow_id):null;const title=recentTask?.title||recentStep?.name||'Agent is active';const status=recentTask?.status||recentStep?.status||'running';return <div className="rounded-xl border border-violet-300/15 bg-black/25 p-4"><div className="flex flex-wrap items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br ${agent.grad} text-sm font-semibold text-white`}>{agent.letter}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Link to={`/agents/${agent.id}`} className="text-sm font-semibold text-white hover:text-violet-200">{agent.name}</Link><StatusBadge status={status} /></div><p className="mt-1 truncate text-xs text-zinc-400">{title}</p><p className="mt-1 text-[10px] text-zinc-600">{recentTask?.provider?`${recentTask.provider} · ${recentTask.model||agent.model}`:agent.model} · started {relTime(recentTask?.started_at||recentStep?.started_at||recentTask?.created_at||recentStep?.created_at)}</p></div><Link to={`/agents/${agent.id}`} className="rounded-lg border border-violet-300/10 p-2 text-zinc-400 hover:bg-violet-400/[.04] hover:text-white"><ArrowRight className="h-4 w-4" /></Link></div>{workflow&&<div className="mt-3 rounded-lg border border-violet-300/15 bg-violet-400/[.045] p-3"><div className="flex flex-wrap items-center gap-2"><GitBranch className="h-3.5 w-3.5 text-violet-300" /><span className="text-[11px] font-semibold text-violet-100">{workflow.name}</span><StatusBadge status={run?.status} /></div><div className="mt-2 flex items-center gap-2 text-[10px] text-zinc-500"><Workflow className="h-3 w-3" /><span>Step {Number(recentStep.position??0)+1}: {recentStep.name||recentStep.kind||'Agent step'}</span><span>· attempt {recentStep.attempt||1}</span></div></div>}{!workflow&&recentTask?.input&&<p className="mt-3 line-clamp-2 rounded-lg border border-violet-300/[.06] bg-white/[.02] p-3 text-[11px] leading-5 text-zinc-500">{recentTask.input}</p>}</div>;}
