import { useEffect,useMemo,useState } from 'react';
import { ShieldAlert,Truck,Boxes,Workflow,Coins,Plus,RefreshCw } from 'lucide-react';
import { getConstructionControl,saveConstructionFieldRecord,saveConstructionPartner,saveConstructionMaterial,saveConstructionWorkPackage,saveConstructionChange } from '@/lib/construction/construction-control.functions';

export default function ConstructionControlCentre({workspaceId,projects=[]}){
 const[data,setData]=useState(null),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 const[field,setField]=useState({record_type:'rams',title:'',status:'open',risk_level:'medium',description:'',responsible_person:''});
 const[partner,setPartner]=useState({partner_type:'subcontractor',name:'',contact_name:'',trade:'',status:'active',notes:''});
 const[material,setMaterial]=useState({name:'',unit:'each',required_qty:0,ordered_qty:0,delivered_qty:0,used_qty:0,unit_cost:0,status:'required',notes:''});
 const[work,setWork]=useState({project_id:'',name:'',trade:'',status:'planned',percent_complete:0,budget:0,committed_cost:0,actual_cost:0,notes:''});
 const[change,setChange]=useState({project_id:'',title:'',change_type:'variation',status:'draft',cost_impact:0,time_impact_days:0,description:''});
 async function load(){if(workspaceId)setData(await getConstructionControl({data:{workspace_id:workspaceId}}));}
 useEffect(()=>{load().catch(e=>setErr(e.message));},[workspaceId]);
 useEffect(()=>{if(projects[0]){setWork(x=>x.project_id?x:{...x,project_id:projects[0].id});setChange(x=>x.project_id?x:{...x,project_id:projects[0].id});}},[projects]);
 async function act(fn){setBusy(true);setErr('');try{await fn();await load();}catch(e){setErr(e.message||'Operation failed');}finally{setBusy(false);}}
 const queue=useMemo(()=>data?[...data.signals.highRisk.map(x=>['High-risk field record',x.title]),...data.signals.supplyShortages.map(x=>['Supply risk',x.name]),...data.signals.blockedPackages.map(x=>['Blocked work package',x.name]),...data.signals.pendingChanges.map(x=>['Commercial decision',x.title])].slice(0,20):[],[data]);
 if(!workspaceId||!data)return null;
 return <section className="rounded-[28px] border border-cyan-300/10 bg-black/30 p-5 lg:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-200">Field + commercial control</p><h2 className="mt-1 text-xl font-semibold text-white">Delivery control centre</h2><p className="mt-2 text-sm text-zinc-500">RAMS, permits, incidents, NCRs, RFIs, partners, materials, work packages and change control in one operating picture.</p></div><button onClick={()=>load()} className="rounded-xl border border-white/[.08] p-2 text-zinc-400"><RefreshCw className="h-4 w-4"/></button></div>
 {err&&<div className="mt-3 rounded-xl border border-rose-300/15 p-3 text-xs text-rose-200">{err}</div>}
 <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['High risk',data.signals.highRisk.length,ShieldAlert],['Open permits',data.signals.openPermits.length,Workflow],['Supply risks',data.signals.supplyShortages.length,Boxes],['Blocked packages',data.signals.blockedPackages.length,Truck],['Change exposure',new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(data.signals.commercialExposure),Coins]].map(([l,v,I])=><Metric key={l} l={l} v={v} I={I}/>)}</div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="AI exception queue">{queue.length?queue.map(([a,b],i)=><div key={i} className="mb-2 rounded-xl border border-white/[.06] p-3"><p className="text-xs font-semibold uppercase tracking-[.12em] text-amber-200">{a}</p><p className="mt-1 text-sm text-white">{b}</p></div>):<p className="text-xs text-zinc-600">No high-priority delivery exceptions.</p>}</Panel><Panel title="Current control records"><p className="text-xs leading-6 text-zinc-500">{data.fieldRecords.length} field records · {data.partners.length} partners · {data.materials.length} materials · {data.workPackages.length} work packages · {data.changes.length} changes</p></Panel></div>
 <div className="mt-4 grid gap-4 xl:grid-cols-5"><Panel title="Field record"><Select v={field.record_type} set={v=>setField({...field,record_type:v})} opts={['rams','permit','incident','near_miss','ncr','snag','rfi','toolbox_talk','daily_diary','handover']}/><Input p="Title" v={field.title} set={v=>setField({...field,title:v})}/><Select v={field.risk_level} set={v=>setField({...field,risk_level:v})} opts={['low','medium','high','critical']}/><Button disabled={!field.title||busy} onClick={()=>act(()=>saveConstructionFieldRecord({data:{...field,workspace_id:workspaceId,project_id:null}}))}>Log</Button></Panel>
 <Panel title="Partner"><Select v={partner.partner_type} set={v=>setPartner({...partner,partner_type:v})} opts={['subcontractor','supplier','consultant','client','manufacturer','hire_company','other']}/><Input p="Name" v={partner.name} set={v=>setPartner({...partner,name:v})}/><Input p="Trade / discipline" v={partner.trade} set={v=>setPartner({...partner,trade:v})}/><Button disabled={!partner.name||busy} onClick={()=>act(()=>saveConstructionPartner({data:{...partner,workspace_id:workspaceId}}))}>Add</Button></Panel>
 <Panel title="Material"><Input p="Material" v={material.name} set={v=>setMaterial({...material,name:v})}/><Input p="Required quantity" type="number" v={material.required_qty} set={v=>setMaterial({...material,required_qty:Number(v)})}/><Select v={material.status} set={v=>setMaterial({...material,status:v})} opts={['required','quoted','ordered','part_delivered','delivered','shortage','cancelled']}/><Button disabled={!material.name||busy} onClick={()=>act(()=>saveConstructionMaterial({data:{...material,workspace_id:workspaceId,project_id:null,supplier_id:null}}))}>Track</Button></Panel>
 <Panel title="Work package"><ProjectSelect projects={projects} v={work.project_id} set={v=>setWork({...work,project_id:v})}/><Input p="Package" v={work.name} set={v=>setWork({...work,name:v})}/><Select v={work.status} set={v=>setWork({...work,status:v})} opts={['planned','ready','in_progress','blocked','complete','cancelled']}/><Button disabled={!work.name||!work.project_id||busy} onClick={()=>act(()=>saveConstructionWorkPackage({data:{...work,workspace_id:workspaceId,partner_id:null}}))}>Save</Button></Panel>
 <Panel title="Variation / change"><ProjectSelect projects={projects} v={change.project_id} set={v=>setChange({...change,project_id:v})}/><Input p="Change" v={change.title} set={v=>setChange({...change,title:v})}/><Input p="Cost impact" type="number" v={change.cost_impact} set={v=>setChange({...change,cost_impact:Number(v)})}/><Button disabled={!change.title||!change.project_id||busy} onClick={()=>act(()=>saveConstructionChange({data:{...change,workspace_id:workspaceId}}))}>Record</Button></Panel></div>
 </section>
}
function Panel({title,children}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><h3 className="mb-3 text-sm font-medium text-white">{title}</h3>{children}</div>}
function Input({p,v,set,type='text'}){return <input aria-label={p} placeholder={p} type={type} value={v??''} onChange={e=>set(e.target.value)} className="mb-2 w-full rounded-xl border border-white/[.08] bg-black/40 px-3 py-2 text-xs text-white outline-none"/>}
function Select({v,set,opts}){return <select value={v} onChange={e=>set(e.target.value)} className="mb-2 w-full rounded-xl border border-white/[.08] bg-black/40 px-3 py-2 text-xs text-white">{opts.map(x=><option key={x}>{x}</option>)}</select>}
function ProjectSelect({projects,v,set}){return <select value={v} onChange={e=>set(e.target.value)} className="mb-2 w-full rounded-xl border border-white/[.08] bg-black/40 px-3 py-2 text-xs text-white"><option value="">Select project</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}
function Button({children,...p}){return <button {...p} className="mt-1 inline-flex items-center gap-1 rounded-xl bg-cyan-200 px-3 py-2 text-xs font-semibold text-black disabled:opacity-40"><Plus className="h-3.5 w-3.5"/>{children}</button>}
function Metric({l,v,I}){return <div className="rounded-2xl border border-white/[.07] p-4"><I className="h-4 w-4 text-cyan-200"/><p className="mt-2 text-xl font-semibold text-white">{v}</p><p className="text-xs text-zinc-600">{l}</p></div>}
