import { useEffect, useMemo, useState } from 'react';
import { HardHat, Plus, RefreshCw, AlertTriangle, ClipboardCheck, Wrench, Factory, Gauge, Save } from 'lucide-react';
import ConstructionControlCentre from '@/components/construction/ConstructionControlCentre';
import { listConstructionWorkspaces,getConstructionOperations,saveConstructionWorkspace,saveConstructionProject,saveConstructionIssue,saveConstructionAsset } from '@/lib/construction/construction-operations.functions';

export default function ConstructionOperationsConsole(){
 const[workspaces,setWorkspaces]=useState([]),[selected,setSelected]=useState(''),[ops,setOps]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const[ws,setWs]=useState({name:'',organisation_name:'',sector:'construction',currency:'GBP',timezone:'Europe/London',notes:''});
 const[project,setProject]=useState({name:'',project_number:'',client_name:'',location_text:'',status:'active',contract_value:0,budget:0,description:''});
 const[issue,setIssue]=useState({issue_type:'safety',title:'',description:'',severity:'medium',status:'open',owner_name:''});
 const[asset,setAsset]=useState({name:'',asset_type:'equipment',identifier:'',manufacturer:'',model:'',status:'operational',criticality:'medium'});
 async function load(){const rows=await listConstructionWorkspaces({data:{}});setWorkspaces(rows);setSelected(s=>s&&rows.some(x=>x.id===s)?s:(rows[0]?.id||''));}
 async function loadOps(id=selected){if(id)setOps(await getConstructionOperations({data:{workspace_id:id}}));}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(selected)loadOps(selected).catch(e=>setError(e.message));},[selected]);
 const priority=useMemo(()=>ops?[...ops.dashboard.criticalIssues.map(x=>({title:x.title,detail:'Critical '+x.issue_type})),...ops.dashboard.assetsOut.map(x=>({title:x.name,detail:'Asset out of service'})),...ops.dashboard.dueInspections.map(x=>({title:x.title,detail:'Inspection due within 7 days'})),...ops.dashboard.maintenanceDue.map(x=>({title:x.title,detail:'Maintenance due within 7 days'}))].slice(0,20):[],[ops]);
 async function act(fn){setBusy(true);setError('');try{await fn();await loadOps();}catch(e){setError(e.message||'Operation failed');}finally{setBusy(false);}}
 if(!workspaces.length)return <section className="rounded-[28px] border border-amber-300/10 bg-black/30 p-5 lg:p-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-200">Operations workspace</p><h2 className="mt-1 text-xl font-semibold text-white">Create a construction / industrial workspace</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><Input label="Workspace name" value={ws.name} set={v=>setWs({...ws,name:v})}/><Input label="Organisation" value={ws.organisation_name} set={v=>setWs({...ws,organisation_name:v})}/><Input label="Sector" value={ws.sector} set={v=>setWs({...ws,sector:v})}/><Input label="Currency" value={ws.currency} set={v=>setWs({...ws,currency:v})}/></div>{error&&<Error text={error}/>}<Button disabled={!ws.name||busy} onClick={()=>act(async()=>{const x=await saveConstructionWorkspace({data:ws});await load();setSelected(x.id);})} icon={Save}>Create workspace</Button></section>;
 return <section className="rounded-[28px] border border-amber-300/10 bg-black/30 p-5 lg:p-6">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-200">Live operating layer</p><h2 className="mt-1 text-xl font-semibold text-white">Construction & industrial operations</h2><p className="mt-2 text-sm text-zinc-500">Saved projects, assets, issues, inspections and maintenance feed this command view.</p></div><div className="flex gap-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="ci-input">{workspaces.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={()=>loadOps()} className="ci-button"><RefreshCw className="h-3.5 w-3.5"/>Refresh</button></div></div>
  {error&&<Error text={error}/>}
  {ops&&<><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[['Active projects',ops.dashboard.activeProjects,HardHat],['Open issues',ops.dashboard.openIssues,AlertTriangle],['Critical',ops.dashboard.criticalIssues.length,AlertTriangle],['Inspections due',ops.dashboard.dueInspections.length,ClipboardCheck],['Maintenance due',ops.dashboard.maintenanceDue.length,Wrench],['Assets out',ops.dashboard.assetsOut.length,Gauge]].map(([l,v,I])=><Metric key={l} label={l} value={v} icon={I}/>)}</div>
  <div className="mt-5 grid gap-4 xl:grid-cols-2"><Panel title="AI operational priority queue">{priority.length?priority.map((x,i)=><div key={i} className="mb-2 rounded-xl border border-white/[.06] bg-black/25 p-3"><p className="text-sm text-white">{x.title}</p><p className="mt-1 text-xs text-zinc-600">{x.detail}</p></div>):<Empty text="No critical exceptions or near-term due work."/ >}</Panel><Panel title="Current projects">{ops.projects.length?ops.projects.slice(0,12).map(x=><div key={x.id} className="mb-2 rounded-xl border border-white/[.06] p-3"><p className="text-sm text-white">{x.name}</p><p className="mt-1 text-xs text-zinc-600">{x.status} · {x.client_name||'No client'} · {x.location_text||'No location'}</p></div>):<Empty text="No projects yet."/ >}</Panel></div>
  <div className="mt-5 grid gap-4 xl:grid-cols-3"><Panel title="Add project"><Input label="Project name" value={project.name} set={v=>setProject({...project,name:v})}/><Input label="Project number" value={project.project_number} set={v=>setProject({...project,project_number:v})}/><Input label="Client" value={project.client_name} set={v=>setProject({...project,client_name:v})}/><Input label="Location" value={project.location_text} set={v=>setProject({...project,location_text:v})}/><Button disabled={!project.name||busy} onClick={()=>act(async()=>{await saveConstructionProject({data:{...project,workspace_id:selected}});setProject({...project,name:'',project_number:''});})} icon={Plus}>Save project</Button></Panel>
  <Panel title="Log issue / risk"><Select label="Type" value={issue.issue_type} set={v=>setIssue({...issue,issue_type:v})} options={['safety','quality','defect','rfi','constraint','delay','maintenance','commercial','environmental','other']}/><Input label="Title" value={issue.title} set={v=>setIssue({...issue,title:v})}/><Select label="Severity" value={issue.severity} set={v=>setIssue({...issue,severity:v})} options={['low','medium','high','critical']}/><Input label="Owner" value={issue.owner_name} set={v=>setIssue({...issue,owner_name:v})}/><Button disabled={!issue.title||busy} onClick={()=>act(async()=>{await saveConstructionIssue({data:{...issue,workspace_id:selected,project_id:null,asset_id:null}});setIssue({...issue,title:'',description:''});})} icon={AlertTriangle}>Log issue</Button></Panel>
  <Panel title="Register plant / asset"><Input label="Asset name" value={asset.name} set={v=>setAsset({...asset,name:v})}/><Input label="Asset type" value={asset.asset_type} set={v=>setAsset({...asset,asset_type:v})}/><Input label="Identifier" value={asset.identifier} set={v=>setAsset({...asset,identifier:v})}/><Select label="Criticality" value={asset.criticality} set={v=>setAsset({...asset,criticality:v})} options={['low','medium','high','critical']}/><Button disabled={!asset.name||busy} onClick={()=>act(async()=>{await saveConstructionAsset({data:{...asset,workspace_id:selected,project_id:null}});setAsset({...asset,name:'',identifier:''});})} icon={Factory}>Register asset</Button></Panel></div></>}
  {ops&&<ConstructionControlCentre workspaceId={selected} projects={ops.projects}/>}\n  <style>{`.ci-input{border-radius:.75rem;border:1px solid rgba(255,255,255,.08);background:rgba(0,0,0,.45);padding:.55rem .7rem;font-size:.75rem;color:white;outline:none}.ci-button{display:flex;align-items:center;gap:.4rem;border-radius:.75rem;border:1px solid rgba(255,255,255,.08);padding:.55rem .7rem;font-size:.75rem;color:#d4d4d8}`}</style>
 </section>;
}
function Panel({title,children}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><h3 className="mb-3 text-sm font-medium text-white">{title}</h3>{children}</div>}
function Input({label,value,set}){return <label className="mb-3 block"><span className="mb-1 block text-[10px] uppercase tracking-[.12em] text-zinc-600">{label}</span><input value={value||''} onChange={e=>set(e.target.value)} className="ci-input w-full"/></label>}
function Select({label,value,set,options}){return <label className="mb-3 block"><span className="mb-1 block text-[10px] uppercase tracking-[.12em] text-zinc-600">{label}</span><select value={value} onChange={e=>set(e.target.value)} className="ci-input w-full">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Button({children,onClick,disabled,icon:Icon}){return <button onClick={onClick} disabled={disabled} className="mt-2 inline-flex items-center gap-2 rounded-xl bg-amber-200 px-3.5 py-2.5 text-xs font-semibold text-black disabled:opacity-40"><Icon className="h-4 w-4"/>{children}</button>}
function Metric({label,value,icon:Icon}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><Icon className="h-4 w-4 text-amber-200"/><p className="mt-2 text-2xl font-semibold text-white">{value}</p><p className="text-xs text-zinc-600">{label}</p></div>}
function Empty({text}){return <p className="rounded-xl border border-dashed border-white/[.08] p-6 text-center text-xs text-zinc-600">{text}</p>}
function Error({text}){return <div className="mt-4 rounded-xl border border-rose-300/15 bg-rose-300/[.04] p-3 text-xs text-rose-200">{text}</div>}
