import{useEffect,useMemo,useState}from'react';
import{ExternalLink,Plus,Scale,Trash2}from'lucide-react';
import{deleteLegalRightsObligation,LEGAL_EVIDENCE_STATUSES,LEGAL_RIGHTS_KINDS,LEGAL_RIGHTS_STATUSES,LEGAL_RIGHTS_WORKFLOW_NOTICE,listLegalRightsObligations,saveLegalRightsObligation}from'@/lib/legal/legal-rights-obligations.functions';

const label=value=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const empty={kind:'obligation',title:'',jurisdiction:'United Kingdom',authority:'',source_url:'',source_locator:'',responsible_party:'',counterparty:'',trigger_event:'',due_on:'',status:'review',evidence_status:'unverified',notes:''};
const payload=(row,patch={})=>{const x={...row,...patch};return{id:x.id,kind:x.kind,title:x.title,jurisdiction:x.jurisdiction,authority:x.authority||'',source_url:x.source_url||'',source_locator:x.source_locator||'',responsible_party:x.responsible_party||'',counterparty:x.counterparty||'',trigger_event:x.trigger_event||'',due_on:x.due_on||'',status:x.status,evidence_status:x.evidence_status,notes:x.notes||''}};

export default function LegalRightsObligations(){
 const[rows,setRows]=useState([]),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){try{setRows(await listLegalRightsObligations({data:{}}));setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load rights and obligations.')}}
 useEffect(()=>{load()},[]);
 const summary=useMemo(()=>{const today=new Date().toISOString().slice(0,10);return{review:rows.filter(x=>x.status==='review').length,active:rows.filter(x=>x.status==='active').length,pastDate:rows.filter(x=>x.due_on&&x.due_on<today&&!['satisfied','expired'].includes(x.status)).length}},[rows]);
 async function create(e){e.preventDefault();setBusy(true);try{await saveLegalRightsObligation({data:form});setForm(empty);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save the working record.')}finally{setBusy(false)}}
 async function update(row,patch){setBusy(true);try{await saveLegalRightsObligation({data:payload(row,patch)});await load()}catch(e){setError(e instanceof Error?e.message:'Could not update the working record.')}finally{setBusy(false)}}
 async function remove(id){setBusy(true);try{await deleteLegalRightsObligation({data:{id}});await load()}catch(e){setError(e instanceof Error?e.message:'Could not delete the working record.')}finally{setBusy(false)}}
 return <section className="rounded-[24px] border border-white/[.08] bg-white/[.02] p-5">
  <div className="flex items-center gap-2"><Scale className="h-4 w-4 text-violet-300"/><h2 className="font-medium text-white">Rights & obligations workflow</h2></div>
  <p className="mt-1 max-w-4xl text-xs leading-5 text-zinc-500">Turn researched legal material into a reviewable working register of rights, duties, prohibitions, permissions, deadlines and remedies. Source and status fields are evidence controls, not Blackstar legal conclusions.</p>
  <p className="mt-3 rounded-xl border border-amber-300/10 bg-amber-300/[.03] p-3 text-[11px] leading-5 text-amber-100/70">{LEGAL_RIGHTS_WORKFLOW_NOTICE}</p>
  <div className="mt-4 grid grid-cols-3 gap-2">{[['Needs review',summary.review],['Active',summary.active],['Past recorded date',summary.pastDate]].map(([name,count])=><div key={name} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><p className="text-[9px] uppercase tracking-[.12em] text-zinc-600">{name}</p><p className="mt-1 text-sm font-semibold text-white">{count}</p></div>)}</div>
  <form onSubmit={create} className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-4">
   <select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})} className="rounded-xl border border-white/10 bg-[#101116] px-3 py-2 text-xs text-white">{LEGAL_RIGHTS_KINDS.map(x=><option key={x} value={x}>{label(x)}</option>)}</select>
   <input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Right / obligation / deadline" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input required value={form.jurisdiction} onChange={e=>setForm({...form,jurisdiction:e.target.value})} placeholder="Jurisdiction" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input value={form.authority} onChange={e=>setForm({...form,authority:e.target.value})} placeholder="Authority / regulator / court" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input value={form.source_url} onChange={e=>setForm({...form,source_url:e.target.value})} placeholder="Authoritative source URL" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input value={form.source_locator} onChange={e=>setForm({...form,source_locator:e.target.value})} placeholder="Section / article / paragraph" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input value={form.responsible_party} onChange={e=>setForm({...form,responsible_party:e.target.value})} placeholder="Responsible / entitled party" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input value={form.counterparty} onChange={e=>setForm({...form,counterparty:e.target.value})} placeholder="Counterparty / beneficiary" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input value={form.trigger_event} onChange={e=>setForm({...form,trigger_event:e.target.value})} placeholder="Trigger / condition" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <input type="date" value={form.due_on} onChange={e=>setForm({...form,due_on:e.target.value})} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white"/>
   <select value={form.evidence_status} onChange={e=>setForm({...form,evidence_status:e.target.value})} className="rounded-xl border border-white/10 bg-[#101116] px-3 py-2 text-xs text-white">{LEGAL_EVIDENCE_STATUSES.map(x=><option key={x} value={x}>{label(x)}</option>)}</select>
   <select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="rounded-xl border border-white/10 bg-[#101116] px-3 py-2 text-xs text-white">{LEGAL_RIGHTS_STATUSES.map(x=><option key={x} value={x}>{label(x)}</option>)}</select>
   <textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Evidence, implementation, factual assumptions or professional-review notes" className="min-h-20 rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-xs text-white md:col-span-2 xl:col-span-3"/>
   <button disabled={busy} className="inline-flex items-center justify-center gap-1 rounded-xl border border-violet-300/15 bg-violet-300/[.05] px-3 py-2 text-xs text-violet-100"><Plus className="h-3.5 w-3.5"/>Add working record</button>
  </form>
  {error&&<p className="mt-3 text-xs text-rose-300">{error}</p>}
  <div className="mt-4 space-y-2">{rows.length===0?<p className="rounded-xl border border-dashed border-white/10 p-4 text-xs text-zinc-600">No rights or obligations recorded yet.</p>:rows.map(row=><article key={row.id} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-violet-300/10 px-2 py-0.5 text-[9px] uppercase text-violet-200/70">{label(row.kind)}</span><p className="text-xs font-medium text-white">{row.title}</p></div><p className="mt-1 text-[10px] text-zinc-500">{row.jurisdiction}{row.authority?' · '+row.authority:''}{row.due_on?' · recorded date '+row.due_on:''}</p>{row.responsible_party&&<p className="mt-1 text-[10px] text-zinc-600">Party: {row.responsible_party}{row.counterparty?' · counterpart: '+row.counterparty:''}</p>}{row.trigger_event&&<p className="mt-1 text-[10px] text-zinc-600">Trigger: {row.trigger_event}</p>}{row.source_url&&<a href={row.source_url} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-[10px] text-cyan-300/80">Source{row.source_locator?' · '+row.source_locator:''}<ExternalLink className="h-3 w-3"/></a>}</div><button onClick={()=>remove(row.id)} disabled={busy} aria-label="Delete right or obligation" className="p-2 text-zinc-600 hover:text-rose-300"><Trash2 className="h-3.5 w-3.5"/></button></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select disabled={busy} value={row.status} onChange={e=>update(row,{status:e.target.value})} className="rounded-lg border border-white/[.07] bg-[#101116] px-2 py-1.5 text-[10px] text-zinc-300">{LEGAL_RIGHTS_STATUSES.map(x=><option key={x} value={x}>Status: {label(x)}</option>)}</select><select disabled={busy} value={row.evidence_status} onChange={e=>update(row,{evidence_status:e.target.value})} className="rounded-lg border border-white/[.07] bg-[#101116] px-2 py-1.5 text-[10px] text-zinc-300">{LEGAL_EVIDENCE_STATUSES.map(x=><option key={x} value={x}>Evidence: {label(x)}</option>)}</select></div></article>)}</div>
 </section>
}