// Mock data for the Tool & Plugin Marketplace. Placeholder only — backend ready.
import {
  Code2, FlaskConical, Megaphone, MessageSquare, Workflow, Briefcase,
  Database, Globe, Brain, Shield, Terminal, FileSearch, Mail, Slack,
  CalendarClock, FileSpreadsheet, Table, Chrome, Sparkles, Lock, Webhook,
} from 'lucide-react';

export const CATEGORIES = [
  { id: 'Developer', icon: Code2, grad: 'from-violet-500 to-indigo-500' },
  { id: 'Research', icon: FlaskConical, grad: 'from-amber-500 to-orange-500' },
  { id: 'Marketing', icon: Megaphone, grad: 'from-fuchsia-500 to-pink-500' },
  { id: 'Communication', icon: MessageSquare, grad: 'from-sky-500 to-cyan-500' },
  { id: 'Automation', icon: Workflow, grad: 'from-emerald-500 to-teal-500' },
  { id: 'Business', icon: Briefcase, grad: 'from-indigo-500 to-violet-500' },
  { id: 'Data', icon: Database, grad: 'from-rose-500 to-pink-500' },
  { id: 'Browser', icon: Globe, grad: 'from-cyan-500 to-blue-500' },
  { id: 'AI', icon: Brain, grad: 'from-violet-500 to-fuchsia-500' },
  { id: 'Security', icon: Shield, grad: 'from-zinc-500 to-zinc-700' },
];

export const PLUGINS = [
  { id: 'p1', name: 'Code Review Sentinel', icon: Terminal, category: 'Developer', grad: 'from-violet-500 to-indigo-500', description: 'Automated PR reviews with security and style checks across 14 languages.', creator: 'Palladium Labs', rating: 4.8, installs: '12.4k', version: '2.1.0', price: 'Free', permissions: ['Read repos', 'Post comments'], agents: ['Devon', 'Leo'], capabilities: ['Static analysis', 'Dependency audit', 'Inline suggestions'], workflows: ['PR gate', 'Pre-merge audit'], docs: '# Code Review Sentinel\nReviews pull requests for security, style, and complexity.', reviews: [{ user: 'Aisha K.', score: 5, text: 'Catches issues our humans miss.' }, { user: 'Marco D.', score: 4, text: 'Great, occasional false positives.' }], versions: ['2.1.0 — security rule pack', '2.0.4 — perf', '1.9.0 — multi-repo'] },
  { id: 'p2', name: 'Deep Research Crawler', icon: FileSearch, category: 'Research', grad: 'from-amber-500 to-orange-500', description: 'Crawl, summarize and cite from 1,000+ sources with provenance.', creator: 'Atlas AI', rating: 4.6, installs: '8.9k', version: '3.4.0', price: '$29/mo', permissions: ['Web access', 'Save files'], agents: ['Aria'], capabilities: ['Multi-hop search', 'Citation graph', 'PDF extraction'], workflows: ['Market scan', 'Lit review'], docs: '# Deep Research Crawler\nAssembles cited research dossiers.', reviews: [{ user: 'Maya R.', score: 5, text: 'Indispensable for briefings.' }], versions: ['3.4.0 — citation graph', '3.3.0 — faster crawl'] },
  { id: 'p3', name: 'CopyForge', icon: Megaphone, category: 'Marketing', grad: 'from-fuchsia-500 to-pink-500', description: 'Brand-aware ad copy and landing variants with A/B scoring.', creator: 'GrowthKit', rating: 4.4, installs: '21.0k', version: '1.7.2', price: 'Free', permissions: ['Read brand kit', 'Generate text'], agents: ['Mia'], capabilities: ['Variant gen', 'Voice match', 'AB scoring'], workflows: ['Campaign launch'], docs: '# CopyForge\nGenerates on-brand marketing copy.', reviews: [{ user: 'Priya S.', score: 4, text: 'Voice match is solid.' }], versions: ['1.7.2 — voice presets', '1.6.0 — AB scoring'] },
  { id: 'p4', name: 'Slack Bridge', icon: Slack, category: 'Communication', grad: 'from-sky-500 to-cyan-500', description: 'Two-way messaging, threading and channel routing for agents.', creator: 'Palladium Labs', rating: 4.7, installs: '33.2k', version: '4.0.1', price: 'Free', permissions: ['Read channels', 'Post messages'], agents: ['Cody', 'Aria'], capabilities: ['Thread sync', 'Channel routing', 'DM handoff'], workflows: ['Support triage', 'Standup digest'], docs: '# Slack Bridge\nConnects agents to Slack.', reviews: [{ user: 'Sam L.', score: 5, text: 'Our support backbone.' }], versions: ['4.0.1 — thread sync', '3.8.0 — routing'] },
  { id: 'p5', name: 'Outreach Mailer', icon: Mail, category: 'Communication', grad: 'from-sky-500 to-blue-500', description: 'Personalized cold outreach sequences with reply detection.', creator: 'FunnelOps', rating: 4.2, installs: '6.1k', version: '2.0.0', price: '$19/mo', permissions: ['Send email', 'Read replies'], agents: ['Mia'], capabilities: ['Sequence builder', 'Reply detect', 'Warmup'], workflows: ['Outbound campaign'], docs: '# Outreach Mailer\nCold outreach at scale.', reviews: [{ user: 'Marco D.', score: 3, text: 'Good, needs better warmup.' }], versions: ['2.0.0 — warmup', '1.4.0 — reply detect'] },
  { id: 'p6', name: 'Flow Orchestrator', icon: Workflow, category: 'Automation', grad: 'from-emerald-500 to-teal-500', description: 'Visual multi-step automation with branches, waits and retries.', creator: 'Palladium Labs', rating: 4.9, installs: '18.7k', version: '5.1.0', price: 'Free', permissions: ['Run workflows', 'Access entities'], agents: ['All'], capabilities: ['Branching', 'Durable waits', 'Retry'], workflows: ['Approval chains', 'Onboarding'], docs: '# Flow Orchestrator\nBuild automations visually.', reviews: [{ user: 'Devon K.', score: 5, text: 'Replaced 3 tools.' }], versions: ['5.1.0 — durable waits', '5.0.0 — branching'] },
  { id: 'p7', name: 'CRM Sync', icon: Briefcase, category: 'Business', grad: 'from-indigo-500 to-violet-500', description: 'Bi-directional sync with Salesforce, HubSpot and Pipedrive.', creator: 'RevOps Co', rating: 4.5, installs: '9.8k', version: '2.3.1', price: '$49/mo', permissions: ['Read CRM', 'Write CRM'], agents: ['Cody'], capabilities: ['Field mapping', 'Dedup', 'Pipeline update'], workflows: ['Lead routing'], docs: '# CRM Sync\nKeep CRM in lockstep.', reviews: [{ user: 'Aisha K.', score: 4, text: 'Mapping UI is great.' }], versions: ['2.3.1 — HubSpot v3', '2.2.0 — dedup'] },
  { id: 'p8', name: 'Spreadsheet Mind', icon: FileSpreadsheet, category: 'Data', grad: 'from-rose-500 to-pink-500', description: 'Query, transform and chart tabular data with natural language.', creator: 'GridIQ', rating: 4.3, installs: '7.4k', version: '1.5.0', price: 'Free', permissions: ['Read sheets', 'Export'], agents: ['Finn', 'Leo'], capabilities: ['NL query', 'Pivot gen', 'Chart'], workflows: ['Report build'], docs: '# Spreadsheet Mind\nAsk questions of your data.', reviews: [{ user: 'Maya R.', score: 4, text: 'Pivots are a breeze.' }], versions: ['1.5.0 — chart pack', '1.4.0 — NL query'] },
  { id: 'p9', name: 'SQL Insight', icon: Database, category: 'Data', grad: 'from-rose-500 to-orange-500', description: 'Self-serve analytics on your warehouse with safe read-only queries.', creator: 'DataHaus', rating: 4.6, installs: '5.2k', version: '3.0.0', price: '$39/mo', permissions: ['Read-only SQL', 'Cache results'], agents: ['Finn'], capabilities: ['Schema map', 'Safe SQL', 'Cache'], workflows: ['Weekly KPI'], docs: '# SQL Insight\nWarehouse analytics, safely.', reviews: [{ user: 'Sam L.', score: 5, text: 'Replaced our BI tool.' }], versions: ['3.0.0 — schema map', '2.9.0 — cache'] },
  { id: 'p10', name: 'Browser Pilot', icon: Chrome, category: 'Browser', grad: 'from-cyan-500 to-blue-500', description: 'Headless browser automation: scrape, fill, screenshot and verify.', creator: 'Palladium Labs', rating: 4.5, installs: '14.1k', version: '2.8.0', price: 'Free', permissions: ['Navigate', 'Screenshot'], agents: ['Aria', 'Leo'], capabilities: ['Scrape', 'Form fill', 'Screenshot'], workflows: ['Price monitor'], docs: '# Browser Pilot\nAutomate the web.', reviews: [{ user: 'Marco D.', score: 4, text: 'Great for monitoring.' }], versions: ['2.8.0 — verify', '2.7.0 — fill'] },
  { id: 'p11', name: 'Web Extract', icon: Globe, category: 'Browser', grad: 'from-cyan-500 to-teal-500', description: 'Structured extraction from any page with schema-aware parsing.', creator: 'ScrapeHub', rating: 4.1, installs: '4.6k', version: '1.2.0', price: '$15/mo', permissions: ['Fetch URLs'], agents: ['Aria'], capabilities: ['Schema parse', 'Pagination'], workflows: ['Competitor scan'], docs: '# Web Extract\nTurn pages into data.', reviews: [{ user: 'Priya S.', score: 4, text: 'Pagination is handy.' }], versions: ['1.2.0 — schema', '1.1.0'] },
  { id: 'p12', name: 'Reasoning Core', icon: Brain, category: 'AI', grad: 'from-violet-500 to-fuchsia-500', description: 'Multi-step reasoning with tool-use, planning and self-checks.', creator: 'Palladium Labs', rating: 4.8, installs: '27.5k', version: '6.0.0', price: 'Free', permissions: ['Call models', 'Use tools'], agents: ['All'], capabilities: ['Planning', 'Tool use', 'Self-check'], workflows: ['Research', 'Support'], docs: '# Reasoning Core\nSmarter agents.', reviews: [{ user: 'Aisha K.', score: 5, text: 'Plans are reliable.' }], versions: ['6.0.0 — planning', '5.4.0'] },
  { id: 'p13', name: 'Image Forge', icon: Sparkles, category: 'AI', grad: 'from-violet-500 to-indigo-500', description: 'Generate and edit images with style transfer and inpainting.', creator: 'StudioX', rating: 4.4, installs: '11.9k', version: '2.2.0', price: 'Free', permissions: ['Generate images'], agents: ['Mia'], capabilities: ['Gen', 'Inpaint', 'Style transfer'], workflows: ['Ad creative'], docs: '# Image Forge\nVisuals on demand.', reviews: [{ user: 'Maya R.', score: 4, text: 'Style transfer is fun.' }], versions: ['2.2.0 — inpaint', '2.1.0'] },
  { id: 'p14', name: 'Secret Vault', icon: Lock, category: 'Security', grad: 'from-zinc-500 to-zinc-700', description: 'Secrets management with rotation, masking and audit logs.', creator: 'SentinelSec', rating: 4.7, installs: '8.2k', version: '3.1.0', price: '$25/mo', permissions: ['Read secrets', 'Rotate'], agents: ['Devon'], capabilities: ['Rotation', 'Masking', 'Audit'], workflows: ['Key rotation'], docs: '# Secret Vault\nSecrets, done right.', reviews: [{ user: 'Devon K.', score: 5, text: 'Audit trail is gold.' }], versions: ['3.1.0 — rotation', '3.0.0'] },
  { id: 'p15', name: 'Threat Watch', icon: Shield, category: 'Security', grad: 'from-rose-500 to-zinc-700', description: 'Continuous dependency and config scanning with CVE alerts.', creator: 'SentinelSec', rating: 4.6, installs: '6.7k', version: '2.0.3', price: '$35/mo', permissions: ['Scan repos', 'Alert'], agents: ['Devon'], capabilities: ['CVE scan', 'Config audit', 'Alerts'], workflows: ['Nightly scan'], docs: '# Threat Watch\nKnow your exposure.', reviews: [{ user: 'Sam L.', score: 5, text: 'Caught a CVE overnight.' }], versions: ['2.0.3 — alerts', '1.9.0'] },
  { id: 'p16', name: 'Webhook Relay', icon: Webhook, category: 'Automation', grad: 'from-emerald-500 to-lime-500', description: 'Relay, filter and sign webhooks across services and agents.', creator: 'Palladium Labs', rating: 4.5, installs: '10.3k', version: '1.6.0', price: 'Free', permissions: ['Receive webhooks', 'Forward'], agents: ['All'], capabilities: ['Filter', 'Sign', 'Retry'], workflows: ['Event router'], docs: '# Webhook Relay\nPlumb your events.', reviews: [{ user: 'Aisha K.', score: 4, text: 'Signing is a nice touch.' }], versions: ['1.6.0 — signing', '1.5.0'] },
];

export const RATING_STARS = (r) => Math.round(r);