// Mock data for the PalladiumAI Admin Organisation Management — illustrative, backend-ready.

export const STATUSES = ['active', 'suspended', 'trial'];
export const PLANS = ['Free', 'Pro', 'Team', 'Enterprise'];

export const ORGS = [
  { id:'o1', name:'Palladium Studio', owner:'Sarah Chen', ownerEmail:'sarah@palladium.ai', members:24, plan:'Enterprise', projects:8, agents:12, usage:{ requests: 184200, storage: 420, seats: 24 }, created:'2024-05-30', status:'active',
    teams:['Product','Engineering','Marketing','Operations'],
    membersList:[{n:'Sarah Chen',e:'sarah@palladium.ai',r:'Owner',t:'Product'},{n:'Nora Fields',e:'nora@palladium.ai',r:'Admin',t:'Engineering'},{n:'Liam Wood',e:'liam@palladium.ai',r:'Member',t:'Engineering'},{n:'Ivy Stone',e:'ivy@palladium.ai',r:'Member',t:'Marketing'}],
    projects:['Atlas Analytics','Nova Support','Orbit Commerce','Palladium Admin','Palladium API'],
    agents:['Atlas Research','Insight Agent','Marketing Agent','CodePilot'],
    billing:{ plan:'Enterprise', mrr:'$1,290', method:'Invoice', since:'May 2024', seats:24 },
    security:{ mfaEnforced:true, sso:true, sessions:18, risk:'low', lastIncident:'None' } },
  { id:'o2', name:'Acme Corp', owner:'Maya Patel', ownerEmail:'maya@acme.com', members:11, plan:'Team', projects:5, agents:6, usage:{ requests: 92100, storage: 180, seats: 11 }, created:'2024-11-04', status:'active',
    teams:['Core','Support'],
    membersList:[{n:'Maya Patel',e:'maya@acme.com',r:'Owner',t:'Core'},{n:'Dan Roy',e:'dan@acme.com',r:'Admin',t:'Support'},{n:'Fay Lin',e:'fay@acme.com',r:'Member',t:'Core'}],
    projects:['Acme Dashboard','Acme CRM','Acme Support'],
    agents:['Support Agent','CodePilot'],
    billing:{ plan:'Team', mrr:'$99', method:'Visa •••• 4242', since:'Nov 2024', seats:11 },
    security:{ mfaEnforced:true, sso:false, sessions:8, risk:'low', lastIncident:'None' } },
  { id:'o3', name:'Globex', owner:'James Lee', ownerEmail:'james@globex.io', members:3, plan:'Pro', projects:3, agents:2, usage:{ requests: 31200, storage: 80, seats: 3 }, created:'2025-01-22', status:'suspended',
    teams:['Core'],
    membersList:[{n:'James Lee',e:'james@globex.io',r:'Owner',t:'Core'},{n:'Kara Vee',e:'kara@globex.io',r:'Member',t:'Core'}],
    projects:['Globex Web','Globex Docs'],
    agents:['Knowledge Agent'],
    billing:{ plan:'Pro', mrr:'$29', method:'Mastercard •••• 8800', since:'Jan 2025', seats:3 },
    security:{ mfaEnforced:false, sso:false, sessions:0, risk:'medium', lastIncident:'Failed logins (3d ago)' } },
  { id:'o4', name:'Initech', owner:'Lina Garcia', ownerEmail:'lina@initech.com', members:42, plan:'Enterprise', projects:11, agents:14, usage:{ requests: 240100, storage: 640, seats: 42 }, created:'2024-07-18', status:'active',
    teams:['Platform','Finance','Ops','QA'],
    membersList:[{n:'Lina Garcia',e:'lina@initech.com',r:'Owner',t:'Platform'},{n:'Owen Park',e:'owen@initech.com',r:'Admin',t:'Finance'},{n:'Zoe Kim',e:'zoe@initech.com',r:'Member',t:'QA'}],
    projects:['Initech Suite','Initech Finance','Initech Ops'],
    agents:['Insight Agent','Atlas Research','Marketing Agent'],
    billing:{ plan:'Enterprise', mrr:'$2,490', method:'Invoice', since:'Jul 2024', seats:42 },
    security:{ mfaEnforced:true, sso:true, sessions:30, risk:'low', lastIncident:'None' } },
  { id:'o5', name:'Umbrella', owner:'Tom Wright', ownerEmail:'tom@umbrella.org', members:1, plan:'Free', projects:1, agents:1, usage:{ requests: 4200, storage: 20, seats: 1 }, created:'2025-04-02', status:'active',
    teams:['Core'],
    membersList:[{n:'Tom Wright',e:'tom@umbrella.org',r:'Owner',t:'Core'}],
    projects:['Personal Site'],
    agents:['CodePilot'],
    billing:{ plan:'Free', mrr:'$0', method:'—', since:'Apr 2025', seats:1 },
    security:{ mfaEnforced:false, sso:false, sessions:1, risk:'low', lastIncident:'None' } },
  { id:'o6', name:'Hooli', owner:'Ben Carter', ownerEmail:'ben@hooli.com', members:9, plan:'Pro', projects:6, agents:4, usage:{ requests: 68400, storage: 220, seats: 9 }, created:'2025-02-28', status:'trial',
    teams:['Growth','Product'],
    membersList:[{n:'Ben Carter',e:'ben@hooli.com',r:'Owner',t:'Growth'},{n:'Rae Nix',e:'rae@hooli.com',r:'Member',t:'Product'}],
    projects:['Hooli App','Hooli Marketing'],
    agents:['Marketing Agent','Support Agent'],
    billing:{ plan:'Pro (trial)', mrr:'$0', method:'Pending', since:'Feb 2025', seats:9 },
    security:{ mfaEnforced:true, sso:false, sessions:6, risk:'low', lastIncident:'None' } },
];