import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';

type Sb = { from: (table: string) => any };
const uuid=z.string().uuid();
const text=(n:number)=>z.string().trim().max(n).optional();
const workspace=z.object({id:uuid.optional(),name:z.string().trim().min(1).max(180),organisation_name:text(180),sector:z.string().trim().min(1).max(100).default('construction'),currency:z.string().trim().min(3).max(8).default('GBP'),timezone:z.string().trim().min(1).max(120).default('Europe/London'),notes:text(8000)});
const project=z.object({id:uuid.optional(),workspace_id:uuid,name:z.string().trim().min(1).max(200),project_number:text(100),client_name:text(180),location_text:text(500),status:z.enum(['planning','active','on_hold','closeout','completed','cancelled']).default('planning'),start_date:z.string().nullish(),target_end_date:z.string().nullish(),contract_value:z.coerce.number().min(0).optional(),budget:z.coerce.number().min(0).optional(),description:text(8000)});
const issue=z.object({id:uuid.optional(),workspace_id:uuid,project_id:uuid.nullish(),asset_id:uuid.nullish(),issue_type:z.enum(['safety','quality','defect','rfi','constraint','delay','maintenance','commercial','environmental','other']),title:z.string().trim().min(1).max(240),description:text(8000),severity:z.enum(['low','medium','high','critical']).default('medium'),status:z.enum(['open','triaged','in_progress','blocked','resolved','closed']).default('open'),owner_name:text(180),due_at:z.string().datetime({offset:true}).nullish(),resolution:text(8000)});
const asset=z.object({id:uuid.optional(),workspace_id:uuid,project_id:uuid.nullish(),name:z.string().trim().min(1).max(200),asset_type:z.string().trim().min(1).max(120),identifier:text(160),manufacturer:text(160),model:text(160),status:z.enum(['operational','inspection_due','maintenance_due','out_of_service','retired']).default('operational'),criticality:z.enum(['low','medium','high','critical']).default('medium'),last_service_at:z.string().datetime({offset:true}).nullish(),next_service_at:z.string().datetime({offset:true}).nullish()});
async function save(sb:Sb,table:string,userId:string,data:Record<string,unknown>){const{id,...values}=data;const row={...values,updated_at:new Date().toISOString()};if(id){const q=await sb.from(table).update(row).eq('id',id).eq('user_id',userId).select().single();if(q.error)throw new Error(q.error.message);return q.data;}const q=await sb.from(table).insert({...row,user_id:userId}).select().single();if(q.error)throw new Error(q.error.message);return q.data;}

export const listConstructionWorkspaces=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const q=await (context.supabase as unknown as Sb).from('construction_workspaces').select('*').order('updated_at',{ascending:false});if(q.error)throw new Error(q.error.message);return q.data??[];});
export const getConstructionOperations=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({workspace_id:uuid}).parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const qs=await Promise.all([
 sb.from('construction_projects').select('*').eq('workspace_id',data.workspace_id).order('updated_at',{ascending:false}),
 sb.from('construction_assets').select('*').eq('workspace_id',data.workspace_id).order('updated_at',{ascending:false}),
 sb.from('construction_issues').select('*').eq('workspace_id',data.workspace_id).order('updated_at',{ascending:false}).limit(300),
 sb.from('construction_inspections').select('*').eq('workspace_id',data.workspace_id).order('scheduled_at',{ascending:true}).limit(300),
 sb.from('construction_maintenance').select('*').eq('workspace_id',data.workspace_id).order('scheduled_at',{ascending:true}).limit(300),
]);const err=qs.find((q:any)=>q.error)?.error;if(err)throw new Error(err.message);const[projects,assets,issues,inspections,maintenance]=qs.map((q:any)=>q.data??[]);const now=Date.now();return{projects,assets,issues,inspections,maintenance,dashboard:{activeProjects:projects.filter((x:any)=>x.status==='active').length,openIssues:issues.filter((x:any)=>!['resolved','closed'].includes(x.status)).length,criticalIssues:issues.filter((x:any)=>x.severity==='critical'&&!['resolved','closed'].includes(x.status)),dueInspections:inspections.filter((x:any)=>x.status==='scheduled'&&x.scheduled_at&&new Date(x.scheduled_at).getTime()<=now+7*86400000),maintenanceDue:maintenance.filter((x:any)=>['open','scheduled'].includes(x.status)&&x.scheduled_at&&new Date(x.scheduled_at).getTime()<=now+7*86400000),assetsOut:assets.filter((x:any)=>x.status==='out_of_service')}};});
export const saveConstructionWorkspace=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>workspace.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_workspaces',context.userId,data));
export const saveConstructionProject=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>project.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_projects',context.userId,data));
export const saveConstructionIssue=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>issue.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_issues',context.userId,data));
export const saveConstructionAsset=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>asset.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_assets',context.userId,data));
