import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod'; import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
type Sb={from:(t:string)=>any};const u=z.string().uuid();const o=z.string().trim().max(8000).optional();
async function save(sb:Sb,t:string,userId:string,d:any){const{id,...v}=d;const row={...v,updated_at:new Date().toISOString()};const q=id?await sb.from(t).update(row).eq('id',id).eq('user_id',userId).select().single():await sb.from(t).insert({...row,user_id:userId}).select().single();if(q.error)throw new Error(q.error.message);return q.data;}
const task=z.object({id:u.optional(),workspace_id:u,project_id:u,work_package_id:u.nullish(),name:z.string().trim().min(1).max(220),wbs_code:z.string().max(80).optional(),status:z.enum(['planned','ready','in_progress','blocked','complete','cancelled']).default('planned'),planned_start:z.string().nullish(),planned_finish:z.string().nullish(),duration_days:z.coerce.number().int().min(0).default(1),percent_complete:z.coerce.number().min(0).max(100).default(0),is_milestone:z.boolean().default(false),is_critical:z.boolean().default(false),notes:o});
const estimate=z.object({id:u.optional(),workspace_id:u,project_id:u,cost_code:z.string().max(80).optional(),category:z.string().max(100).default('other'),description:z.string().trim().min(1).max(500),quantity:z.coerce.number().min(0).default(0),unit:z.string().max(40).default('each'),labour_rate:z.coerce.number().min(0).default(0),material_rate:z.coerce.number().min(0).default(0),plant_rate:z.coerce.number().min(0).default(0),subcontract_rate:z.coerce.number().min(0).default(0),waste_percent:z.coerce.number().min(0).default(0),markup_percent:z.coerce.number().min(0).default(0),notes:o});
const tender=z.object({id:u.optional(),workspace_id:u,project_id:u.nullish(),title:z.string().trim().min(1).max(220),bidder_name:z.string().trim().min(1).max(220),trade:z.string().max(160).optional(),status:z.enum(['invited','received','clarification','shortlisted','accepted','rejected']).default('received'),bid_value:z.coerce.number().min(0).default(0),programme_days:z.coerce.number().int().min(0).nullish(),exclusions:o,qualifications:o,clarifications:o,score_quality:z.coerce.number().min(0).max(100).nullish(),score_commercial:z.coerce.number().min(0).max(100).nullish(),score_delivery:z.coerce.number().min(0).max(100).nullish(),score_safety:z.coerce.number().min(0).max(100).nullish(),notes:o});
const worker=z.object({id:u.optional(),workspace_id:u,project_id:u.nullish(),partner_id:u.nullish(),name:z.string().trim().min(1).max(220),role:z.string().trim().min(1).max(160),trade:z.string().max(160).optional(),employer:z.string().max(220).optional(),status:z.enum(['planned','active','off_site','suspended','inactive']).default('active'),certification_expiry:z.string().nullish(),induction_complete:z.boolean().default(false),hours_this_week:z.coerce.number().min(0).default(0),notes:o});
export const getConstructionPlanning=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({workspace_id:u}).parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const ts=['construction_schedule_tasks','construction_estimate_items','construction_tenders','construction_workforce'];const qs=await Promise.all(ts.map(t=>sb.from(t).select('*').eq('workspace_id',data.workspace_id).order('updated_at',{ascending:false}).limit(500)));const e=qs.find((q:any)=>q.error)?.error;if(e)throw new Error(e.message);const[tasks,estimateItems,tenders,workforce]=qs.map((q:any)=>q.data??[]);const today=new Date().toISOString().slice(0,10);const estimateTotal=estimateItems.reduce((sum:number,x:any)=>{const base=Number(x.quantity||0)*(Number(x.labour_rate||0)+Number(x.material_rate||0)*(1+Number(x.waste_percent||0)/100)+Number(x.plant_rate||0)+Number(x.subcontract_rate||0));return sum+base*(1+Number(x.markup_percent||0)/100)},0);return{tasks,estimateItems,tenders,workforce,signals:{criticalOpen:tasks.filter((x:any)=>x.is_critical&&x.status!=='complete'),lateTasks:tasks.filter((x:any)=>x.planned_finish&&x.planned_finish<today&&!['complete','cancelled'].includes(x.status)),blockedTasks:tasks.filter((x:any)=>x.status==='blocked'),estimateTotal,expiringCompetencies:workforce.filter((x:any)=>x.certification_expiry&&x.certification_expiry<=new Date(Date.now()+30*86400000).toISOString().slice(0,10)),uninducted:workforce.filter((x:any)=>x.status==='active'&&!x.induction_complete),bestTender:[...tenders].filter((x:any)=>x.status!=='rejected').sort((a:any,b:any)=>{const sa=[a.score_quality,a.score_commercial,a.score_delivery,a.score_safety].filter((v:any)=>v!=null);const sb=[b.score_quality,b.score_commercial,b.score_delivery,b.score_safety].filter((v:any)=>v!=null);return (sb.reduce((n:number,v:number)=>n+v,0)/(sb.length||1))-(sa.reduce((n:number,v:number)=>n+v,0)/(sa.length||1));})[0]??null}};});
export const saveConstructionScheduleTask=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>task.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_schedule_tasks',context.userId,data));
export const saveConstructionEstimateItem=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>estimate.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_estimate_items',context.userId,data));
export const saveConstructionTender=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>tender.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_tenders',context.userId,data));
export const saveConstructionWorker=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>worker.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_workforce',context.userId,data));
