import{createServerFn}from'@tanstack/react-start';import{notify}from'@/lib/notifications/notify.server';import{z}from'zod';import{requireSupabaseAuth}from'@/integrations/supabase/auth-middleware';type Sb={from:(t:string)=>any};const u=z.string().uuid();const roles=z.enum(['project','estimator','site_manager','hse','quality','planner','commercial','procurement','reliability','document_control','bim','sustainability']);const start=z.object({workspace_id:u,project_id:u.nullish(),agent_role:roles,objective:z.string().trim().min(3).max(4000),risk_class:z.enum(['low','medium','high','critical']).default('medium')});
const HIGH=new Set(['hse','quality','reliability','bim']);
export const startConstructionAgentRun=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>start.parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const competent=data.risk_class==='critical'||(data.risk_class==='high'&&HIGH.has(data.agent_role));const q=await sb.from('construction_agent_runs').insert({...data,user_id:context.userId,status:'analysing',requires_competent_person:competent,approval_reason:competent?'High-consequence construction/engineering/safety work requires competent-person review.':null}).select().single();if(q.error)throw new Error(q.error.message);return q.data});
export const listConstructionAgentRuns=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({workspace_id:u}).parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const r=await sb.from('construction_agent_runs').select('*').eq('workspace_id',data.workspace_id).order('updated_at',{ascending:false}).limit(100);if(r.error)throw new Error(r.error.message);const a=await sb.from('construction_agent_actions').select('*').eq('workspace_id',data.workspace_id).order('updated_at',{ascending:false}).limit(200);if(a.error)throw new Error(a.error.message);return{runs:r.data??[],actions:a.data??[],signals:{awaitingApproval:(a.data??[]).filter((x:any)=>x.status==='approval_required'),criticalRuns:(r.data??[]).filter((x:any)=>x.risk_class==='critical'&&!['verified','rejected','failed'].includes(x.status))}}});
export const proposeConstructionAgentAction=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({workspace_id:u,run_id:u,action_type:z.string().min(1).max(160),target_type:z.string().min(1).max(160),target_id:z.string().max(200).nullish(),payload:z.record(z.string(),z.unknown()).default({}),consequence_class:z.enum(['advisory','reversible','external_side_effect','safety_critical','engineering_authority'])}).parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const guarded=['external_side_effect','safety_critical','engineering_authority'].includes(data.consequence_class);const q=await sb.from('construction_agent_actions').insert({...data,user_id:context.userId,status:guarded?'approval_required':'proposed'}).select().single();if(q.error)throw new Error(q.error.message);if(guarded)await sb.from('construction_agent_runs').update({status:'approval_required',updated_at:new Date().toISOString()}).eq('id',data.run_id).eq('user_id',context.userId);return q.data});

export const queueConstructionActionApproval=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({action_id:u}).parse(v)).handler(async({data,context})=>{
 const sb=context.supabase as unknown as Sb;
 const {data:action,error}=await sb.from('construction_agent_actions').select('*').eq('id',data.action_id).eq('user_id',context.userId).maybeSingle();
 if(error)throw new Error(error.message);if(!action)throw new Error('Construction agent action not found.');
 if(!['external_side_effect','safety_critical','engineering_authority'].includes(action.consequence_class))throw new Error('This construction action does not require Mission Control approval.');
 if(action.approval_request_id){const e=await sb.from('approval_requests').select('id,status,execution_status').eq('id',action.approval_request_id).eq('user_id',context.userId).maybeSingle();if(e.error)throw new Error(e.error.message);if(e.data)return{approval:e.data,reused:true as const};}
 const {data:run,error:runError}=await sb.from('construction_agent_runs').select('id,agent_role,objective,risk_class,requires_competent_person').eq('id',action.run_id).eq('user_id',context.userId).maybeSingle();
 if(runError)throw new Error(runError.message);if(!run)throw new Error('Construction agent run not found.');
 const title=(`Construction ${run.agent_role}: ${action.action_type}`).slice(0,200);
 const summary=(`Approve this ${action.consequence_class} construction action. Target: ${action.target_type}. ${run.requires_competent_person?'Competent-person review is required before approval.':''}`).slice(0,500);
 const details={construction_action_id:action.id,construction_run_id:run.id,workspace_id:action.workspace_id,action_type:action.action_type,target_type:action.target_type,target_id:action.target_id,payload:action.payload,consequence_class:action.consequence_class,requires_competent_person:run.requires_competent_person,objective:run.objective};
 const {data:approval,error:approvalError}=await sb.from('approval_requests').insert({user_id:context.userId,org_id:null,agent_id:null,task_id:null,action_type:'construction_governed_action',title,summary,details,risk_level:action.consequence_class==='engineering_authority'||action.consequence_class==='safety_critical'?'critical':run.risk_class,status:'pending'}).select('id,status,title,summary,risk_level,created_at').single();
 if(approvalError)throw new Error(approvalError.message);
 const up=await sb.from('construction_agent_actions').update({approval_request_id:approval.id,status:'approval_required',updated_at:new Date().toISOString()}).eq('id',action.id).eq('user_id',context.userId);if(up.error)throw new Error(up.error.message);
 await notify({userId:context.userId,type:'agent.input_required',title,body:summary,link:'/mission-control',metadata:{approval_request_id:approval.id,construction_action_id:action.id,construction_run_id:run.id}});
 return{approval,reused:false as const};
});
