import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
type Sb={from:(t:string)=>any}; const uuid=z.string().uuid(); const opt=z.string().trim().max(8000).optional();
async function save(sb:Sb,table:string,userId:string,data:any){const{id,...v}=data;const row={...v,updated_at:new Date().toISOString()};const q=id?await sb.from(table).update(row).eq('id',id).eq('user_id',userId).select().single():await sb.from(table).insert({...row,user_id:userId}).select().single();if(q.error)throw new Error(q.error.message);return q.data;}
const field=z.object({id:uuid.optional(),workspace_id:uuid,project_id:uuid.nullish(),record_type:z.enum(['rams','permit','incident','near_miss','ncr','snag','rfi','toolbox_talk','daily_diary','handover']),title:z.string().trim().min(1).max(240),reference:z.string().max(100).optional(),status:z.enum(['draft','open','submitted','approved','rejected','in_progress','resolved','closed']).default('open'),risk_level:z.enum(['low','medium','high','critical']).default('medium'),description:opt,responsible_person:z.string().max(180).optional(),due_at:z.string().datetime({offset:true}).nullish()});
const partner=z.object({id:uuid.optional(),workspace_id:uuid,partner_type:z.enum(['subcontractor','supplier','consultant','client','manufacturer','hire_company','other']),name:z.string().trim().min(1).max(220),contact_name:z.string().max(180).optional(),email:z.string().email().optional().or(z.literal('')),phone:z.string().max(80).optional(),trade:z.string().max(160).optional(),status:z.enum(['prospect','approved','active','suspended','inactive']).default('active'),notes:opt});
const material=z.object({id:uuid.optional(),workspace_id:uuid,project_id:uuid.nullish(),supplier_id:uuid.nullish(),name:z.string().trim().min(1).max(220),sku:z.string().max(120).optional(),unit:z.string().max(40).default('each'),required_qty:z.coerce.number().min(0).default(0),ordered_qty:z.coerce.number().min(0).default(0),delivered_qty:z.coerce.number().min(0).default(0),used_qty:z.coerce.number().min(0).default(0),unit_cost:z.coerce.number().min(0).default(0),lead_time_days:z.coerce.number().int().min(0).nullish(),required_by:z.string().nullish(),expected_delivery:z.string().nullish(),status:z.enum(['required','quoted','ordered','part_delivered','delivered','shortage','cancelled']).default('required'),notes:opt});
const work=z.object({id:uuid.optional(),workspace_id:uuid,project_id:uuid,partner_id:uuid.nullish(),name:z.string().trim().min(1).max(220),trade:z.string().max(160).optional(),status:z.enum(['planned','ready','in_progress','blocked','complete','cancelled']).default('planned'),planned_start:z.string().nullish(),planned_finish:z.string().nullish(),percent_complete:z.coerce.number().min(0).max(100).default(0),budget:z.coerce.number().min(0).default(0),committed_cost:z.coerce.number().min(0).default(0),actual_cost:z.coerce.number().min(0).default(0),notes:opt});
const change=z.object({id:uuid.optional(),workspace_id:uuid,project_id:uuid,reference:z.string().max(100).optional(),title:z.string().trim().min(1).max(220),change_type:z.enum(['variation','change_order','compensation_event','claim','forecast_adjustment','other']).default('variation'),status:z.enum(['draft','submitted','under_review','approved','rejected','implemented','closed']).default('draft'),description:opt,cost_impact:z.coerce.number().default(0),time_impact_days:z.coerce.number().int().default(0),approved_by:z.string().max(180).optional()});
export const getConstructionControl=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({workspace_id:uuid}).parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const tables=['construction_field_records','construction_partners','construction_materials','construction_work_packages','construction_changes'];const qs=await Promise.all(tables.map(t=>sb.from(t).select('*').eq('workspace_id',data.workspace_id).order('updated_at',{ascending:false}).limit(400)));const bad=qs.find((x:any)=>x.error)?.error;if(bad)throw new Error(bad.message);const[fieldRecords,partners,materials,workPackages,changes]=qs.map((x:any)=>x.data??[]);return{fieldRecords,partners,materials,workPackages,changes,signals:{highRisk:fieldRecords.filter((x:any)=>['high','critical'].includes(x.risk_level)&&!['resolved','closed','approved'].includes(x.status)),openPermits:fieldRecords.filter((x:any)=>x.record_type==='permit'&&!['closed','approved'].includes(x.status)),supplyShortages:materials.filter((x:any)=>x.status==='shortage'||x.delivered_qty<x.required_qty&&x.required_by&&new Date(x.required_by).getTime()<Date.now()+7*86400000),blockedPackages:workPackages.filter((x:any)=>x.status==='blocked'),pendingChanges:changes.filter((x:any)=>['submitted','under_review'].includes(x.status)),commercialExposure:changes.filter((x:any)=>!['rejected','closed'].includes(x.status)).reduce((n:number,x:any)=>n+Number(x.cost_impact||0),0)}};});
export const saveConstructionFieldRecord=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>field.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_field_records',context.userId,data));
export const saveConstructionPartner=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>partner.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_partners',context.userId,data));
export const saveConstructionMaterial=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>material.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_materials',context.userId,data));
export const saveConstructionWorkPackage=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>work.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_work_packages',context.userId,data));
export const saveConstructionChange=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>change.parse(v)).handler(async({data,context})=>save(context.supabase as unknown as Sb,'construction_changes',context.userId,data));
