import { useEffect, useState } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { FileUp, Loader2, Stethoscope, Sparkles } from 'lucide-react';
import { friendlyMessage } from '@/lib/errors';
import { generateAppointmentBrief, getHealthImportsBriefs, importHealthMetrics } from '@/lib/health/health-imports-briefs.functions';

const samples={
 csv:'weight,82.4,kg,2026-09-14T08:00:00+01:00\nsteps,8400,steps,2026-09-14T22:00:00+01:00',
 json:'[{"metric_type":"weight","value":82.4,"unit":"kg","recorded_at":"2026-09-14T08:00:00+01:00"}]',
};
function parseRows(text,format){
 if(format==='json'){const v=JSON.parse(text);if(!Array.isArray(v))throw new Error('JSON import must be an array.');return v;}
 return text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const [metric_type,value,unit,recorded_at,...notes]=line.split(',').map(x=>x.trim());return{metric_type,value:Number(value),unit,recorded_at,notes:notes.join(', ')||undefined};});
}

export default function HealthImportsBriefs(){
 const getFn=useServerFn(getHealthImportsBriefs),importFn=useServerFn(importHealthMetrics),briefFn=useServerFn(generateAppointmentBrief);
 const [data,setData]=useState({imports:[],briefs:[]}),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const [format,setFormat]=useState('csv'),[source,setSource]=useState('csv'),[raw,setRaw]=useState(samples.csv);
 const [brief,setBrief]=useState({title:'Appointment preparation',appointment_date:'',clinician_or_service:'',focus:''});
 async function load(){try{setData(await getFn({data:undefined}));}catch(e){setError(friendlyMessage(e));}}
 useEffect(()=>{load();},[]);
 async function doImport(){setBusy('import');setError('');try{const rows=parseRows(raw,format);await importFn({data:{source_type:source,filename:`manual.${format}`,rows}});await load();}catch(e){setError(friendlyMessage(e));}finally{setBusy('');}}
 async function makeBrief(){if(!brief.focus.trim())return;setBusy('brief');setError('');try{await briefFn({data:brief});await load();setBrief({...brief,focus:''});}catch(e){setError(friendlyMessage(e));}finally{setBusy('');}}
 return <div className="grid gap-4 xl:grid-cols-2">
  <section className="rounded-[24px] border border-white/[.07] bg-white/[.025] p-4 sm:p-5"><div className="flex items-center gap-2"><FileUp className="h-4 w-4 text-violet-300"/><h2 className="text-sm font-semibold text-white">Health data import</h2></div><p className="mt-1 text-[10px] leading-5 text-zinc-600">Import normalized metrics from exports. Direct wearable account sync remains connector-dependent; Blackstar does not claim a live Apple Health, Health Connect, Fitbit, Garmin or Oura connection until one is configured.</p>{error&&<p className="mt-3 text-xs text-rose-300">{error}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><select className="hib-field" value={format} onChange={e=>{setFormat(e.target.value);setRaw(samples[e.target.value]||'')}}><option value="csv">CSV rows</option><option value="json">JSON array</option></select><select className="hib-field" value={source} onChange={e=>setSource(e.target.value)}>{['csv','json','apple_health_export','health_connect_export','fitbit_export','garmin_export','oura_export','other'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></div><textarea className="hib-field mt-2 min-h-44 resize-y font-mono text-[10px]" value={raw} onChange={e=>setRaw(e.target.value)}/><button onClick={doImport} disabled={busy==='import'||!raw.trim()} className="hib-primary mt-3">{busy==='import'?<Loader2 className="h-4 w-4 animate-spin"/>:<FileUp className="h-4 w-4"/>}Validate & import</button><div className="mt-4 space-y-2">{data.imports.slice(0,8).map(x=><div key={x.id} className="rounded-xl border border-white/[.06] bg-black/20 p-3 text-[10px] text-zinc-500"><span className="text-zinc-300">{x.source_type.replaceAll('_',' ')}</span> · {x.imported_rows} imported · {new Date(x.created_at).toLocaleString()}</div>)}</div></section>
  <section className="rounded-[24px] border border-white/[.07] bg-white/[.025] p-4 sm:p-5"><div className="flex items-center gap-2"><Stethoscope className="h-4 w-4 text-violet-300"/><h2 className="text-sm font-semibold text-white">Appointment prep</h2></div><p className="mt-1 text-[10px] leading-5 text-zinc-600">Turn your own logs and records into a factual clinician-ready briefing: changes, questions and records to bring—without diagnosis or prescribing.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><input className="hib-field" value={brief.title} onChange={e=>setBrief({...brief,title:e.target.value})} placeholder="Appointment title"/><input className="hib-field" type="date" value={brief.appointment_date} onChange={e=>setBrief({...brief,appointment_date:e.target.value})}/><input className="hib-field sm:col-span-2" value={brief.clinician_or_service} onChange={e=>setBrief({...brief,clinician_or_service:e.target.value})} placeholder="GP, physiotherapist, dietitian…"/><textarea className="hib-field min-h-28 resize-none sm:col-span-2" value={brief.focus} onChange={e=>setBrief({...brief,focus:e.target.value})} placeholder="What do you want to discuss or make sure you cover?"/></div><button onClick={makeBrief} disabled={busy==='brief'||!brief.focus.trim()} className="hib-primary mt-3">{busy==='brief'?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}Build brief</button><div className="mt-4 space-y-3">{data.briefs.slice(0,6).map(x=>{const b=x.brief||{};return <div key={x.id} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="flex justify-between gap-2"><p className="text-xs font-medium text-zinc-200">{x.title}</p><span className="text-[9px] text-zinc-600">{x.appointment_date||'No date'}</span></div><p className="mt-2 text-[10px] leading-5 text-zinc-400">{b.summary}</p>{Array.isArray(b.questions)&&b.questions.length>0&&<div className="mt-2"><p className="text-[9px] uppercase tracking-wider text-violet-300">Questions</p><ul className="mt-1 space-y-1 text-[10px] text-zinc-500">{b.questions.slice(0,8).map((q,i)=><li key={i}>• {q}</li>)}</ul></div>}</div>})}</div></section>
  <style>{`.hib-field{width:100%;border:1px solid rgba(255,255,255,.09);background:rgba(0,0,0,.28);border-radius:.75rem;padding:.62rem .72rem;font-size:.75rem;color:white;outline:none}.hib-field option{background:#11131a}.hib-primary{display:inline-flex;align-items:center;gap:.5rem;border-radius:.75rem;background:rgb(196 181 253);padding:.65rem .9rem;font-size:.75rem;font-weight:600;color:#050505}.hib-primary:disabled{opacity:.4}`}</style>
 </div>
}
