import { useEffect,useState } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { Activity, BarChart3, Dumbbell, Moon, Salad, Target, TrendingUp } from 'lucide-react';
import { getHealthAnalytics } from '@/lib/health/health-analytics.functions';
import { friendlyMessage } from '@/lib/errors';

export default function HealthIntelligenceDashboard(){
 const getFn=useServerFn(getHealthAnalytics);const [d,setD]=useState(null),[error,setError]=useState('');
 useEffect(()=>{getFn({data:undefined}).then(setD).catch(e=>setError(friendlyMessage(e)));},[]);
 if(error)return <div className="rounded-xl border border-rose-400/20 bg-rose-500/10 p-3 text-xs text-rose-200">{error}</div>;
 if(!d)return <div className="rounded-2xl border border-white/[.07] p-8 text-center text-xs text-zinc-600">Building your private health intelligence view…</div>;
 const cards=[[Dumbbell,'Workouts · 7d',d.training.workouts7],[Activity,'Training minutes · 30d',d.training.durationMinutes30],[Moon,'Avg sleep · 7d',d.recovery.averageSleepHours7==null?'—':d.recovery.averageSleepHours7+'h'],[Salad,'Nutrition logged · 7d',d.nutrition.loggedDays7+'/7'],[Target,'Active goals',d.goals.length]];
 return <div className="space-y-4">
  <div className="rounded-xl border border-cyan-300/10 bg-cyan-300/[.025] p-3 text-[10px] leading-5 text-zinc-500">Health Intelligence summarizes your own logs. Trends and overlaps are descriptive only and must not be interpreted as diagnoses, causes or medical predictions.</div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([Icon,label,value])=><div key={label} className="rounded-2xl border border-white/[.07] bg-black/25 p-4"><Icon className="h-4 w-4 text-violet-300"/><div className="mt-3 text-xl font-semibold text-white">{value}</div><div className="mt-1 text-[9px] uppercase tracking-wider text-zinc-600">{label}</div></div>)}</div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel icon={TrendingUp} title="90-day trends"><div className="grid gap-2 sm:grid-cols-2">{Object.entries(d.trends).map(([key,t])=><div key={key} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="text-[9px] uppercase tracking-wider text-zinc-600">{key.replace(/([A-Z])/g,' $1')}</div>{t?<><div className="mt-2 text-sm text-zinc-200">{t.last} {t.unit}</div><div className="mt-1 text-[10px] text-zinc-500">{t.change>0?'+':''}{t.change} {t.unit} across logged window</div><Spark points={t.points}/></>:<div className="mt-4 text-xs text-zinc-700">Need at least 2 logged points.</div>}</div>)}</div></Panel>
  <Panel icon={Target} title="Goal progress"><div className="space-y-2">{d.goals.length?d.goals.map(g=><div key={g.id} className="rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="flex justify-between gap-2"><span className="text-xs text-zinc-200">{g.title}</span><span className="text-[9px] text-violet-300">{g.category}</span></div><p className="mt-1 text-[10px] text-zinc-600">{g.latest==null?'No directly matching metric yet':`Latest ${g.latest} ${g.unit||''} · target ${g.target} ${g.unit||''}`}</p></div>):<Empty text="No active goals."/>}</div></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel icon={Moon} title="Recovery"><p className="text-2xl font-semibold text-white">{d.recovery.averageSleepHours7??'—'}<span className="ml-1 text-xs font-normal text-zinc-600">hours average</span></p><p className="mt-2 text-xs text-zinc-500">{d.recovery.nights7} nights logged · quality {d.recovery.averageQuality7??'—'}/10</p></Panel><Panel icon={Salad} title="Nutrition consistency"><p className="text-2xl font-semibold text-white">{d.nutrition.averageProteinLoggedDay7??'—'}<span className="ml-1 text-xs font-normal text-zinc-600">g protein / logged day</span></p><p className="mt-2 text-xs text-zinc-500">{d.nutrition.entries7} entries across {d.nutrition.loggedDays7} days</p></Panel></div>
  <Panel icon={BarChart3} title="Explainable observations"><div className="space-y-2">{d.observations.length?d.observations.map((x,i)=><div key={i} className="rounded-xl border border-white/[.06] bg-black/20 p-3 text-[11px] leading-5 text-zinc-400">{x}</div>):<Empty text="No notable cross-log observations yet. More consistent logging will improve this view."/>}</div></Panel>
 </div>
}
function Spark({points}){if(!points?.length)return null;const vals=points.map(p=>p.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const path=points.map((p,i)=>`${i?'L':'M'} ${(i/(points.length-1||1))*100} ${28-((p.value-min)/range)*24}`).join(' ');return <svg viewBox="0 0 100 32" className="mt-2 h-8 w-full overflow-visible"><path d={path} fill="none" stroke="currentColor" strokeWidth="1.5" className="text-violet-300"/></svg>}
function Panel({icon:Icon,title,children}){return <section className="rounded-[24px] border border-white/[.07] bg-white/[.025] p-4 sm:p-5"><div className="mb-4 flex items-center gap-2"><Icon className="h-4 w-4 text-violet-300"/><h2 className="text-sm font-semibold text-white">{title}</h2></div>{children}</section>}
function Empty({text}){return <div className="rounded-xl border border-dashed border-white/[.07] p-6 text-center text-xs text-zinc-600">{text}</div>}
