import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
import { writeAudit } from '@/lib/platform/audit.server';
type Sb={from:(table:string)=>any};
const reminder=z.object({reminder_type:z.enum(['workout','nutrition','hydration','sleep','medication','appointment','measurement','habit','other']),title:z.string().trim().min(1).max(180),notes:z.string().trim().max(2000).optional(),scheduled_for:z.string().datetime({offset:true}),recurrence:z.enum(['none','daily','weekly','monthly']).default('none')});
export const getHealthReminders=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const sb=context.supabase as unknown as Sb;const {data,error}=await sb.from('health_reminders').select('*').eq('user_id',context.userId).neq('status','archived').order('scheduled_for',{ascending:true}).limit(200);if(error)throw new Error(error.message);return data??[];});
export const createHealthReminder=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>reminder.parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const {data:row,error}=await sb.from('health_reminders').insert({user_id:context.userId,...data,notes:data.notes||null}).select('*').single();if(error)throw new Error(error.message);await writeAudit({userId:context.userId,action:'health.reminder_created',targetType:'health_reminder',targetId:row.id,status:'success',metadata:{type:data.reminder_type,recurrence:data.recurrence}});return row;});
export const updateHealthReminderStatus=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>z.object({id:z.string().uuid(),status:z.enum(['active','completed','dismissed','archived'])}).parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;const {data:row,error}=await sb.from('health_reminders').update({status:data.status,updated_at:new Date().toISOString()}).eq('id',data.id).eq('user_id',context.userId).select('*').single();if(error)throw new Error(error.message);return row;});
