import { useState } from 'react';
import { Download, Eye, FileText, Printer, X } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

function slug(value) {
  return String(value || 'palladium-document')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 70) || 'palladium-document';
}

function downloadBlob(content, name, type) {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = name;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function escapeHtml(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function wordDocument(title, markdown) {
  const body = escapeHtml(markdown)
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^[-*] (.+)$/gm, '<p>• $1</p>')
    .replace(/\n/g, '<br/>');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>body{font-family:Arial,sans-serif;line-height:1.55;color:#111827;max-width:900px;margin:48px auto;padding:0 32px}h1,h2,h3{color:#111827}h1{font-size:28px}h2{font-size:21px;margin-top:28px}h3{font-size:17px;margin-top:22px}strong{font-weight:700}</style></head><body><h1>${escapeHtml(title)}</h1>${body}</body></html>`;
}

export default function GeneratedDocumentCard({ title, content, kind = 'document' }) {
  const [open, setOpen] = useState(false);
  const safeTitle = title || 'Generated document';
  const filename = slug(safeTitle);

  const downloadDocument = () => downloadBlob(
    wordDocument(safeTitle, content),
    `${filename}.doc`,
    'application/msword;charset=utf-8',
  );

  const printDocument = () => {
    if (typeof window === 'undefined') return;
    const popup = window.open('', '_blank', 'noopener,noreferrer');
    if (!popup) return;
    popup.document.open();
    popup.document.write(wordDocument(safeTitle, content));
    popup.document.close();
    popup.focus();
    setTimeout(() => popup.print(), 250);
  };

  return (
    <>
      <div className="mt-2 rounded-xl border border-violet-400/20 bg-gradient-to-br from-violet-500/[.09] to-cyan-500/[.04] p-3.5">
        <div className="flex items-start gap-3">
          <div className="rounded-xl border border-violet-400/20 bg-violet-500/10 p-2.5"><FileText className="h-5 w-5 text-violet-200" /></div>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <p className="truncate text-[12px] font-semibold text-white">{safeTitle}</p>
              <span className="rounded-full border border-emerald-400/20 bg-emerald-500/10 px-2 py-0.5 text-[9px] font-medium uppercase tracking-wider text-emerald-200">Document ready</span>
            </div>
            <p className="mt-1 text-[10px] text-zinc-500">Generated by PalladiumAI · {kind.replace(/-/g, ' ')}</p>
          </div>
        </div>
        <div className="mt-3 grid gap-2 sm:grid-cols-3">
          <button type="button" onClick={() => setOpen(true)} className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-[10px] font-medium text-zinc-200 hover:bg-white/[.08]"><Eye className="h-3.5 w-3.5" />Preview</button>
          <button type="button" onClick={downloadDocument} className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-violet-400/25 bg-violet-500/10 px-3 py-2 text-[10px] font-medium text-violet-100 hover:bg-violet-500/15"><Download className="h-3.5 w-3.5" />Download document</button>
          <button type="button" onClick={printDocument} className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-[10px] font-medium text-zinc-200 hover:bg-white/[.08]"><Printer className="h-3.5 w-3.5" />Print / Save PDF</button>
        </div>
      </div>

      {open && (
        <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/75 p-3 backdrop-blur-sm sm:p-6" role="dialog" aria-modal="true" aria-label={safeTitle}>
          <div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-white/15 bg-[#0d0f17] shadow-2xl">
            <div className="flex items-center gap-3 border-b border-white/10 px-4 py-3 sm:px-5">
              <div className="rounded-lg bg-violet-500/10 p-2"><FileText className="h-4 w-4 text-violet-200" /></div>
              <div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{safeTitle}</p><p className="text-[10px] text-zinc-500">PalladiumAI generated document</p></div>
              <button type="button" onClick={downloadDocument} className="hidden items-center gap-1.5 rounded-lg border border-violet-400/25 bg-violet-500/10 px-3 py-2 text-[10px] font-medium text-violet-100 sm:inline-flex"><Download className="h-3.5 w-3.5" />Download</button>
              <button type="button" onClick={() => setOpen(false)} className="rounded-lg border border-white/10 p-2 text-zinc-400 hover:bg-white/5 hover:text-white"><X className="h-4 w-4" /></button>
            </div>
            <div className="overflow-y-auto bg-white p-5 text-slate-800 sm:p-8">
              <article className="prose prose-slate mx-auto max-w-3xl prose-headings:text-slate-950 prose-strong:text-slate-950 prose-table:text-sm"><ReactMarkdown>{content}</ReactMarkdown></article>
            </div>
            <div className="flex flex-wrap justify-end gap-2 border-t border-white/10 px-4 py-3">
              <button type="button" onClick={printDocument} className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-2 text-[10px] font-medium text-zinc-300 hover:bg-white/5"><Printer className="h-3.5 w-3.5" />Print / Save PDF</button>
              <button type="button" onClick={downloadDocument} className="inline-flex items-center gap-1.5 rounded-lg bg-violet-600 px-3 py-2 text-[10px] font-semibold text-white hover:bg-violet-500"><Download className="h-3.5 w-3.5" />Download .doc</button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
