/**
 * Salesforce CRM provider executor. Server-only and read-only.
 *
 * Uses the encrypted OAuth token and the validated tenant instance_url captured
 * during OAuth. Queries are generated by PalladiumAI; arbitrary SOQL is never
 * accepted from the model or browser.
 */
import {
  getIntegrationAccessToken,
  getIntegrationProviderConfig,
  normaliseSalesforceInstanceUrl,
} from "./oauth.server";

type FetchLike = typeof fetch;

export class SalesforceIntegrationError extends Error {
  constructor(message: string, public readonly status?: number) {
    super(message);
    this.name = "SalesforceIntegrationError";
  }
}

async function salesforceContext(userId: string): Promise<{ token: string; instanceUrl: string }> {
  const [token, config] = await Promise.all([
    getIntegrationAccessToken(userId, "salesforce"),
    getIntegrationProviderConfig(userId, "salesforce"),
  ]);
  if (!token) {
    throw new SalesforceIntegrationError(
      "Salesforce is not connected, or the connection needs to be renewed.",
      401,
    );
  }
  const instanceUrl = normaliseSalesforceInstanceUrl(config["instance_url"]);
  if (!instanceUrl) {
    throw new SalesforceIntegrationError(
      "Salesforce connection is missing its tenant API address. Reconnect Salesforce.",
      400,
    );
  }
  return { token, instanceUrl };
}

async function sfFetch(
  userId: string,
  path: string,
  init: RequestInit = {},
  fetchImpl: FetchLike = fetch,
): Promise<Response> {
  const { token, instanceUrl } = await salesforceContext(userId);
  const response = await fetchImpl(`${instanceUrl}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/json",
      ...(init.headers ?? {}),
    },
    signal: init.signal ?? AbortSignal.timeout(20_000),
  });
  if (response.ok) return response;

  let reason = "Salesforce CRM request failed.";
  try {
    const payload = (await response.json()) as any;
    if (Array.isArray(payload) && payload[0]?.message) reason = String(payload[0].message);
    else reason = String(payload?.message ?? payload?.error_description ?? payload?.error ?? reason);
  } catch {
    /* provider error body is optional */
  }
  throw new SalesforceIntegrationError(reason.slice(0, 300), response.status);
}

async function latestApiVersion(
  userId: string,
  signal?: AbortSignal,
  fetchImpl: FetchLike = fetch,
): Promise<string> {
  const response = await sfFetch(
    userId,
    "/services/data/",
    { method: "GET", ...(signal ? { signal } : {}) },
    fetchImpl,
  );
  const payload = (await response.json()) as any;
  const versions = Array.isArray(payload)
    ? payload
        .map((row: any) => String(row?.version ?? ""))
        .filter((value: string) => /^\d+\.\d+$/.test(value))
        .sort((a: string, b: string) => Number(b) - Number(a))
    : [];
  const version = versions[0];
  if (!version) throw new SalesforceIntegrationError("Salesforce did not return a supported REST API version.");
  return version;
}

function searchTerm(value: string): string {
  return String(value ?? "")
    .replace(/[\\'"%_\r\n\t]+/g, " ")
    .replace(/[^A-Za-z0-9 .,@&+()\-]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 200);
}

async function querySalesforce(
  userId: string,
  soql: string,
  signal?: AbortSignal,
  fetchImpl: FetchLike = fetch,
): Promise<any[]> {
  const version = await latestApiVersion(userId, signal, fetchImpl);
  const url = `/services/data/v${version}/query?q=${encodeURIComponent(soql)}`;
  const response = await sfFetch(
    userId,
    url,
    { method: "GET", ...(signal ? { signal } : {}) },
    fetchImpl,
  );
  const payload = (await response.json()) as any;
  return Array.isArray(payload?.records) ? payload.records : [];
}

export type SalesforceAccount = {
  id: string;
  name: string;
  industry: string | null;
  website: string | null;
  phone: string | null;
  billingCity: string | null;
  billingCountry: string | null;
  annualRevenue: number | null;
  type: string | null;
};

export async function searchSalesforceAccounts(args: {
  userId: string;
  query: string;
  limit?: number;
  signal?: AbortSignal;
  fetchImpl?: FetchLike;
}): Promise<SalesforceAccount[]> {
  const query = searchTerm(args.query);
  if (!query) throw new SalesforceIntegrationError("A Salesforce account search query is required.");
  const limit = Math.min(Math.max(Number(args.limit ?? 20) || 20, 1), 50);
  const soql =
    "SELECT Id,Name,Industry,Website,Phone,BillingCity,BillingCountry,AnnualRevenue,Type " +
    `FROM Account WHERE Name LIKE '%${query}%' ORDER BY LastModifiedDate DESC LIMIT ${limit}`;
  const records = await querySalesforce(args.userId, soql, args.signal, args.fetchImpl ?? fetch);
  return records.slice(0, limit).map((row: any) => ({
    id: String(row?.Id ?? ""),
    name: String(row?.Name ?? "Untitled account").slice(0, 300),
    industry: row?.Industry ? String(row.Industry).slice(0, 200) : null,
    website: row?.Website ? String(row.Website).slice(0, 500) : null,
    phone: row?.Phone ? String(row.Phone).slice(0, 100) : null,
    billingCity: row?.BillingCity ? String(row.BillingCity).slice(0, 200) : null,
    billingCountry: row?.BillingCountry ? String(row.BillingCountry).slice(0, 200) : null,
    annualRevenue: Number.isFinite(Number(row?.AnnualRevenue)) ? Number(row.AnnualRevenue) : null,
    type: row?.Type ? String(row.Type).slice(0, 200) : null,
  }));
}

export type SalesforceOpportunity = {
  id: string;
  name: string;
  stage: string | null;
  amount: number | null;
  probability: number | null;
  closeDate: string | null;
  accountName: string | null;
  type: string | null;
  nextStep: string | null;
};

export async function searchSalesforceOpportunities(args: {
  userId: string;
  query: string;
  limit?: number;
  signal?: AbortSignal;
  fetchImpl?: FetchLike;
}): Promise<SalesforceOpportunity[]> {
  const query = searchTerm(args.query);
  if (!query) throw new SalesforceIntegrationError("A Salesforce opportunity search query is required.");
  const limit = Math.min(Math.max(Number(args.limit ?? 20) || 20, 1), 50);
  const soql =
    "SELECT Id,Name,StageName,Amount,Probability,CloseDate,Account.Name,Type,NextStep " +
    `FROM Opportunity WHERE Name LIKE '%${query}%' ORDER BY LastModifiedDate DESC LIMIT ${limit}`;
  const records = await querySalesforce(args.userId, soql, args.signal, args.fetchImpl ?? fetch);
  return records.slice(0, limit).map((row: any) => ({
    id: String(row?.Id ?? ""),
    name: String(row?.Name ?? "Untitled opportunity").slice(0, 300),
    stage: row?.StageName ? String(row.StageName).slice(0, 200) : null,
    amount: Number.isFinite(Number(row?.Amount)) ? Number(row.Amount) : null,
    probability: Number.isFinite(Number(row?.Probability)) ? Number(row.Probability) : null,
    closeDate: row?.CloseDate ? String(row.CloseDate).slice(0, 100) : null,
    accountName: row?.Account?.Name ? String(row.Account.Name).slice(0, 300) : null,
    type: row?.Type ? String(row.Type).slice(0, 200) : null,
    nextStep: row?.NextStep ? String(row.NextStep).slice(0, 500) : null,
  }));
}
