export const LEGAL_TOPICS=[
["Business & corporate","Companies, governance, directors, beneficial ownership, insolvency and commercial obligations."],["Contracts & commerce","Contract formation, sale of goods, electronic commerce, arbitration, mediation and cross-border trade."],["Employment & labour","Employment terms, wages, working time, dismissal, equality, unions, workplace rights and safety."],["Privacy & data","Privacy, data protection, cybersecurity, breach duties, international transfers and digital identity."],["AI & technology","AI governance, automated decisions, platform regulation, online safety, software and emerging technology."],["Intellectual property","Copyright, patents, trade marks, designs, trade secrets, licensing and international IP treaties."],["Consumer law","Consumer rights, unfair terms, product safety, advertising, refunds and digital services."],["Tax & finance","Tax frameworks, financial services regulation, AML, sanctions, payments, securities and banking."],["Property & housing","Land, leases, tenancies, planning, construction and property transactions."],["Family & personal","Marriage, divorce, children, inheritance, wills, capacity and personal legal rights."],["Criminal & justice","Criminal law, procedure, evidence, courts, legal aid, extradition and mutual assistance."],["Human rights","Constitutional rights, equality, civil liberties, international human-rights instruments and remedies."],["Immigration & nationality","Visas, residence, citizenship, asylum, borders and mobility."],["Environment & energy","Environmental duties, climate regulation, energy, emissions, waste and natural resources."],["Health & life sciences","Healthcare regulation, medicines, medical devices, clinical research and health information."],["International law","Treaties, public international law, trade law, conflicts, state responsibility and international institutions."]
];
export const OFFICIAL_LEGAL_SOURCES=[
{region:"United Kingdom",name:"UK Legislation",url:"https://www.legislation.gov.uk/",kind:"Legislation"},{region:"United Kingdom",name:"Find Case Law",url:"https://caselaw.nationalarchives.gov.uk/",kind:"Case law"},{region:"United Kingdom",name:"UK Treaties Online",url:"https://treaties.fcdo.gov.uk/",kind:"Treaties"},{region:"European Union",name:"EUR-Lex",url:"https://eur-lex.europa.eu/",kind:"EU law & treaties"},{region:"European Union",name:"European e-Justice",url:"https://e-justice.europa.eu/",kind:"National law & justice"},{region:"United States",name:"Congress.gov",url:"https://www.congress.gov/",kind:"Federal legislation"},{region:"United States",name:"Federal Register",url:"https://www.federalregister.gov/",kind:"Rules & regulations"},{region:"United States",name:"U.S. Code",url:"https://uscode.house.gov/",kind:"Codified federal law"},{region:"Canada",name:"Justice Laws Website",url:"https://laws-lois.justice.gc.ca/",kind:"Federal law"},{region:"Canada",name:"Canada Treaty Information",url:"https://www.treaty-accord.gc.ca/",kind:"Treaties"},{region:"Australia",name:"Federal Register of Legislation",url:"https://www.legislation.gov.au/",kind:"Commonwealth law"},{region:"Australia",name:"Australian Treaties Database",url:"https://www.dfat.gov.au/international-relations/treaties/australian-treaties-database",kind:"Treaties"},{region:"New Zealand",name:"New Zealand Legislation",url:"https://www.legislation.govt.nz/",kind:"Legislation"},{region:"New Zealand",name:"New Zealand Treaties Online",url:"https://www.treaties.mfat.govt.nz/",kind:"Treaties"},
{region:"France",name:"Légifrance",url:"https://www.legifrance.gouv.fr/",kind:"Legislation, codes & official legal publication"},
{region:"Germany",name:"Gesetze im Internet",url:"https://www.gesetze-im-internet.de/",kind:"Consolidated federal legislation"},{region:"Germany",name:"Federal Law Gazette",url:"https://www.recht.bund.de/",kind:"Official federal promulgation"},
{region:"Ireland",name:"Irish Statute Book",url:"https://www.irishstatutebook.ie/",kind:"Legislation & statutory instruments"},
{region:"Spain",name:"BOE",url:"https://www.boe.es/",kind:"Official gazette & legislation"},
{region:"Italy",name:"Normattiva",url:"https://www.normattiva.it/",kind:"Legislation"},
{region:"Switzerland",name:"Fedlex",url:"https://www.fedlex.admin.ch/",kind:"Federal law & official publications"},
{region:"Singapore",name:"Singapore Statutes Online",url:"https://sso.agc.gov.sg/",kind:"Legislation"},{region:"Singapore",name:"Singapore Courts Judgments",url:"https://www.judiciary.gov.sg/judgments",kind:"Case law"},
{region:"Japan",name:"e-Gov Law Search",url:"https://elaws.e-gov.go.jp/",kind:"Legislation"},{region:"Japan",name:"Supreme Court of Japan Judgments",url:"https://www.courts.go.jp/english/Judgments/",kind:"Case law"},
{region:"South Korea",name:"Korean Law Information Center",url:"https://www.law.go.kr/",kind:"Legislation"},{region:"South Korea",name:"Supreme Court of Korea",url:"https://www.scourt.go.kr/eng/",kind:"Court materials"},
{region:"India",name:"India Code",url:"https://www.indiacode.nic.in/",kind:"Union legislation"},{region:"India",name:"Supreme Court of India",url:"https://www.sci.gov.in/",kind:"Judgments & court materials"},
{region:"Hong Kong",name:"Hong Kong e-Legislation",url:"https://www.elegislation.gov.hk/",kind:"Legislation"},{region:"Hong Kong",name:"Hong Kong Judiciary",url:"https://www.judiciary.hk/",kind:"Court materials"},
{region:"Brazil",name:"Portal da Legislação",url:"https://www4.planalto.gov.br/legislacao",kind:"Federal legislation"},
{region:"Mexico",name:"Leyes Federales de México",url:"https://www.diputados.gob.mx/LeyesBiblio/index.htm",kind:"Federal-law compilation"},
{region:"South Africa",name:"South African Government Acts",url:"https://www.gov.za/documents/acts",kind:"Acts"},{region:"South Africa",name:"Parliament of South Africa Acts",url:"https://www.parliament.gov.za/acts",kind:"Acts"},
{region:"Kenya",name:"Kenya Law",url:"https://new.kenyalaw.org/",kind:"Consolidated laws, gazette & case law"},
{region:"United Arab Emirates",name:"UAE Legislation",url:"https://uaelegislation.gov.ae/en",kind:"Federal legislation & policies"},
{region:"Saudi Arabia",name:"Bureau of Experts Laws",url:"https://laws.boe.gov.sa/",kind:"Laws & regulations"},
{region:"International",name:"UN Treaty Collection",url:"https://treaties.un.org/",kind:"Treaties"},{region:"International",name:"UNCITRAL",url:"https://uncitral.un.org/en/texts",kind:"International commercial law"},{region:"International",name:"WIPO Lex",url:"https://www.wipo.int/wipolex/",kind:"IP laws, treaties & judgments"},{region:"International",name:"WTO Legal Texts",url:"https://www.wto.org/english/docs_e/legal_e/legal_e.htm",kind:"Trade law"},{region:"International",name:"ILO NORMLEX",url:"https://normlex.ilo.org/",kind:"Labour standards"},{region:"International",name:"OHCHR",url:"https://www.ohchr.org/en/instruments-and-mechanisms/international-human-rights-law",kind:"Human rights law"}
];
