import { hostMatchesCaseLawSource } from "./case-law-sources";

export const JURISDICTION_COVERAGE_TIERS={
source_discovery:{label:"Source discovery",description:"Verified official entry points are mapped, but additional source discovery is required before broad legal research."},
structured_profile:{label:"Structured profile",description:"Official sources, legal-system context and authority layers are curated, with issue-specific verification still required."},
research_ready:{label:"Research ready",description:"Multiple verified official research entry points and authority context are mapped for live research, subject to currentness and applicability checks."}
} as const;
const REVIEWED_ON="2026-09-13";

export const JURISDICTIONS=[
{id:"uk",name:"United Kingdom",region:"Europe",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common law with devolved legal systems",levels:["UK Parliament","Devolved legislatures","Secondary legislation","Courts"],primary:["https://www.legislation.gov.uk/","https://caselaw.nationalarchives.gov.uk/"],officialHosts:["legislation.gov.uk","caselaw.nationalarchives.gov.uk"],notes:"Check whether the issue falls under England & Wales, Scotland or Northern Ireland and whether competence is devolved."},
{id:"ie",name:"Ireland",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Common-law constitutional parliamentary system",levels:["Constitution","Acts of the Oireachtas","Statutory instruments","Courts","EU law where applicable"],primary:["https://www.irishstatutebook.ie/"],officialHosts:["irishstatutebook.ie"],notes:"Use the electronic Irish Statute Book as a research starting point, but note that the official versions remain the printed versions published by Government Publications; also check applicable EU law and current amendments."},
{id:"eu",name:"European Union",region:"Europe",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Supranational legal order",levels:["EU treaties","Regulations","Directives","Decisions","CJEU case law"],primary:["https://eur-lex.europa.eu/","https://curia.europa.eu/"],officialHosts:["eur-lex.europa.eu","curia.europa.eu"],notes:"Determine whether EU law applies directly, requires national implementation, or interacts with member-state law."},
{id:"fr",name:"France",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Civil-law constitutional system",levels:["Constitutional norms","Codes and statutes","Regulations","Administrative law","Courts"],primary:["https://www.legifrance.gouv.fr/"],officialHosts:["legifrance.gouv.fr"],notes:"Start with current consolidated legislation on Légifrance and distinguish statutory, regulatory, constitutional and administrative sources."},
{id:"de",name:"Germany",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law constitutional system",levels:["Basic Law","Federal statutes","Federal regulations","Land law","Courts","EU law where applicable"],primary:["https://www.gesetze-im-internet.de/","https://www.recht.bund.de/"],officialHosts:["gesetze-im-internet.de","recht.bund.de"],notes:"Identify federal versus Land competence and check EU-law interaction. Gesetze im Internet is a research copy of federal statutes and regulations; the electronic Federal Law Gazette is the official federal promulgation source."},
{id:"es",name:"Spain",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Decentralised civil-law constitutional system",levels:["Constitution","State legislation","Autonomous-community law","Regulations","Constitutional and ordinary courts"],primary:["https://www.boe.es/"],officialHosts:["boe.es"],notes:"Identify state versus autonomous-community competence. BOE consolidated texts aid research, but BOE states consolidated versions are informational rather than the official promulgated text."},
{id:"it",name:"Italy",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Civil-law constitutional republic",levels:["Constitution","Primary legislation","Legislative decrees and regulations","Regional law","Constitutional and ordinary courts"],primary:["https://www.normattiva.it/"],officialHosts:["normattiva.it"],notes:"Check the version in force, amendments and effective dates on Normattiva, then identify relevant constitutional, ordinary or administrative-court authority."},
{id:"ch",name:"Switzerland",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law system",levels:["Federal Constitution","Federal acts","Ordinances","Cantonal law","Courts"],primary:["https://www.fedlex.admin.ch/"],officialHosts:["fedlex.admin.ch"],notes:"Separate federal and cantonal law and verify the language/version in force. English material may be unofficial and should not replace the authoritative language text."},
{id:"us",name:"United States",region:"North America",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Federal system with federal and state law",levels:["Constitution","Federal statutes","Federal regulations","State law","Federal/state courts"],primary:["https://www.congress.gov/","https://uscode.house.gov/","https://www.federalregister.gov/"],officialHosts:["congress.gov","uscode.house.gov","federalregister.gov"],notes:"Identify the relevant state and whether federal law pre-empts, supplements or leaves the issue to state law."},
{id:"ca",name:"Canada",region:"North America",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal bijural system",levels:["Constitution","Federal statutes","Provincial/territorial law","Regulations","Courts"],primary:["https://laws-lois.justice.gc.ca/"],officialHosts:["laws-lois.justice.gc.ca"],notes:"Identify whether jurisdiction lies with the federal government or a province/territory; Quebec private law differs from common-law provinces."},
{id:"mx",name:"Mexico",region:"Latin America",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Federal civil-law constitutional system",levels:["Constitution","Federal statutes","Federal regulations","State law","Courts"],primary:["https://dof.gob.mx/","https://www.diputados.gob.mx/LeyesBiblio/index.htm"],officialHosts:["dof.gob.mx","diputados.gob.mx"],notes:"Use the Diario Oficial de la Federación for official federal publication. Chamber of Deputies compilations are useful for research but state that they are informational; also identify relevant state law."},
{id:"br",name:"Brazil",region:"Latin America",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law constitutional system",levels:["Federal Constitution","Complementary and ordinary laws","Provisional measures","Decrees","State/municipal law","Courts"],primary:["https://www4.planalto.gov.br/legislacao"],officialHosts:["planalto.gov.br"],notes:"Separate federal, state and municipal competence and verify consolidation, amendments and effective dates in authoritative publication sources."},
{id:"au",name:"Australia",region:"Asia-Pacific",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal common-law system",levels:["Constitution","Commonwealth legislation","State/territory law","Regulations","Courts"],primary:["https://www.legislation.gov.au/"],officialHosts:["legislation.gov.au"],notes:"Check Commonwealth versus state/territory competence and the relevant regulator or tribunal."},
{id:"nz",name:"New Zealand",region:"Asia-Pacific",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Common-law parliamentary system",levels:["Acts","Secondary legislation","Courts","Regulators"],primary:["https://www.legislation.govt.nz/"],officialHosts:["legislation.govt.nz"],notes:"Start with current consolidated legislation and then verify relevant court and regulator materials."},
{id:"in",name:"India",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Federal common-law constitutional system",levels:["Constitution","Central Acts","Subordinate legislation","State law","Courts"],primary:["https://www.indiacode.nic.in/","https://www.sci.gov.in/"],officialHosts:["indiacode.nic.in","sci.gov.in"],notes:"Identify Union versus State competence and verify rules, regulations, notifications and commencement as well as the parent Act. Use original Supreme Court or relevant High Court decisions rather than summaries alone."},
{id:"sg",name:"Singapore",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common-law parliamentary system",levels:["Constitution","Acts","Subsidiary legislation","Courts"],primary:["https://sso.agc.gov.sg/","https://www.judiciary.gov.sg/judgments"],officialHosts:["sso.agc.gov.sg","judiciary.gov.sg"],notes:"Use Singapore Statutes Online for current Acts and subsidiary legislation, then check commencement, amendments and official judicial authority."},
{id:"hk",name:"Hong Kong SAR",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common-law system under the Basic Law",levels:["Basic Law","Ordinances","Subsidiary legislation","Courts"],primary:["https://www.elegislation.gov.hk/","https://www.judiciary.hk/"],officialHosts:["elegislation.gov.hk","judiciary.hk"],notes:"For Hong Kong e-Legislation, distinguish verified PDF copies with legal status from HTML/RTF reference versions and confirm the version date in force; verify appellate history through official Judiciary material."},
{id:"jp",name:"Japan",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Civil-law constitutional system",levels:["Constitution","Acts","Cabinet orders","Ministerial ordinances","Courts"],primary:["https://elaws.e-gov.go.jp/","https://www.japaneselawtranslation.go.jp/","https://www.courts.go.jp/english/Judgments/"],officialHosts:["elaws.e-gov.go.jp","japaneselawtranslation.go.jp","courts.go.jp"],notes:"Use e-Gov Law Search for Japanese legal text. English translations on Japanese Law Translation and the Supreme Court English site are reference materials only; only the original Japanese text has legal effect."},
{id:"kr",name:"South Korea",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Civil-law constitutional system",levels:["Constitution","Acts","Presidential decrees","Ministerial ordinances","Courts"],primary:["https://law.go.kr/eng/engMain.do","https://www.scourt.go.kr/eng/"],officialHosts:["law.go.kr","scourt.go.kr"],notes:"Use the Korean Law Information Center as a primary research portal and official judiciary sources for court materials; verify the Korean text, amendment history and enforcement date for any proposition."},
{id:"za",name:"South Africa",region:"Africa",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Constitutional mixed legal system",levels:["Constitution","Acts of Parliament","Regulations","Provincial law","Courts"],primary:["https://www.gov.za/documents-categories/acts","https://www.parliament.gov.za/acts"],officialHosts:["gov.za","parliament.gov.za"],notes:"Check the Constitution, national legislation, regulations and any applicable provincial law. Government and Parliament act listings are research starting points; verify current amendments and commencement."},
{id:"ke",name:"Kenya",region:"Africa",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common-law constitutional system with customary-law interaction",levels:["Constitution","Acts of Parliament","Subsidiary legislation","Supreme Court and superior courts"],primary:["https://new.kenyalaw.org/","https://judiciary.go.ke/"],officialHosts:["kenyalaw.org","judiciary.go.ke"],notes:"Kenya Law is the National Council for Law Reporting and official source for Law Reports and consolidated Laws of Kenya. Verify version dates, Gazette material and the deciding court through official judiciary sources."},
{id:"ae",name:"United Arab Emirates",region:"Middle East",coverageTier:"source_discovery",reviewedOn:REVIEWED_ON,system:"Federal civil-law system with Sharia influences and emirate-level law",levels:["Constitution","Federal laws","Executive regulations","Cabinet resolutions","Emirate-level law","Courts"],primary:["https://uaelegislation.gov.ae/en"],officialHosts:["uaelegislation.gov.ae"],notes:"The UAE Legislation platform covers federal legislation. Identify whether emirate-level rules or free-zone regimes also apply and verify Arabic text, amendments and effective dates where relevant."},
{id:"sa",name:"Saudi Arabia",region:"Middle East",coverageTier:"source_discovery",reviewedOn:REVIEWED_ON,system:"Sharia-based legal system with codified laws and regulations",levels:["Basic Law and foundational instruments","Royal decrees and laws","Council of Ministers regulations","Implementing regulations","Courts and judicial bodies"],primary:["https://laws.boe.gov.sa/"],officialHosts:["laws.boe.gov.sa","boe.gov.sa"],notes:"Use the Bureau of Experts legal-document portal for Saudi laws and regulations, verify amendments and implementing rules, and account for Sharia principles and specialist jurisdiction where relevant."},
{id:"intl",name:"International",region:"International",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Treaty and customary international law framework",levels:["Treaties","Customary international law","Institutional rules","International tribunals"],primary:["https://treaties.un.org/","https://www.icj-cij.org/"],officialHosts:["treaties.un.org","icj-cij.org"],notes:"Confirm treaty status, reservations, territorial application and whether the instrument is binding on the states involved."},
{id:"ip",name:"International IP",region:"International",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Treaty-based and national IP systems",levels:["WIPO treaties","National statutes","Regional systems","Courts/offices"],primary:["https://www.wipo.int/wipolex/"],officialHosts:["wipo.int"],notes:"IP rights are territorial. Identify the country or regional right, registration status and applicable treaty framework."}
] as const;

export const AUTHORITY_ORDER=[
"Constitutional or treaty text where applicable",
"Current enacted legislation / binding regulation",
"Binding appellate or supreme-court authority",
"Relevant regulator rules or legally binding decisions",
"Official guidance and explanatory materials",
"Bills, consultations and proposals",
"Secondary commentary and practitioner analysis"
];

export function getJurisdictionProfile(value:string){const needle=value.trim().toLowerCase();return JURISDICTIONS.find(item=>item.id===needle||item.name.toLowerCase()===needle)??null;}
export function hostMatchesJurisdictionSource(url:string,jurisdiction:string){const profile=getJurisdictionProfile(jurisdiction);return Boolean(profile&&hostMatchesCaseLawSource(url,[...profile.officialHosts]));}
