import { hostMatchesCaseLawSource } from "./case-law-sources";

export const JURISDICTION_COVERAGE_TIERS = {
  source_discovery: {
    label: "Source discovery",
    description: "Verified official entry points are mapped, but the jurisdiction profile is not yet deep enough for broad legal research without extra source discovery.",
  },
  structured_profile: {
    label: "Structured profile",
    description: "Official sources, legal-system context and authority layers are curated, with issue-specific verification still required.",
  },
  research_ready: {
    label: "Research ready",
    description: "Multiple verified official research entry points and authority context are mapped for live research, subject to currentness and applicability checks.",
  },
} as const;

const REVIEWED_ON = "2026-09-13";

export const JURISDICTIONS = [
  {id:"uk",name:"United Kingdom",region:"Europe",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common law with devolved legal systems",levels:["UK Parliament","Devolved legislatures","Secondary legislation","Courts"],primary:["https://www.legislation.gov.uk/","https://caselaw.nationalarchives.gov.uk/"],officialHosts:["legislation.gov.uk","caselaw.nationalarchives.gov.uk"],notes:"Check whether the issue falls under England & Wales, Scotland or Northern Ireland and whether competence is devolved."},
  {id:"eu",name:"European Union",region:"Europe",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Supranational legal order",levels:["EU treaties","Regulations","Directives","Decisions","CJEU case law"],primary:["https://eur-lex.europa.eu/","https://curia.europa.eu/"],officialHosts:["eur-lex.europa.eu","curia.europa.eu"],notes:"Determine whether EU law applies directly, requires national implementation, or interacts with member-state law."},
  {id:"us",name:"United States",region:"North America",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Federal system with federal and state law",levels:["Constitution","Federal statutes","Federal regulations","State law","Federal/state courts"],primary:["https://www.congress.gov/","https://uscode.house.gov/","https://www.federalregister.gov/"],officialHosts:["congress.gov","uscode.house.gov","federalregister.gov"],notes:"Identify the relevant state and whether federal law pre-empts, supplements or leaves the issue to state law."},
  {id:"ca",name:"Canada",region:"North America",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal bijural system",levels:["Constitution","Federal statutes","Provincial/territorial law","Regulations","Courts"],primary:["https://laws-lois.justice.gc.ca/"],officialHosts:["laws-lois.justice.gc.ca"],notes:"Identify whether jurisdiction lies with the federal government or a province/territory; Quebec private law differs from common-law provinces."},
  {id:"au",name:"Australia",region:"Asia-Pacific",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal common-law system",levels:["Constitution","Commonwealth legislation","State/territory law","Regulations","Courts"],primary:["https://www.legislation.gov.au/"],officialHosts:["legislation.gov.au"],notes:"Check Commonwealth versus state/territory competence and the relevant regulator or tribunal."},
  {id:"nz",name:"New Zealand",region:"Asia-Pacific",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Common-law parliamentary system",levels:["Acts","Secondary legislation","Courts","Regulators"],primary:["https://www.legislation.govt.nz/"],officialHosts:["legislation.govt.nz"],notes:"Start with current consolidated legislation and then verify relevant court and regulator materials."},
  {id:"fr",name:"France",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Civil-law republic with constitutional and administrative review",levels:["Constitutional block","Statutes and codes","Regulations","Administrative and judicial courts"],primary:["https://www.legifrance.gouv.fr/"],officialHosts:["legifrance.gouv.fr"],notes:"Use Légifrance for enacted texts and codes, then identify the competent judicial or administrative court and verify current consolidated text and commencement."},
  {id:"de",name:"Germany",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law system",levels:["Basic Law","Federal statutes","Federal regulations","Länder law","Federal and Land courts"],primary:["https://www.gesetze-im-internet.de/","https://www.recht.bund.de/"],officialHosts:["gesetze-im-internet.de","recht.bund.de"],notes:"Distinguish federal from Länder competence. Consolidated texts on Gesetze im Internet are useful research copies; verify official promulgation in the electronic Federal Law Gazette where consequential."},
  {id:"ie",name:"Ireland",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Common-law constitutional system",levels:["Constitution","Acts of the Oireachtas","Statutory instruments","Courts"],primary:["https://www.irishstatutebook.ie/"],officialHosts:["irishstatutebook.ie"],notes:"Verify amendments, commencement and EU-law interaction. The Irish Statute Book is produced by the Office of the Attorney General and should be checked for currentness notices."},
  {id:"es",name:"Spain",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Decentralised civil-law constitutional system",levels:["Constitution","State legislation","Autonomous-community law","Regulations","Constitutional and ordinary courts"],primary:["https://www.boe.es/"],officialHosts:["boe.es"],notes:"Identify state versus autonomous-community competence. BOE consolidated texts aid research, but the BOE itself warns consolidated versions are informational rather than the official promulgated text."},
  {id:"it",name:"Italy",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Civil-law constitutional republic",levels:["Constitution","Primary legislation","Legislative decrees and regulations","Regional law","Constitutional and ordinary courts"],primary:["https://www.normattiva.it/"],officialHosts:["normattiva.it"],notes:"Check the version in force, amendments and effective dates, then identify any relevant constitutional, ordinary or administrative-court authority."},
  {id:"ch",name:"Switzerland",region:"Europe",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law system with cantonal law",levels:["Federal Constitution","Federal statutes and ordinances","Cantonal law","Federal and cantonal courts"],primary:["https://www.fedlex.admin.ch/"],officialHosts:["fedlex.admin.ch"],notes:"Fedlex is the federal-law publication platform. Cantonal issues require the relevant canton’s official sources in addition to federal materials."},
  {id:"sg",name:"Singapore",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common-law parliamentary system",levels:["Constitution","Acts","Subsidiary legislation","Supreme Court and State Courts"],primary:["https://sso.agc.gov.sg/","https://www.judiciary.gov.sg/judgments"],officialHosts:["sso.agc.gov.sg","judiciary.gov.sg"],notes:"Singapore Statutes Online is provided by the Attorney-General’s Chambers. Verify the current/repealed/uncommenced status and use official court judgments for case authority."},
  {id:"jp",name:"Japan",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Civil-law constitutional system",levels:["Constitution","Acts","Cabinet and ministerial orders","Supreme and lower courts"],primary:["https://elaws.e-gov.go.jp/","https://www.courts.go.jp/english/Judgments/"],officialHosts:["elaws.e-gov.go.jp","courts.go.jp"],notes:"Use e-Gov for legislation and official courts material for judgments. English judgment translations may be unofficial, so consequential analysis should verify the authoritative Japanese text."},
  {id:"kr",name:"South Korea",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Civil-law constitutional republic",levels:["Constitution","Acts","Presidential and ministerial decrees","Constitutional Court and ordinary courts"],primary:["https://www.law.go.kr/","https://www.scourt.go.kr/eng/"],officialHosts:["law.go.kr","scourt.go.kr"],notes:"Use the Korean Law Information Center for legislation and official judiciary sources for court materials; verify language version, enforcement date and later amendments."},
  {id:"in",name:"India",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Federal common-law constitutional system",levels:["Constitution","Union legislation","State legislation","Subordinate legislation","Supreme Court and High Courts"],primary:["https://www.indiacode.nic.in/","https://www.sci.gov.in/"],officialHosts:["indiacode.nic.in","sci.gov.in"],notes:"Identify Union versus state competence. India Code is a government legislation source; verify current subordinate legislation and use original Supreme Court or relevant High Court decisions rather than summaries alone."},
  {id:"hk",name:"Hong Kong",region:"Asia-Pacific",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common-law system under the Basic Law",levels:["Basic Law","Ordinances","Subsidiary legislation","Court of Final Appeal and lower courts"],primary:["https://www.elegislation.gov.hk/","https://www.judiciary.hk/"],officialHosts:["elegislation.gov.hk","judiciary.hk"],notes:"Use verified copies on Hong Kong e-Legislation where available and distinguish them from reference-only HTML/RTF versions. Verify appellate history through official Judiciary material."},
  {id:"br",name:"Brazil",region:"Latin America",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law constitutional system",levels:["Federal Constitution","Federal legislation","State and municipal law","Regulations","Federal and state courts"],primary:["https://www4.planalto.gov.br/legislacao"],officialHosts:["planalto.gov.br"],notes:"Identify federal, state or municipal competence and verify amendments and constitutional review. The Presidency’s legislation portal is a federal-law research starting point."},
  {id:"mx",name:"Mexico",region:"Latin America",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law constitutional system",levels:["Federal Constitution","Federal statutes","State law","Regulations","Federal and state courts"],primary:["https://www.diputados.gob.mx/LeyesBiblio/index.htm"],officialHosts:["diputados.gob.mx"],notes:"The Chamber of Deputies compilation is useful for current federal texts but states it is informational; the Diario Oficial de la Federación controls official federal publication. State-law issues require state sources."},
  {id:"za",name:"South Africa",region:"Africa",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Mixed legal system under a supreme Constitution",levels:["Constitution","Acts of Parliament","Provincial law","Regulations","Constitutional Court and other courts"],primary:["https://www.gov.za/documents/acts","https://www.parliament.gov.za/acts"],officialHosts:["gov.za","parliament.gov.za"],notes:"Use official government and Parliament sources for legislation, then verify constitutional and appellate authority from the competent court. Mixed common-law, Roman-Dutch and customary-law issues may require specialised analysis."},
  {id:"ke",name:"Kenya",region:"Africa",coverageTier:"research_ready",reviewedOn:REVIEWED_ON,system:"Common-law constitutional system with customary-law interaction",levels:["Constitution","Acts of Parliament","Subsidiary legislation","Supreme Court and superior courts"],primary:["https://new.kenyalaw.org/","https://judiciary.go.ke/"],officialHosts:["kenyalaw.org","judiciary.go.ke"],notes:"Kenya Law is the National Council for Law Reporting and official source for Law Reports and consolidated Laws of Kenya. Verify version dates, Gazette material and the deciding court."},
  {id:"ae",name:"United Arab Emirates",region:"Middle East",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Federal civil-law system with emirate-level and specialised regimes",levels:["Constitution","Federal legislation","Cabinet and regulatory decisions","Emirate-level law","Federal and local courts"],primary:["https://uaelegislation.gov.ae/en"],officialHosts:["uaelegislation.gov.ae"],notes:"The UAE Legislation Platform is the official federal legislation platform. Identify whether the issue is federal, emirate-level or within a specialised free-zone regime before drawing conclusions."},
  {id:"sa",name:"Saudi Arabia",region:"Middle East",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Sharia-based legal system with codified laws and regulations",levels:["Basic Law and foundational instruments","Royal decrees and laws","Council of Ministers regulations","Implementing regulations","Courts and judicial bodies"],primary:["https://laws.boe.gov.sa/"],officialHosts:["laws.boe.gov.sa","boe.gov.sa"],notes:"Use the Bureau of Experts legal-document portal for Saudi laws and regulations, verify amendments and implementing rules, and account for Sharia principles and specialist jurisdiction where relevant."},
  {id:"intl",name:"International",region:"International",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Treaty and customary international law framework",levels:["Treaties","Customary international law","Institutional rules","International tribunals"],primary:["https://treaties.un.org/","https://www.icj-cij.org/"],officialHosts:["treaties.un.org","icj-cij.org"],notes:"Confirm treaty status, reservations, territorial application and whether the instrument is binding on the states involved."},
  {id:"ip",name:"International IP",region:"International",coverageTier:"structured_profile",reviewedOn:REVIEWED_ON,system:"Treaty-based and national IP systems",levels:["WIPO treaties","National statutes","Regional systems","Courts/offices"],primary:["https://www.wipo.int/wipolex/"],officialHosts:["wipo.int"],notes:"IP rights are territorial. Identify the country or regional right, registration status and applicable treaty framework."},
] as const;

export const AUTHORITY_ORDER=[
"Constitutional or treaty text where applicable",
"Current enacted legislation / binding regulation",
"Binding appellate or supreme-court authority",
"Relevant regulator rules or legally binding decisions",
"Official guidance and explanatory materials",
"Bills, consultations and proposals",
"Secondary commentary and practitioner analysis"
];

export function getJurisdictionProfile(value: string) {
  const needle = value.trim().toLowerCase();
  return JURISDICTIONS.find((item) => item.id === needle || item.name.toLowerCase() === needle) ?? null;
}

export function hostMatchesJurisdictionSource(url: string, jurisdiction: string): boolean {
  const profile = getJurisdictionProfile(jurisdiction);
  return Boolean(profile && hostMatchesCaseLawSource(url, [...profile.officialHosts]));
}
