export const JURISDICTIONS=[
{id:"uk",name:"United Kingdom",system:"Common law with devolved legal systems",levels:["UK Parliament","Devolved legislatures","Secondary legislation","Courts"],primary:["https://www.legislation.gov.uk/","https://caselaw.nationalarchives.gov.uk/"],notes:"Check whether the issue falls under England & Wales, Scotland or Northern Ireland and whether competence is devolved."},
{id:"ie",name:"Ireland",system:"Common-law constitutional parliamentary system",levels:["Constitution","Acts of the Oireachtas","Statutory instruments","Courts","EU law where applicable"],primary:["https://www.irishstatutebook.ie/"],notes:"Use the electronic Irish Statute Book as a research starting point, but note that the official versions remain the printed versions published by Government Publications; also check applicable EU law and current amendments."},
{id:"eu",name:"European Union",system:"Supranational legal order",levels:["EU treaties","Regulations","Directives","Decisions","CJEU case law"],primary:["https://eur-lex.europa.eu/","https://curia.europa.eu/"],notes:"Determine whether EU law applies directly, requires national implementation, or interacts with member-state law."},
{id:"fr",name:"France",system:"Civil-law constitutional system",levels:["Constitutional norms","Codes and statutes","Regulations","Administrative law","Courts"],primary:["https://www.legifrance.gouv.fr/"],notes:"Start with current consolidated legislation on Légifrance and distinguish statutory, regulatory, constitutional and administrative sources."},
{id:"de",name:"Germany",system:"Federal civil-law constitutional system",levels:["Basic Law","Federal statutes","Federal regulations","Land law","Courts","EU law where applicable"],primary:["https://www.gesetze-im-internet.de/"],notes:"Identify federal versus Land competence and check EU-law interaction. The federal portal is a starting point for federal statutes and regulations, not a substitute for Land-level sources."},
{id:"ch",name:"Switzerland",system:"Federal civil-law system",levels:["Federal Constitution","Federal acts","Ordinances","Cantonal law","Courts"],primary:["https://www.fedlex.admin.ch/"],notes:"Separate federal and cantonal law and verify the language/version in force. English material may be unofficial and should not replace the authoritative language text."},
{id:"us",name:"United States",system:"Federal system with federal and state law",levels:["Constitution","Federal statutes","Federal regulations","State law","Federal/state courts"],primary:["https://www.congress.gov/","https://uscode.house.gov/","https://www.federalregister.gov/"],notes:"Identify the relevant state and whether federal law pre-empts, supplements or leaves the issue to state law."},
{id:"ca",name:"Canada",system:"Federal bijural system",levels:["Constitution","Federal statutes","Provincial/territorial law","Regulations","Courts"],primary:["https://laws-lois.justice.gc.ca/"],notes:"Identify whether jurisdiction lies with the federal government or a province/territory; Quebec private law differs from common-law provinces."},
{id:"mx",name:"Mexico",system:"Federal civil-law constitutional system",levels:["Constitution","Federal statutes","Federal regulations","State law","Courts"],primary:["https://dof.gob.mx/","https://www.diputados.gob.mx/LeyesBiblio/index.htm"],notes:"Use the Diario Oficial de la Federación for official federal publication. Chamber of Deputies compilations are useful for research but state that they are informational; also identify relevant state law."},
{id:"br",name:"Brazil",system:"Federal civil-law constitutional system",levels:["Federal Constitution","Complementary and ordinary laws","Provisional measures","Decrees","State/municipal law","Courts"],primary:["https://www4.planalto.gov.br/legislacao"],notes:"Separate federal, state and municipal competence and verify consolidation, amendments and effective dates in authoritative publication sources."},
{id:"au",name:"Australia",system:"Federal common-law system",levels:["Constitution","Commonwealth legislation","State/territory law","Regulations","Courts"],primary:["https://www.legislation.gov.au/"],notes:"Check Commonwealth versus state/territory competence and the relevant regulator or tribunal."},
{id:"nz",name:"New Zealand",system:"Common-law parliamentary system",levels:["Acts","Secondary legislation","Courts","Regulators"],primary:["https://www.legislation.govt.nz/"],notes:"Start with current consolidated legislation and then verify relevant court and regulator materials."},
{id:"za",name:"South Africa",system:"Constitutional mixed legal system",levels:["Constitution","Acts of Parliament","Regulations","Provincial law","Courts"],primary:["https://www.gov.za/documents-categories/acts"],notes:"Check the Constitution, national legislation, regulations and any applicable provincial law. Government act listings are a research starting point; verify current amendments and commencement."},
{id:"in",name:"India",system:"Federal common-law constitutional system",levels:["Constitution","Central Acts","Subordinate legislation","State law","Courts"],primary:["https://www.indiacode.nic.in/"],notes:"Identify Union versus State competence and verify rules, regulations, notifications and commencement as well as the parent Act."},
{id:"sg",name:"Singapore",system:"Common-law parliamentary system",levels:["Constitution","Acts","Subsidiary legislation","Courts"],primary:["https://sso.agc.gov.sg/"],notes:"Use Singapore Statutes Online for current Acts and subsidiary legislation, then check commencement, amendments and relevant judicial authority."},
{id:"hk",name:"Hong Kong SAR",system:"Common-law system under the Basic Law",levels:["Basic Law","Ordinances","Subsidiary legislation","Courts"],primary:["https://www.elegislation.gov.hk/"],notes:"For Hong Kong e-Legislation, distinguish verified PDF copies with legal status from HTML/RTF reference versions and confirm the version date in force."},
{id:"jp",name:"Japan",system:"Civil-law constitutional system",levels:["Constitution","Acts","Cabinet orders","Ministerial ordinances","Courts"],primary:["https://elaws.e-gov.go.jp/","https://www.japaneselawtranslation.go.jp/"],notes:"Use e-Gov Law Search for Japanese legal text. English translations on Japanese Law Translation are reference materials only; only the original Japanese text has legal effect."},
{id:"kr",name:"South Korea",system:"Civil-law constitutional system",levels:["Constitution","Acts","Presidential decrees","Ministerial ordinances","Courts"],primary:["https://law.go.kr/eng/engMain.do"],notes:"Use the Korean Law Information Center as a primary research portal and verify the Korean text, amendment history and enforcement date for any proposition."},
{id:"ae",name:"United Arab Emirates",system:"Federal civil-law system with Sharia influences and emirate-level law",levels:["Constitution","Federal laws","Executive regulations","Cabinet resolutions","Emirate-level law","Courts"],primary:["https://uaelegislation.gov.ae/en"],notes:"The UAE Legislation platform covers federal legislation. Identify whether emirate-level rules or free-zone regimes also apply and verify Arabic text, amendments and effective dates where relevant."},
{id:"intl",name:"International",system:"Treaty and customary international law framework",levels:["Treaties","Customary international law","Institutional rules","International tribunals"],primary:["https://treaties.un.org/","https://www.icj-cij.org/"],notes:"Confirm treaty status, reservations, territorial application and whether the instrument is binding on the states involved."},
{id:"ip",name:"International IP",system:"Treaty-based and national IP systems",levels:["WIPO treaties","National statutes","Regional systems","Courts/offices"],primary:["https://www.wipo.int/wipolex/"],notes:"IP rights are territorial. Identify the country or regional right, registration status and applicable treaty framework."}
];

export const AUTHORITY_ORDER=[
"Constitutional or treaty text where applicable",
"Current enacted legislation / binding regulation",
"Binding appellate or supreme-court authority",
"Relevant regulator rules or legally binding decisions",
"Official guidance and explanatory materials",
"Bills, consultations and proposals",
"Secondary commentary and practitioner analysis"
];
