import{createServerFn}from"@tanstack/react-start";import{z}from"zod";import{requireSupabaseAuth}from"@/integrations/supabase/auth-middleware";import{searchPublicWeb,type WebSource}from"@/lib/ai/web-access.server";import{runChat}from"@/lib/runtime/model-gateway.server";import{resolveAssistantModelPreference}from"@/lib/ai/ai-preferences.server";import{getJurisdictionProfile,hostMatchesJurisdictionSource}from"@/lib/legal/jurisdictions";
type Sb={from:(t:string)=>any};const input=z.object({query:z.string().trim().min(3).max(600),jurisdiction:z.string().trim().min(2).max(120),topic:z.string().trim().max(100).optional()});

const OFFICIAL_HOST_SUFFIXES=[
"legislation.gov.uk","caselaw.nationalarchives.gov.uk","treaties.fcdo.gov.uk","irishstatutebook.ie","europa.eu","legifrance.gouv.fr","gesetze-im-internet.de","recht.bund.de","boe.es","normattiva.it","fedlex.admin.ch","congress.gov","uscode.house.gov","federalregister.gov","laws-lois.justice.gc.ca","treaty-accord.gc.ca","dof.gob.mx","diputados.gob.mx","planalto.gov.br","legislation.gov.au","dfat.gov.au","legislation.govt.nz","treaties.mfat.govt.nz","gov.za","parliament.gov.za","kenyalaw.org","judiciary.go.ke","indiacode.nic.in","sci.gov.in","sso.agc.gov.sg","judiciary.gov.sg","elegislation.gov.hk","judiciary.hk","elaws.e-gov.go.jp","japaneselawtranslation.go.jp","courts.go.jp","law.go.kr","scourt.go.kr","uaelegislation.gov.ae","laws.boe.gov.sa","boe.gov.sa","treaties.un.org","icj-cij.org","wipo.int","uncitral.un.org","wto.org","normlex.ilo.org","ohchr.org"
];
const GOVERNMENT_SUFFIXES=[".gov",".gov.uk",".gov.au",".govt.nz",".gov.sg",".gov.hk",".gov.za",".gov.in",".gov.br",".gouv.fr",".admin.ch",".go.kr",".go.jp",".gob.mx",".gc.ca"];

export function isOfficialLegalUrl(value:string){
  try{
    const hostname=new URL(value).hostname.toLowerCase().replace(/\.$/,"");
    return OFFICIAL_HOST_SUFFIXES.some(suffix=>hostname===suffix||hostname.endsWith(`.${suffix}`))||GOVERNMENT_SUFFIXES.some(suffix=>hostname.endsWith(suffix));
  }catch{return false}
}
export function rankLegalSources(sources:WebSource[],jurisdiction?:string){return [...sources].sort((a,b)=>{const verifiedB=jurisdiction&&hostMatchesJurisdictionSource(b.url,jurisdiction)?4:0;const verifiedA=jurisdiction&&hostMatchesJurisdictionSource(a.url,jurisdiction)?4:0;return verifiedB+Number(isOfficialLegalUrl(b.url))-(verifiedA+Number(isOfficialLegalUrl(a.url)));});}
export const runLegalResearch=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((v:unknown)=>input.parse(v)).handler(async({data,context})=>{const sb=context.supabase as unknown as Sb;let pref=null;try{const r=await sb.from("user_ai_preferences").select("default_provider,default_model").eq("user_id",context.userId).maybeSingle();if(!r.error)pref=r.data}catch{}const{provider,model}=resolveAssistantModelPreference(pref);const profile=getJurisdictionProfile(data.jurisdiction);const sourceHint=profile?.primary.length?` official sources ${profile.primary.map(url=>new URL(url).hostname).join(" ")}`:"";const searchQuery=`${data.query} ${data.jurisdiction} law legislation regulation official${sourceHint}`;const web=await searchPublicWeb(searchQuery,10);const sources=rankLegalSources(web.results,data.jurisdiction).slice(0,10);if(!sources.length)throw new Error("No live legal sources were found.");const evidence=sources.map((s,i)=>`[${i+1}] ${s.title}\nURL: ${s.url}\nSnippet: ${s.snippet??""}`).join("\n\n");const coverage=profile?`Blackstar jurisdiction registry coverage: ${profile.coverageTier}; official entry points reviewed ${profile.reviewedOn}; region ${profile.region}. This describes curated research-source coverage, not completeness of the jurisdiction's law.`:"No curated Blackstar jurisdiction profile matched this jurisdiction; additional source verification is required.";const prompt=`Question: ${data.query}\nJurisdiction: ${data.jurisdiction}\nTopic: ${data.topic||"general"}\nCoverage context: ${coverage}\n\nSOURCES:\n${evidence}`;const result=await runChat({provider,model,maxTokens:2200,messages:[{role:"system",content:"You are Blackstar Legal Research. Provide legal information, not legal advice. Use only the supplied live sources as evidence. Prioritise official/primary sources. State the jurisdiction and date-sensitivity. Distinguish enacted/binding law from guidance, proposals and commentary. Never invent a citation, case, statute, quotation or URL. If governing jurisdiction, currentness, authority or applicability cannot be established, say so. A government or official portal is still only evidence to inspect; its presence does not establish that a rule applies to the user's facts. A Blackstar jurisdiction coverage tier describes curated research entry points and never means all laws, local rules or authorities are captured. Cite factual legal propositions with Markdown links to supplied URLs. End with a short section titled 'Professional review' identifying what a qualified lawyer should verify for a consequential decision."},{role:"user",content:prompt}]});return{report:result.text,provider:result.provider,model:result.model,sources,coverage:profile?{tier:profile.coverageTier,reviewedOn:profile.reviewedOn,region:profile.region}:null};});
