/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppMissionControlRouteImport } from './routes/app.mission-control'
import { Route as AppWorkforceRouteImport } from './routes/app.workforce'
import { Route as AppDepartmentsIndexRouteImport } from './routes/app.departments.index'
import { Route as AppDepartmentsSlugRouteImport } from './routes/app.departments.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionControlRoute = AppMissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkforceRoute = AppWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsIndexRoute = AppDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsSlugRoute = AppDepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/mission-control': typeof AppMissionControlRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app/': typeof AppIndexRoute
  '/app/departments/$slug': typeof AppDepartmentsSlugRoute
  '/app/departments/': typeof AppDepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/mission-control': typeof AppMissionControlRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app': typeof AppIndexRoute
  '/app/departments/$slug': typeof AppDepartmentsSlugRoute
  '/app/departments': typeof AppDepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/mission-control': typeof AppMissionControlRoute
  '/app/workforce': typeof AppWorkforceRoute
  '/app/': typeof AppIndexRoute
  '/app/departments/$slug': typeof AppDepartmentsSlugRoute
  '/app/departments/': typeof AppDepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/integrations'
    | '/app/marketplace'
    | '/app/mission-control'
    | '/app/workforce'
    | '/app/'
    | '/app/departments/$slug'
    | '/app/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/integrations'
    | '/app/marketplace'
    | '/app/mission-control'
    | '/app/workforce'
    | '/app'
    | '/app/departments/$slug'
    | '/app/departments'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/integrations'
    | '/app/marketplace'
    | '/app/mission-control'
    | '/app/workforce'
    | '/app/'
    | '/app/departments/$slug'
    | '/app/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mission-control': {
      id: '/app/mission-control'
      path: '/mission-control'
      fullPath: '/app/mission-control'
      preLoaderRoute: typeof AppMissionControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workforce': {
      id: '/app/workforce'
      path: '/workforce'
      fullPath: '/app/workforce'
      preLoaderRoute: typeof AppWorkforceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments/': {
      id: '/app/departments/'
      path: '/departments'
      fullPath: '/app/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments/$slug': {
      id: '/app/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/app/departments/$slug'
      preLoaderRoute: typeof AppDepartmentsSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMissionControlRoute: typeof AppMissionControlRoute
  AppWorkforceRoute: typeof AppWorkforceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDepartmentsSlugRoute: typeof AppDepartmentsSlugRoute
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMissionControlRoute: AppMissionControlRoute,
  AppWorkforceRoute: AppWorkforceRoute,
  AppIndexRoute: AppIndexRoute,
  AppDepartmentsSlugRoute: AppDepartmentsSlugRoute,
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
