-- Blackstar creator marketplace commerce.
-- Fee rule requested by operator: £3 listing fee; sales below £10,000 = 2%; £10,000 and above = 8%.
create table public.marketplace_listings (
 id uuid primary key default gen_random_uuid(), seller_id uuid not null references auth.users(id) on delete cascade,
 title text not null check (char_length(title) between 2 and 120), slug text not null unique, description text not null default '',
 item_type text not null check (item_type in ('ai_tool','website','app','agent','template','automation','code','design','dataset','prompt_pack','plugin','other')),
 price_pence bigint not null check (price_pence between 0 and 1000000000), currency text not null default 'GBP' check (currency='GBP'),
 status text not null default 'draft' check (status in ('draft','listing_fee_due','pending_review','published','rejected','unlisted','sold')),
 delivery_type text not null default 'digital' check (delivery_type in ('digital','license','source_code','repository_access','service_handoff','other')),
 preview_url text,thumbnail_url text,tags text[] not null default '{}',metadata jsonb not null default '{}'::jsonb,
 listing_fee_pence integer not null default 300 check (listing_fee_pence=300),listing_fee_paid_at timestamptz,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.marketplace_orders (
 id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.marketplace_listings(id) on delete restrict,
 buyer_id uuid not null references auth.users(id) on delete restrict,seller_id uuid not null references auth.users(id) on delete restrict,
 sale_price_pence bigint not null check (sale_price_pence>=0),platform_fee_bps integer not null check (platform_fee_bps in (200,800)),platform_fee_pence bigint not null check(platform_fee_pence>=0),seller_net_pence bigint not null check(seller_net_pence>=0),
 currency text not null default 'GBP' check(currency='GBP'),status text not null default 'pending' check(status in ('pending','paid','fulfilled','refunded','disputed','cancelled')),payment_provider text,provider_payment_id text,paid_at timestamptz,fulfilled_at timestamptz,created_at timestamptz not null default now(),unique(payment_provider,provider_payment_id)
);
create table public.marketplace_listing_fee_payments(id uuid primary key default gen_random_uuid(),listing_id uuid not null references public.marketplace_listings(id) on delete cascade,seller_id uuid not null references auth.users(id) on delete cascade,amount_pence integer not null default 300 check(amount_pence=300),currency text not null default 'GBP' check(currency='GBP'),status text not null default 'pending' check(status in ('pending','paid','failed','refunded')),payment_provider text,provider_payment_id text,paid_at timestamptz,created_at timestamptz not null default now(),unique(payment_provider,provider_payment_id));
create index marketplace_listings_public_idx on public.marketplace_listings(status,published_at desc);create index marketplace_listings_seller_idx on public.marketplace_listings(seller_id,created_at desc);create index marketplace_orders_buyer_idx on public.marketplace_orders(buyer_id,created_at desc);create index marketplace_orders_seller_idx on public.marketplace_orders(seller_id,created_at desc);
alter table public.marketplace_listings enable row level security;alter table public.marketplace_listings force row level security;alter table public.marketplace_orders enable row level security;alter table public.marketplace_orders force row level security;alter table public.marketplace_listing_fee_payments enable row level security;alter table public.marketplace_listing_fee_payments force row level security;
revoke all on table public.marketplace_listings,public.marketplace_orders,public.marketplace_listing_fee_payments from anon,authenticated;grant select,insert,update,delete on public.marketplace_listings to authenticated;grant select on public.marketplace_orders,public.marketplace_listing_fee_payments to authenticated;grant all on public.marketplace_listings,public.marketplace_orders,public.marketplace_listing_fee_payments to service_role;
create policy marketplace_listings_read on public.marketplace_listings for select to authenticated using(status='published' or seller_id=(select auth.uid()));create policy marketplace_listings_insert on public.marketplace_listings for insert to authenticated with check(seller_id=(select auth.uid()) and status='draft' and listing_fee_pence=300 and listing_fee_paid_at is null);create policy marketplace_listings_update on public.marketplace_listings for update to authenticated using(seller_id=(select auth.uid())) with check(seller_id=(select auth.uid()) and listing_fee_pence=300);create policy marketplace_orders_parties_read on public.marketplace_orders for select to authenticated using(buyer_id=(select auth.uid()) or seller_id=(select auth.uid()));create policy marketplace_listing_fees_owner_read on public.marketplace_listing_fee_payments for select to authenticated using(seller_id=(select auth.uid()));
create or replace function public.marketplace_fee_quote(p_sale_price_pence bigint) returns table(platform_fee_bps integer,platform_fee_pence bigint,seller_net_pence bigint) language sql immutable set search_path=public as $$ select case when p_sale_price_pence < 1000000 then 200 else 800 end,round(p_sale_price_pence*(case when p_sale_price_pence < 1000000 then .02 else .08 end))::bigint,p_sale_price_pence-round(p_sale_price_pence*(case when p_sale_price_pence < 1000000 then .02 else .08 end))::bigint $$;revoke all on function public.marketplace_fee_quote(bigint) from public,anon;grant execute on function public.marketplace_fee_quote(bigint) to authenticated,service_role;