-- Cover foreign keys introduced/restored by the Blackstar workspace and repository schema.
create index if not exists organisation_members_user_idx on public.organisation_members(user_id);
create index if not exists organisation_members_invited_by_idx on public.organisation_members(invited_by) where invited_by is not null;
create index if not exists organisations_owner_idx on public.organisations(owner_id);
create index if not exists profiles_org_idx on public.profiles(org_id) where org_id is not null;
create index if not exists subscriptions_org_idx on public.subscriptions(org_id) where org_id is not null;
create index if not exists subscriptions_user_idx on public.subscriptions(user_id) where user_id is not null;
create index if not exists subscriptions_plan_idx on public.subscriptions(plan_code);
create index if not exists personal_agents_user_idx on public.personal_agents(user_id);
create index if not exists personal_agents_org_idx on public.personal_agents(org_id) where org_id is not null;
create index if not exists personal_agents_org_fk_idx on public.personal_agents(org_id_fk) where org_id_fk is not null;
create index if not exists agent_tasks_user_created_idx on public.agent_tasks(user_id,created_at desc);
create index if not exists agent_tasks_org_created_idx on public.agent_tasks(org_id,created_at desc) where org_id is not null;
create index if not exists agent_tasks_agent_idx on public.agent_tasks(agent_id) where agent_id is not null;
create index if not exists workflows_user_idx on public.workflows(user_id);
create index if not exists workflows_org_idx on public.workflows(org_id) where org_id is not null;
create index if not exists usage_records_user_idx on public.usage_records(user_id);
create index if not exists usage_records_org_idx on public.usage_records(org_id) where org_id is not null;
create index if not exists usage_records_agent_idx on public.usage_records(agent_id) where agent_id is not null;
create index if not exists mission_audit_logs_user_idx on public.mission_audit_logs(user_id,created_at desc);
create index if not exists mission_audit_logs_org_idx on public.mission_audit_logs(org_id,created_at desc) where org_id is not null;
create index if not exists project_activity_user_idx on public.project_activity(user_id);
create index if not exists project_resources_added_by_idx on public.project_resources(added_by);
create index if not exists project_collaborators_added_by_idx on public.project_collaborators(added_by);
create index if not exists project_stars_user_idx on public.project_stars(user_id);
create index if not exists project_repo_commits_author_idx on public.project_repository_commits(author_id);
create index if not exists project_repo_commits_parent_idx on public.project_repository_commits(parent_commit_id) where parent_commit_id is not null;
create index if not exists project_repo_branches_created_by_idx on public.project_repository_branches(created_by);
create index if not exists project_repo_branches_head_idx on public.project_repository_branches(head_commit_id) where head_commit_id is not null;
create index if not exists project_repo_files_updated_by_idx on public.project_repository_files(updated_by);
create index if not exists project_repo_commit_files_project_idx on public.project_repository_commit_files(project_id);
create index if not exists project_repo_issues_created_by_idx on public.project_repository_issues(created_by);
create index if not exists project_repo_issues_assignee_idx on public.project_repository_issues(assignee_id) where assignee_id is not null;
create index if not exists project_repo_issue_comments_project_idx on public.project_repository_issue_comments(project_id);
create index if not exists project_repo_issue_comments_created_by_idx on public.project_repository_issue_comments(created_by);
create index if not exists project_repo_releases_commit_idx on public.project_repository_releases(commit_id) where commit_id is not null;
create index if not exists project_repo_releases_created_by_idx on public.project_repository_releases(created_by);
create index if not exists project_repo_pr_created_by_idx on public.project_repository_pull_requests(created_by);
create index if not exists project_repo_pr_merged_by_idx on public.project_repository_pull_requests(merged_by) where merged_by is not null;
