-- Blackstar construction production hardening: existing owner-scoped child/parent
-- relationships must match the same owner and, where applicable, the same workspace.
-- Additive, no data writes or privilege grants. Run after the seven existing construction migrations.
-- Composite FKs defer validation to transaction completion so the existing ON DELETE CASCADE / SET NULL actions work.
-- Source: 52 existing construction-to-construction foreign-key edges and 51 missing covering indexes
-- audited in the active Supabase project on 2026-09-22. Never replay this migration once applied.

create unique index if not exists c_construction_parent_scope_uq_01 on public.construction_agent_runs (id, workspace_id, user_id);
create unique index if not exists c_construction_parent_scope_uq_02 on public.construction_assets (id, workspace_id, user_id);
create unique index if not exists c_construction_parent_scope_uq_03 on public.construction_inspections (id, workspace_id, user_id);
create unique index if not exists c_construction_parent_scope_uq_04 on public.construction_issues (id, workspace_id, user_id);
create unique index if not exists c_construction_parent_scope_uq_05 on public.construction_partners (id, workspace_id, user_id);
create unique index if not exists c_construction_parent_scope_uq_06 on public.construction_projects (id, workspace_id, user_id);
create unique index if not exists c_construction_parent_scope_uq_07 on public.construction_work_packages (id, workspace_id, user_id);
create unique index if not exists c_construction_parent_scope_uq_08 on public.construction_workspaces (id, user_id);

create index if not exists c_construction_owner_idx_01 on public.construction_agent_actions (user_id);
create index if not exists c_construction_owner_idx_02 on public.construction_agent_runs (user_id);
create index if not exists c_construction_owner_idx_03 on public.construction_asset_health (user_id);
create index if not exists c_construction_owner_idx_04 on public.construction_asset_telemetry (user_id);
create index if not exists c_construction_owner_idx_05 on public.construction_assets (user_id);
create index if not exists c_construction_owner_idx_06 on public.construction_changes (user_id);
create index if not exists c_construction_owner_idx_07 on public.construction_documents (user_id);
create index if not exists c_construction_owner_idx_08 on public.construction_estimate_items (user_id);
create index if not exists c_construction_owner_idx_09 on public.construction_field_records (user_id);
create index if not exists c_construction_owner_idx_10 on public.construction_inspection_actions (user_id);
create index if not exists c_construction_owner_idx_11 on public.construction_inspections (user_id);
create index if not exists c_construction_owner_idx_12 on public.construction_issues (user_id);
create index if not exists c_construction_owner_idx_13 on public.construction_maintenance (user_id);
create index if not exists c_construction_owner_idx_14 on public.construction_materials (user_id);
create index if not exists c_construction_owner_idx_15 on public.construction_partners (user_id);
create index if not exists c_construction_owner_idx_16 on public.construction_progress_evidence (user_id);
create index if not exists c_construction_owner_idx_17 on public.construction_projects (user_id);
create index if not exists c_construction_owner_idx_18 on public.construction_reliability_events (user_id);
create index if not exists c_construction_owner_idx_19 on public.construction_reports (user_id);
create index if not exists c_construction_owner_idx_20 on public.construction_schedule_tasks (user_id);
create index if not exists c_construction_owner_idx_21 on public.construction_tenders (user_id);
create index if not exists c_construction_owner_idx_22 on public.construction_work_packages (user_id);
create index if not exists c_construction_owner_idx_23 on public.construction_workforce (user_id);
create index if not exists c_construction_owner_idx_24 on public.construction_workspaces (user_id);

alter table public.construction_agent_actions add constraint c_construction_scope_fk_001 foreign key (run_id, workspace_id, user_id) references public.construction_agent_runs (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_001 on public.construction_agent_actions (run_id, workspace_id, user_id);
alter table public.construction_agent_actions add constraint c_construction_scope_fk_002 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_agent_runs add constraint c_construction_scope_fk_003 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_003 on public.construction_agent_runs (project_id, workspace_id, user_id);
alter table public.construction_agent_runs add constraint c_construction_scope_fk_004 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_asset_health add constraint c_construction_scope_fk_005 foreign key (asset_id, workspace_id, user_id) references public.construction_assets (id, workspace_id, user_id) deferrable initially deferred;
alter table public.construction_asset_health add constraint c_construction_scope_fk_006 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_asset_telemetry add constraint c_construction_scope_fk_007 foreign key (asset_id, workspace_id, user_id) references public.construction_assets (id, workspace_id, user_id) deferrable initially deferred;
alter table public.construction_asset_telemetry add constraint c_construction_scope_fk_008 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_assets add constraint c_construction_scope_fk_009 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_009 on public.construction_assets (project_id, workspace_id, user_id);
alter table public.construction_assets add constraint c_construction_scope_fk_010 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_changes add constraint c_construction_scope_fk_011 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_011 on public.construction_changes (project_id, workspace_id, user_id);
alter table public.construction_changes add constraint c_construction_scope_fk_012 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_documents add constraint c_construction_scope_fk_013 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_013 on public.construction_documents (project_id, workspace_id, user_id);
alter table public.construction_documents add constraint c_construction_scope_fk_014 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_estimate_items add constraint c_construction_scope_fk_015 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_015 on public.construction_estimate_items (project_id, workspace_id, user_id);
alter table public.construction_estimate_items add constraint c_construction_scope_fk_016 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_field_records add constraint c_construction_scope_fk_017 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_017 on public.construction_field_records (project_id, workspace_id, user_id);
alter table public.construction_field_records add constraint c_construction_scope_fk_018 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_inspection_actions add constraint c_construction_scope_fk_019 foreign key (inspection_id, workspace_id, user_id) references public.construction_inspections (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_019 on public.construction_inspection_actions (inspection_id, workspace_id, user_id);
alter table public.construction_inspection_actions add constraint c_construction_scope_fk_020 foreign key (issue_id, workspace_id, user_id) references public.construction_issues (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_020 on public.construction_inspection_actions (issue_id, workspace_id, user_id);
alter table public.construction_inspection_actions add constraint c_construction_scope_fk_021 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_inspections add constraint c_construction_scope_fk_022 foreign key (asset_id, workspace_id, user_id) references public.construction_assets (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_022 on public.construction_inspections (asset_id, workspace_id, user_id);
alter table public.construction_inspections add constraint c_construction_scope_fk_023 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_023 on public.construction_inspections (project_id, workspace_id, user_id);
alter table public.construction_inspections add constraint c_construction_scope_fk_024 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_issues add constraint c_construction_scope_fk_025 foreign key (asset_id, workspace_id, user_id) references public.construction_assets (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_025 on public.construction_issues (asset_id, workspace_id, user_id);
alter table public.construction_issues add constraint c_construction_scope_fk_026 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_026 on public.construction_issues (project_id, workspace_id, user_id);
alter table public.construction_issues add constraint c_construction_scope_fk_027 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_maintenance add constraint c_construction_scope_fk_028 foreign key (asset_id, workspace_id, user_id) references public.construction_assets (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_028 on public.construction_maintenance (asset_id, workspace_id, user_id);
alter table public.construction_maintenance add constraint c_construction_scope_fk_029 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_materials add constraint c_construction_scope_fk_030 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_030 on public.construction_materials (project_id, workspace_id, user_id);
alter table public.construction_materials add constraint c_construction_scope_fk_031 foreign key (supplier_id, workspace_id, user_id) references public.construction_partners (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_031 on public.construction_materials (supplier_id, workspace_id, user_id);
alter table public.construction_materials add constraint c_construction_scope_fk_032 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_partners add constraint c_construction_scope_fk_033 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_progress_evidence add constraint c_construction_scope_fk_034 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_034 on public.construction_progress_evidence (project_id, workspace_id, user_id);
alter table public.construction_progress_evidence add constraint c_construction_scope_fk_035 foreign key (work_package_id, workspace_id, user_id) references public.construction_work_packages (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_035 on public.construction_progress_evidence (work_package_id, workspace_id, user_id);
alter table public.construction_progress_evidence add constraint c_construction_scope_fk_036 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_projects add constraint c_construction_scope_fk_037 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_reliability_events add constraint c_construction_scope_fk_038 foreign key (asset_id, workspace_id, user_id) references public.construction_assets (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_038 on public.construction_reliability_events (asset_id, workspace_id, user_id);
alter table public.construction_reliability_events add constraint c_construction_scope_fk_039 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_reports add constraint c_construction_scope_fk_040 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_040 on public.construction_reports (project_id, workspace_id, user_id);
alter table public.construction_reports add constraint c_construction_scope_fk_041 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_schedule_tasks add constraint c_construction_scope_fk_042 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_042 on public.construction_schedule_tasks (project_id, workspace_id, user_id);
alter table public.construction_schedule_tasks add constraint c_construction_scope_fk_043 foreign key (work_package_id, workspace_id, user_id) references public.construction_work_packages (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_043 on public.construction_schedule_tasks (work_package_id, workspace_id, user_id);
alter table public.construction_schedule_tasks add constraint c_construction_scope_fk_044 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_tenders add constraint c_construction_scope_fk_045 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_045 on public.construction_tenders (project_id, workspace_id, user_id);
alter table public.construction_tenders add constraint c_construction_scope_fk_046 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_work_packages add constraint c_construction_scope_fk_047 foreign key (partner_id, workspace_id, user_id) references public.construction_partners (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_047 on public.construction_work_packages (partner_id, workspace_id, user_id);
alter table public.construction_work_packages add constraint c_construction_scope_fk_048 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_048 on public.construction_work_packages (project_id, workspace_id, user_id);
alter table public.construction_work_packages add constraint c_construction_scope_fk_049 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
alter table public.construction_workforce add constraint c_construction_scope_fk_050 foreign key (partner_id, workspace_id, user_id) references public.construction_partners (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_050 on public.construction_workforce (partner_id, workspace_id, user_id);
alter table public.construction_workforce add constraint c_construction_scope_fk_051 foreign key (project_id, workspace_id, user_id) references public.construction_projects (id, workspace_id, user_id) deferrable initially deferred;
create index if not exists c_construction_scope_idx_051 on public.construction_workforce (project_id, workspace_id, user_id);
alter table public.construction_workforce add constraint c_construction_scope_fk_052 foreign key (workspace_id, user_id) references public.construction_workspaces (id, user_id) deferrable initially deferred;
