// Mock data for the PalladiumAI Documents & Reports Centre.
// All documents are illustrative mock data — not real content.

export const DISCLAIMER = 'Documents shown are illustrative mock data and do not represent real content.';

export const METRICS = [
  { id: 'total', label: 'Documents', value: '284', delta: '+18 this week', tone: 'text-sky-300' },
  { id: 'ai', label: 'AI-Generated', value: '96', delta: '+34%', tone: 'text-violet-300' },
  { id: 'shared', label: 'Shared', value: '62', delta: '8 pending review', tone: 'text-amber-300' },
  { id: 'templates', label: 'Templates', value: '41', delta: '5 new', tone: 'text-emerald-300' },
];

export const NAV = [
  { id: 'recent', label: 'Recent', icon: 'Clock' },
  { id: 'templates', label: 'Templates', icon: 'LayoutTemplate' },
  { id: 'shared', label: 'Shared', icon: 'Share2' },
  { id: 'ai', label: 'Generated by AI', icon: 'Sparkles' },
];

export const TYPES = [
  { id: 'report', label: 'Report', icon: 'FileBarChart', tone: 'from-violet-600/40 to-indigo-600/40' },
  { id: 'proposal', label: 'Proposal', icon: 'FileText', tone: 'from-sky-600/40 to-blue-600/40' },
  { id: 'contract', label: 'Contract', icon: 'ScrollText', tone: 'from-fuchsia-600/40 to-pink-600/40' },
  { id: 'presentation', label: 'Presentation', icon: 'Presentation', tone: 'from-amber-600/40 to-orange-600/40' },
  { id: 'document', label: 'Document', icon: 'FileType', tone: 'from-emerald-600/40 to-teal-600/40' },
  { id: 'research', label: 'AI Research', icon: 'Microscope', tone: 'from-rose-600/40 to-red-600/40' },
  { id: 'notes', label: 'Meeting Notes', icon: 'NotebookPen', tone: 'from-cyan-600/40 to-sky-600/40' },
];

export const FORMATS = [
  { id: 'pdf', label: 'PDF', tone: 'text-rose-300 bg-rose-400/10' },
  { id: 'docx', label: 'DOCX', tone: 'text-sky-300 bg-sky-400/10' },
  { id: 'pptx', label: 'PPTX', tone: 'text-amber-300 bg-amber-400/10' },
  { id: 'csv', label: 'CSV', tone: 'text-emerald-300 bg-emerald-400/10' },
  { id: 'md', label: 'Markdown', tone: 'text-violet-300 bg-violet-400/10' },
];

export const AI_ACTIONS = [
  { id: 'generate', label: 'Generate', desc: 'Create from a prompt', icon: 'Sparkles', tone: 'from-violet-600/40 to-indigo-600/40' },
  { id: 'summarise', label: 'Summarise', desc: 'Condense content', icon: 'ScrollText', tone: 'from-sky-600/40 to-blue-600/40' },
  { id: 'rewrite', label: 'Rewrite', desc: 'Refine tone & clarity', icon: 'PenLine', tone: 'from-fuchsia-600/40 to-pink-600/40' },
  { id: 'translate', label: 'Translate', desc: '12 languages', icon: 'Languages', tone: 'from-amber-600/40 to-orange-600/40' },
  { id: 'analyse', label: 'Analyse', desc: 'Extract key insights', icon: 'Microscope', tone: 'from-emerald-600/40 to-teal-600/40' },
  { id: 'export', label: 'Export', desc: 'Download in any format', icon: 'Download', tone: 'from-cyan-600/40 to-sky-600/40' },
];

export const DOCS = [
  { id: 'd1', title: 'Q3 Revenue Analysis', type: 'report', format: 'pdf', updated: 'Aug 7', author: 'Maya Chen', shared: false, ai: true },
  { id: 'd2', title: 'Vertex Partnership Proposal', type: 'proposal', format: 'docx', updated: 'Aug 6', author: 'Sam Okafor', shared: true, ai: false },
  { id: 'd3', title: 'Master Services Agreement', type: 'contract', format: 'pdf', updated: 'Aug 5', author: 'Legal Bot', shared: true, ai: true },
  { id: 'd4', title: 'Investor Deck — Series B', type: 'presentation', format: 'pptx', updated: 'Aug 5', author: 'Riya Patel', shared: false, ai: false },
  { id: 'd5', title: 'AI Market Research Brief', type: 'research', format: 'md', updated: 'Aug 4', author: 'Research Agent', shared: true, ai: true },
  { id: 'd6', title: 'Quarterly Board Notes', type: 'notes', format: 'md', updated: 'Aug 3', author: 'Maya Chen', shared: false, ai: false },
  { id: 'd7', title: 'Pricing Strategy Memo', type: 'document', format: 'docx', updated: 'Aug 2', author: 'Sam Okafor', shared: true, ai: false },
  { id: 'd8', title: 'Customer Churn Export', type: 'document', format: 'csv', updated: 'Aug 1', author: 'Analytics Agent', shared: false, ai: true },
  { id: 'd9', title: 'Onboarding Playbook', type: 'document', format: 'pdf', updated: 'Jul 30', author: 'Leo Martins', shared: true, ai: false },
  { id: 'd10', title: 'Roadmap Review Notes', type: 'notes', format: 'md', updated: 'Jul 29', author: 'Maya Chen', shared: false, ai: false },
];

export const TEMPLATES = [
  { id: 't1', title: 'Executive Summary', type: 'report', uses: 128, tone: 'from-violet-600/40 to-indigo-600/40' },
  { id: 't2', title: 'SaaS Proposal', type: 'proposal', uses: 96, tone: 'from-sky-600/40 to-blue-600/40' },
  { id: 't3', title: 'NDA Template', type: 'contract', uses: 210, tone: 'from-fuchsia-600/40 to-pink-600/40' },
  { id: 't4', title: 'Pitch Deck', type: 'presentation', uses: 74, tone: 'from-amber-600/40 to-orange-600/40' },
  { id: 't5', title: 'Meeting Notes', type: 'notes', uses: 340, tone: 'from-cyan-600/40 to-sky-600/40' },
  { id: 't6', title: 'Research Brief', type: 'research', uses: 58, tone: 'from-rose-600/40 to-red-600/40' },
];