// UI configuration for the Documents & Reports workspace.
// Contains presentation constants and clearly-labelled starter prompts only.
// It holds NO documents: every document shown in the UI is a persisted row.

export const NAV = [
  { id: 'recent', label: 'Recent', icon: 'Clock' },
  { id: 'ai', label: 'Generated by AI', icon: 'Sparkles' },
  { id: 'starters', label: 'Starter prompts', icon: 'LayoutTemplate' },
];

export const TYPES = [
  { id: 'report', label: 'Report', icon: 'FileBarChart', tone: 'from-violet-600/40 to-indigo-600/40' },
  { id: 'proposal', label: 'Proposal', icon: 'FileText', tone: 'from-sky-600/40 to-blue-600/40' },
  { id: 'contract', label: 'Contract', icon: 'ScrollText', tone: 'from-fuchsia-600/40 to-pink-600/40' },
  { id: 'presentation', label: 'Presentation', icon: 'Presentation', tone: 'from-amber-600/40 to-orange-600/40' },
  { id: 'document', label: 'Document', icon: 'FileType', tone: 'from-emerald-600/40 to-teal-600/40' },
  { id: 'research', label: 'AI Research', icon: 'Microscope', tone: 'from-rose-600/40 to-red-600/40' },
  { id: 'notes', label: 'Meeting Notes', icon: 'NotebookPen', tone: 'from-cyan-600/40 to-sky-600/40' },
];

export const FORMATS = [
  { id: 'md', label: 'Markdown', tone: 'text-violet-300 bg-violet-400/10' },
  { id: 'pdf', label: 'PDF', tone: 'text-rose-300 bg-rose-400/10' },
  { id: 'docx', label: 'DOCX', tone: 'text-sky-300 bg-sky-400/10' },
  { id: 'pptx', label: 'PPTX', tone: 'text-amber-300 bg-amber-400/10' },
  { id: 'csv', label: 'CSV', tone: 'text-emerald-300 bg-emerald-400/10' },
];

export const SOURCE_LABEL = {
  manual: 'Written here',
  ai_generated: 'AI generated',
  ai_summarise: 'AI summary',
  ai_rewrite: 'AI rewrite',
  ai_translate: 'AI translation',
  ai_analyse: 'AI analysis',
};

// Transforms that run against the currently selected persisted document.
export const TRANSFORMS = [
  { id: 'summarise', label: 'Summarise', desc: 'Condense this document', icon: 'ScrollText', tone: 'from-sky-600/40 to-blue-600/40' },
  { id: 'rewrite', label: 'Rewrite', desc: 'Refine tone & clarity', icon: 'PenLine', tone: 'from-fuchsia-600/40 to-pink-600/40' },
  { id: 'translate', label: 'Translate', desc: 'Faithful translation', icon: 'Languages', tone: 'from-amber-600/40 to-orange-600/40' },
  { id: 'analyse', label: 'Analyse', desc: 'Insights & risks', icon: 'Microscope', tone: 'from-emerald-600/40 to-teal-600/40' },
];

// Starter prompts are prompt text only — never presented or counted as documents.
export const STARTER_PROMPTS = [
  { id: 's1', title: 'Executive summary', doc_type: 'report', prompt: 'Write an executive summary report for the current quarter. Leave clearly marked placeholders wherever I have not supplied figures.' },
  { id: 's2', title: 'SaaS proposal', doc_type: 'proposal', prompt: 'Draft a SaaS proposal covering scope, deliverables, timeline, commercial model and assumptions. Mark any unknown commercial detail as a placeholder.' },
  { id: 's3', title: 'Mutual NDA outline', doc_type: 'contract', prompt: 'Draft the structure and plain-English section outline of a mutual NDA. Do not invent binding legal wording; mark clauses that need legal review.' },
  { id: 's4', title: 'Pitch deck outline', doc_type: 'presentation', prompt: 'Outline a 12-slide pitch deck, one section per slide, with the key message and the evidence each slide needs.' },
  { id: 's5', title: 'Meeting notes template', doc_type: 'notes', prompt: 'Produce a meeting notes structure with attendees, decisions, risks and owner-assigned actions.' },
  { id: 's6', title: 'Research brief', doc_type: 'research', prompt: 'Create a research brief structure covering the question, method, sources to gather, and how findings will be validated.' },
];
