// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role/secret key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type SupabaseAdminKeySource =
  | "SUPABASE_SECRET_KEY"
  | "SUPABASE_SECRET_KEYS"
  | "SUPABASE_SERVICE_ROLE_KEY";

export type SupabaseAdminKey = {
  key: string;
  source: SupabaseAdminKeySource;
};

type SupabaseAdminEnvironment = Record<string, string | undefined>;

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function cleanSecretKey(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const cleaned = value.trim();
  return cleaned.startsWith("sb_secret_") ? cleaned : null;
}

function secretKeysFromCollection(raw: string | undefined): string[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return [];

    const record = parsed as Record<string, unknown>;
    const candidates: string[] = [];
    const preferred = cleanSecretKey(record["default"]);
    if (preferred) candidates.push(preferred);
    for (const [name, value] of Object.entries(record)) {
      if (name === "default") continue;
      const key = cleanSecretKey(value);
      if (key) candidates.push(key);
    }
    return [...new Set(candidates)];
  } catch {
    return [];
  }
}

/**
 * Resolve every privileged server key Blackstar has been explicitly configured
 * with, in preferred order. This lets the server survive a staged Supabase key
 * rotation without exposing or persisting any key material elsewhere.
 */
export function resolveSupabaseAdminKeyCandidates(
  env: SupabaseAdminEnvironment = process.env,
): SupabaseAdminKey[] {
  const candidates: SupabaseAdminKey[] = [];
  const directSecret = cleanSecretKey(env["SUPABASE_SECRET_KEY"]);
  if (directSecret) candidates.push({ key: directSecret, source: "SUPABASE_SECRET_KEY" });

  for (const key of secretKeysFromCollection(env["SUPABASE_SECRET_KEYS"])) {
    candidates.push({ key, source: "SUPABASE_SECRET_KEYS" });
  }

  const legacy = env["SUPABASE_SERVICE_ROLE_KEY"]?.trim();
  if (legacy) candidates.push({ key: legacy, source: "SUPABASE_SERVICE_ROLE_KEY" });

  const seen = new Set<string>();
  return candidates.filter((candidate) => {
    if (seen.has(candidate.key)) return false;
    seen.add(candidate.key);
    return true;
  });
}

/**
 * Resolve the preferred privileged key for compatibility with callers/tests that
 * only need one credential. Ambiguous named collections do not outrank the legacy
 * fallback; the runtime fetch layer can still try those named keys safely if the
 * preferred credential is rejected by Supabase.
 */
export function resolveSupabaseAdminKey(
  env: SupabaseAdminEnvironment = process.env,
): SupabaseAdminKey | null {
  const directSecret = cleanSecretKey(env["SUPABASE_SECRET_KEY"]);
  if (directSecret) return { key: directSecret, source: "SUPABASE_SECRET_KEY" };

  const collection = secretKeysFromCollection(env["SUPABASE_SECRET_KEYS"]);
  if (collection.length === 1) return { key: collection[0]!, source: "SUPABASE_SECRET_KEYS" };
  if (collection.length > 1) {
    try {
      const parsed = JSON.parse(env["SUPABASE_SECRET_KEYS"] ?? "{}") as Record<string, unknown>;
      const preferred = cleanSecretKey(parsed["default"]);
      if (preferred) return { key: preferred, source: "SUPABASE_SECRET_KEYS" };
    } catch {
      // Malformed collections fall through to the legacy compatibility key.
    }
  }

  const legacy = env["SUPABASE_SERVICE_ROLE_KEY"]?.trim();
  if (legacy) return { key: legacy, source: "SUPABASE_SERVICE_ROLE_KEY" };

  return null;
}

async function isRejectedApiKey(response: Response): Promise<boolean> {
  if (response.status !== 401) return false;
  try {
    const text = (await response.clone().text()).slice(0, 1000).toLowerCase();
    return text.includes("invalid api key");
  } catch {
    return false;
  }
}

function headersForAdminKey(input: RequestInfo | URL, init: RequestInit | undefined, key: string) {
  const headers = new Headers(
    typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
  );
  if (init?.headers) new Headers(init.headers).forEach((value, name) => headers.set(name, value));

  // This is a server-only elevated client and never carries a user session. Replace
  // the SDK's API-key Authorization header on every attempt so a rejected candidate
  // cannot leak into the fallback request.
  headers.delete("Authorization");
  headers.set("apikey", key);
  if (!isNewSupabaseApiKey(key)) headers.set("Authorization", `Bearer ${key}`);
  return headers;
}

/**
 * Supabase key-rotation-aware fetch. A fallback is attempted only when Supabase
 * explicitly reports `Invalid API key` with HTTP 401. Application/RLS/server
 * errors are returned unchanged, so non-idempotent writes are never replayed after
 * an authenticated response.
 */
export function createSupabaseAdminFetch(
  candidates: SupabaseAdminKey[],
  fetchImpl: typeof fetch = fetch,
): typeof fetch {
  let activeIndex = 0;

  return async (input, init) => {
    if (!candidates.length) return fetchImpl(input, init);
    const order = [
      activeIndex,
      ...candidates.map((_, index) => index).filter((index) => index !== activeIndex),
    ];

    let lastResponse: Response | null = null;
    for (const index of order) {
      const candidate = candidates[index];
      if (!candidate) continue;
      const response = await fetchImpl(input, {
        ...init,
        headers: headersForAdminKey(input, init, candidate.key),
      });
      lastResponse = response;
      if (!(await isRejectedApiKey(response))) {
        activeIndex = index;
        return response;
      }
    }
    return lastResponse ?? fetchImpl(input, init);
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const candidates = resolveSupabaseAdminKeyCandidates();
  const preferred = resolveSupabaseAdminKey();

  if (!SUPABASE_URL || !preferred || !candidates.length) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!preferred || !candidates.length
        ? ["SUPABASE_SECRET_KEY/SUPABASE_SECRET_KEYS/SUPABASE_SERVICE_ROLE_KEY"]
        : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, preferred.key, {
    global: {
      fetch: createSupabaseAdminFetch(candidates),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with elevated server credentials - bypasses RLS.
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
