// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role/secret key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type SupabaseAdminKeySource =
  | "SUPABASE_SECRET_KEY"
  | "SUPABASE_SECRET_KEYS"
  | "SUPABASE_SERVICE_ROLE_KEY";

type SupabaseAdminKey = {
  key: string;
  source: SupabaseAdminKeySource;
};

type SupabaseAdminEnvironment = Record<string, string | undefined>;

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function cleanSecretKey(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const cleaned = value.trim();
  return cleaned.startsWith("sb_secret_") ? cleaned : null;
}

function secretKeyFromCollection(raw: string | undefined): string | null {
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;

    const record = parsed as Record<string, unknown>;
    const preferred = cleanSecretKey(record["default"]);
    if (preferred) return preferred;

    const candidates = Object.values(record)
      .map(cleanSecretKey)
      .filter((value): value is string => Boolean(value));
    return candidates.length === 1 ? candidates[0]! : null;
  } catch {
    return null;
  }
}

/**
 * Resolve the privileged server key without ever logging or returning key material
 * beyond this server-only module. Prefer Supabase's rotatable modern secret-key
 * variables, while retaining the legacy service-role key as a compatibility fallback.
 */
export function resolveSupabaseAdminKey(
  env: SupabaseAdminEnvironment = process.env,
): SupabaseAdminKey | null {
  const directSecret = cleanSecretKey(env["SUPABASE_SECRET_KEY"]);
  if (directSecret) return { key: directSecret, source: "SUPABASE_SECRET_KEY" };

  const collectionSecret = secretKeyFromCollection(env["SUPABASE_SECRET_KEYS"]);
  if (collectionSecret) return { key: collectionSecret, source: "SUPABASE_SECRET_KEYS" };

  const legacy = env["SUPABASE_SERVICE_ROLE_KEY"]?.trim();
  if (legacy) return { key: legacy, source: "SUPABASE_SERVICE_ROLE_KEY" };

  return null;
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const resolvedKey = resolveSupabaseAdminKey();

  if (!SUPABASE_URL || !resolvedKey) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!resolvedKey
        ? ["SUPABASE_SECRET_KEY/SUPABASE_SECRET_KEYS/SUPABASE_SERVICE_ROLE_KEY"]
        : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, resolvedKey.key, {
    global: {
      fetch: createSupabaseFetch(resolvedKey.key),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with elevated server credentials - bypasses RLS.
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
